### ISSUE TITLE
Invertebrate Taxon Data - Karl Reinecke

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#10]
Data from:

Reinecke   M.K. | 2008 | Spontaneous succession of riparian vegetation and aquatic macroinvertebrates along the Silvermine River, South Africa, after fire and clearing of exotic plant   species. MSc thesis.   Zoology Department. University of Cape Town, South Africa.
[Reinecke M.K. 2008.pdf](https://github.com/helendallas/FRC_FBIS/files/3630844/Reinecke.M.K.2008.pdf)

https://www.dropbox.com/sh/4h3ktgzkxgypfu2/AAChAylE8NV9_eEyYBfeuaaba?dl=0

@toniolsen 
Please can you indicate if this was done yet. I moved it from SASS to Inverts.

**Comment by toniolsen** [comment]
@helendallas, no it has not been done yet.

**Comment by helendallas** [comment]
Site information on page 30 of thesis:
4 sites (Site 4 is an extra one  -see details from Karl:
Site 4 is just d/s of site 3 and tributary 5 where the old poplar forest used to be, just u/s of the homestead

See map and table
![image](https://user-images.githubusercontent.com/45286876/65407800-ee7d1400-dde3-11e9-85ad-fc9567489f1a.png)

Aquatic macro-invertebrates collected:
April 2001
March 2002

Because of differences in mesh sizes and sampling methods his samples cannot be called SASS Samples. Thus include as Invertebrate Taxon Data NOT SASS Data.

I have emailed Karl Reinecke for clarity on the electronic data that he sent. Awaiting his response.

**Comment by helendallas** [comment]
@Aneri16 

The file below was received from Karl in response to my query. Please have a look and see if you can work it out. Then check with me to see we are on the same page.

His comments to my queries will be forwarded in a separate email.

File is: Karl Reinecke Invert data.xlsx

In folder
https://www.dropbox.com/sh/4h3ktgzkxgypfu2/AAChAylE8NV9_eEyYBfeuaaba?dl=0


Thanks

All new completed invertebrate data now needs to be added to :
https://www.dropbox.com/sh/3lrrqeup1sqaxni/AADaXjW9Ujg3G7w5T6g4RMraa?dl=0

**Comment by aneriswanepoel** [comment]
@helendallas 
Okay I have have finished extracting this data and it is on Dropbox in the "Data to combine" folder

**Comment by helendallas** [comment]
@Aneri16 
Please can you change the codes as per those needed by Dimas. Thanks. Alos pelase change the master template.

Also remember Collector/Owner needs to be First Name, Surname, so Karl Reinecke
Authors(s) - change to format Dimas needs

Also I had to change date format again.

Please also add taxonomy as per Master list up until Order.
I have updated to new template, please just change above.

**Comment by Aneri16** [comment]
Okay checking now. Does the invert spreadsheet need the Turbidity column?

**Comment by helendallas** [comment]
@Aneri16 Check I revised spreadsheet after email. Should have correct labels etc. Just chec:
Also remember Collector/Owner needs to be First Name, Surname, so Karl Reinecke
Authors(s) - change to format Dimas needs

Also I had to change date format again.

Please also add taxonomy as per Master list up until Order.

**Comment by aneriswanepoel** [comment]
Okay so just to confirm - adding taxonomy from Species through to Order?

**Comment by aneriswanepoel** [comment]
@helendallas Okay I have checked the sheet and added taxonomy
