### ISSUE TITLE
Bellingham 2017 - conductivity data to be recaptured

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#102]
@Aneri16 
It looks like you captured average conductivity (EC) data for the Rondegat River. The data is available per sampling month.

Please can you update this data and also check all other variables, to make sure the average has not been captured.

Data is available is the following spreadsheet
[Environmental Data - Rondegat river.xlsx](https://github.com/helendallas/FRC_FBIS/files/4139070/Environmental.Data.-.Rondegat.river.xlsx)

The conversion looks correct here. uS/cm to mS/m divide by 10.

**Comment by Janette-Lumley** [comment]
@helendallas all the water quality data has now been changed as per the spreadsheet.
