### ISSUE TITLE
Ad hoc Data spreadsheet  -missing lat and long

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#104]
@Janette-Lumley 
Please can you add missing latitude and longitudes for the sites in the Ad Hoc datasheet. It is the last issue before I can consolidate the data. 

I have filtered on blanks.

https://www.dropbox.com/s/heibw5d006uwbov/Adhoc%20Data%20New%202019_10_03.xlsx?dl=0

[Adhoc Data New 2019_10_03.xlsx](https://github.com/helendallas/FRC_FBIS/files/4224955/Adhoc.Data.New.2019_10_03.xlsx)

**Comment by Janette-Lumley** [comment]
@helendallas I have added the missing latitude and longitudes. I couldn't find the data for 2 sites (Holsloot and Schusters) so I used Google earth according to the site descriptions.

**Comment by helendallas** [comment]
@Janette-Lumley Thanks

Please can you go through the ad hoc file once more.  I had to change the fields to match the master list, and I don't think that all of the upload links are working.  **Specifically check:**

Collector/Owner | Institute | Author(s) | Year | Source | Title | Reference category | URL | DOI | Document Upload Link
