### ISSUE TITLE
Refine layer drawers and get info drawers

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#105]
@helendallas we need to decide what to do with 'not so useful' fields currently on display for spatial layers and filters. 

For example, we must make a call on (1) what to show when a user clicks on a layer?

<img width="350" alt="Screenshot 2020-02-29 at 17 05 31" src="https://user-images.githubusercontent.com/44292029/75659392-925fcb00-5c72-11ea-97a1-f3891f280997.png">

And (2) what to show/hide from a user in the filter drawers (some of what's currently being displayed is not useful to the user)

<img width="284" alt="Screenshot 2020-03-02 at 10 46 35" src="https://user-images.githubusercontent.com/44292029/75659744-2a5db480-5c73-11ea-998d-f56e33ae2e03.png">

**Comment by helendallas** [comment]
@jeremyshelton Lets chat thursday
