### ISSUE TITLE
Is the 'Collector/owner' column really working?

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#106]
For almost every Sandelia capensis record (see csv download below) the 'Collector/owner' column is just 'FBIS'. That's not very useful, and seems a bit weird? Maybe better to just hide that column, and tell on the Reference column as the link to the human(s) who collected the data? Thoughts @Aneri16 @helendallas ?

[OccurrenceData-5.xlsx](https://github.com/helendallas/FRC_FBIS/files/4347380/OccurrenceData-5.xlsx)

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
So I remember making "FBIS" the collector/owner for most of the Cape Nature and DWS database records because the data was collected by a number people unlikely to join FBIS (as we agreed to do in order to save time) with the exception of a few names like Dean Impson etc. However the other records should definitely have the collector/owner names so not sure what is happening there

**Comment by aneriswanepoel** [comment]
From what I can see, the only names present in the owner/collector column are Jeremy_Shelton, Helen_Dallas and Toni_Olsen which are your FBIS user names. Perhaps FBIS is only recognizing names that are on the system already, and everyone else who isn't on FBIS yet gets assigned "FBIS"? Just a guess..

**Comment by helendallas** [comment]
@jeremyshelton I assume this will of been resolved with the revised fish data which has actual Owner/Collector for most, and FBIS for some. If you confirm please close the ticket.

**Comment by jeremyshelton** [comment]
Oh right, yes looking at the spreadsheet I agree - this should be resolved with the latest fish data 👍

**Comment by helendallas** [comment]
@jeremyshelton Please check if this has been resolved, and if yes, close the issue.

**Comment by jeremyshelton** [comment]
@helendallas CSV downloads for some fish species not working at the moment. S capensis is one of them, so I can't test at this point. Will check as soon as Dimas fixes the fish csv downloads.

**Comment by helendallas** [comment]
@jeremyshelton I checked now, seems to be sorted. PLease confirm. FIle attached.
[FishOccurrence.xlsx](https://github.com/helendallas/FRC_FBIS/files/5107706/FishOccurrence.xlsx)
