### ISSUE TITLE
Origin dropdown options query

### ISSUE THREAD

**Issue by philipfrenzel** [helendallas/FRC_FBIS#109]
Hi @helendallas 

I was wondering whether you had been able to make a ticket for Dimas regarding the origin dropdown options? I recall us having a discussion at our last internal Zoom meeting about whether to add an 'unknown' option given that these data are all unknown for algal taxa. The options would, therefore, be: Native, Non-native and Unknown.

Not sure whether that will change the dashboard displays too? And the implications of this?

@jeremyshelton

**Comment by helendallas** [comment]
@philipfrenzel @jeremyshelton I have already added ticket to FBIS V4

#1996

**Comment by philipfrenzel** [comment]
@helendallas many thanks.
