### ISSUE TITLE
SASS Data - Eerste River Helen Dallas

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#11]
SASS data to be captured on freshwaterbiodiversity.org
All site: G1EERS-JONKE; Owner Helen Dallas

@Aneri16 
Assigned to do this, please sit with @helendallas to learn how to do the data capture

https://www.dropbox.com/sh/seg79zhl4nv3tuz/AABe5vGygPkqWkYITx3dv1gva?dl=0

**Comment by helendallas** [comment]
@Aneri16 please comment on status of this please.

**Comment by aneriswanepoel** [comment]
I have completed the data capture on FBIS and the PDFs that I worked with were all correct as far as I know so what is on FBIS should be final.
