### ISSUE TITLE
Citations in Testing

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#110]
@Aneri16 
I found some strange citations in the Citations on testing. 

https://testing.healthyrivers.kartoza.com/bibliography/?year=&author=&doi_exist=&q=

![image](https://user-images.githubusercontent.com/45286876/79547916-ebee4e80-8094-11ea-906e-a5e87b69a67c.png)

Please can you check the fish data to see they are correct.  Please can you check Citations on the testing site and correct if these are real issues in the fish data file. They may be artifacts of the DOIs and URLs

 @jeremyshelton fyi

**Comment by aneriswanepoel** [comment]
@helendallas the referencing is correct in the spreadsheet so not sure why it has been pulled into FBIS so strangely...

**Comment by helendallas** [comment]
@jeremyshelton Did these citations come through correctly in the new fish ingestion?

**Comment by jeremyshelton** [comment]
@helendallas @Aneri16 

Unfortunately these issues still persist on the testing site. 

Should we make a ticket to ask Dimas?

**Comment by helendallas** [comment]
@jeremyshelton Yes, we definately need to make a ticket. Something has either not been cleared out before reingestion, or it is because it is the testing site and not the live site. Perhaps make a ticket Jeremy to ask him to check why. Aneri has spent a lot of time fixing documents on the live site.

**Comment by jeremyshelton** [comment]
@helendallas done. #2060 on Kartoza GitHub
