### ISSUE TITLE
FBIS V4 Consolidate Invertebrate data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#111]
@Aneri16 

What would be really helpful is to start consolidating the data from each invert study into the new FBIS invert data file for ingesting into FBIS next round.

Dropbox Folder: FRC_FBIS Data for Consolidation/ Data for Consolidation/ Invertebrate Data/ CFR Invertebrate data Species/ Final for FBISv4
https://www.dropbox.com/sh/3lrrqeup1sqaxni/AADaXjW9Ujg3G7w5T6g4RMraa?dl=0

New data file to use is: SA Invertebrate Data for FBISv4 2020_06_23.xlsx

**For each study that you add, you need to:**

1. 1Make sure the columns match up to FBISv4 2020_06_23.xlsx
2. Check all taxonomy – each taxon needs to be as per the SA Invertebrate Master List FBISv3_11 May 2020.xlsx. If any taxon is missing please add it to the data file and highlight it in yellow. I will then need to check why it is not in the Master file.
3. Make sure the taxon rank in the data file matches taxon rank specified in the SA Invertebrate Master List FBISv3_11 May 2020.xlsx
4. Make sure all formats such as date etc are correct.
5. Use the filters to check for typos, duplicates with one letter different etc.
6. Where possible populate Original River name, Original Site Code, Site description and Refined geomorphological zone. Please check studies if missing.
7. Check formats of collector/Owner, authors, URL, DOI, etc. as you have done previously. Remember if a thesis the URL should be added, not the pdf.

**Studies ready to consolidate include:**
Ketley, Z.A. 2009_For revision 2020_04_16.xlsx
Reinecke, M.K. 2008.xlsx
Bellingan, T.A. 2017_For revision 2020_04_22.xlsx
Eady, B.R. 2009.xlsx

Please ask for clarification if needed, thanks

**Comment by aneriswanepoel** [comment]
Data consolidation is complete but must still add UUIDs. Missing taxa highlighted in the Taxon column

**Comment by aneriswanepoel** [comment]
Comments from Helen Dallas

 Simulium albivirgulatum - added to Master List (orange)

Stratiomyia - added to Master List (orange)

Teratothyasa - added to Master List (orange)

Nitidulidae - added to Master List (orange)

Mytilidae - added to Master List (orange)

Nymphulinae - corrected to Crambidae

Chlorosyphidae - spelling, should be Chlorocyphidae

Forcipomyiinae -  subFamily of Ceratopogonidae - added to Master List (orange)

Pyraustidae - corrected to Crambidae

 Note - all new taxa in Master list have been highlighted in Organe

e.g. Species | Animalia | Arthropoda | Insecta | Diptera | Simuliidae | Simulium | albivirgulatum

**Comment by aneriswanepoel** [comment]
@helendallas I have found one more taxon that is not in the masterlist - Centroptiloides bifasciata

**Comment by helendallas** [comment]
@Aneri16 This is spelt incorrectly. It should be
Centroptiloides bifasciatum

This is in the master list. Please can you update on the data file, thanks

**Comment by aneriswanepoel** [comment]
@helendallas okay done. That should be it for this data file then

**Comment by helendallas** [comment]
@Aneri16 Please can you add the following to the consolidated file:
[AdHoc_For revision 2020_07_28.xlsx](https://github.com/helendallas/FRC_FBIS/files/5107625/AdHoc_For.revision.2020_07_28.xlsx)
[Brown, C.A. 1998_For revision 2020_07_14.xlsx](https://github.com/helendallas/FRC_FBIS/files/5107626/Brown.C.A.1998_For.revision.2020_07_14.xlsx)

And check that all the others in the Final for FBISv4 have been included.
Thanks

**Comment by aneriswanepoel** [comment]
@helendallas I have added the above two, and the other studies are all there. Just need to add UUIDs

**Comment by helendallas** [comment]
@Aneri16 Thanks, please also check all taxa are on the master list and alert me to any that are not in this ticket. Thanks
