### ISSUE TITLE
Corrected algal data needs to be reinjested

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#113]
Awaiting corrected algal data with duplicates removed from @philipfrenzel 

Once received Dimas will reinjest.

**Comment by helendallas** [comment]
@philipfrenzel @Aneri16 
Phil - if you are battling to finalise these, please can you spend some time with Aneri giving her the low down.

**Comment by aneriswanepoel** [comment]
@helendallas @philipfrenzel I have finished correcting the duplicates.     File is on Dropbox:
https://www.dropbox.com/s/q3c7mku12yqtqza/SA%20Algal%20Data%20For%20FBISV3_PF%20to%20AS%2026-10-2020.xlsx?dl=0

**Comment by helendallas** [comment]
@Aneri16 Thanks. I will check next week and organise reingestion. Thanks so much. I will shout if I have any quereis

**Comment by helendallas** [comment]
@Aneri16 Thanks Aneri. Looks fine.
