### ISSUE TITLE
Extract GBIF information for Branchiopoda

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#114]
@Aneri16 Please can you:

- add the GBIF links for each taxon in the Branchiopoda
- Check and add Scientific name and authority
- Add common name if available

The link for the GBIF taxonomic backbone is:
https://www.gbif.org/species/2235078

Enter taxon in:
![image](https://user-images.githubusercontent.com/45286876/91447140-9f9ff000-e878-11ea-8614-ffe2276e3030.png)

Here is the file:
[SA Invertebrate Master List FBISv3_11 May 2020 Branchiopoda Only.xlsx](https://github.com/helendallas/FRC_FBIS/files/5136660/SA.Invertebrate.Master.List.FBISv3_11.May.2020.Branchiopoda.Only.xlsx)

In this folder:
https://www.dropbox.com/sh/yx3aj7p3kfe5rjv/AAAX1oIkaYfhOoZxTOmjeXRfa?dl=0

**Comment by aneriswanepoel** [comment]
@helendallas I have finished the Branchipods - taxa missing from GBIF highlighted in orange, as well as any other queries (eg spelling). File is in the Taxonomy folder, with today's date (1 September 2020)
