### ISSUE TITLE
Extract GBIF data for Plecoptera

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#115]
@Aneri16 Please can you:

-     add the GBIF links for each taxon in the Order Plecoptera
-     Check and add Scientific name and authority
-     Add common name if available

The link for the GBIF taxonomic backbone is:
https://www.gbif.org/species/2235078

Enter taxon in:
image

Here is the file:
[SA Invertebrate Master List FBISv3_11 May 2020 Plecoptera only.xlsx](https://github.com/helendallas/FRC_FBIS/files/5136759/SA.Invertebrate.Master.List.FBISv3_11.May.2020.Plecoptera.only.xlsx)

In this folder:
https://www.dropbox.com/sh/yx3aj7p3kfe5rjv/AAAX1oIkaYfhOoZxTOmjeXRfa?dl=0

**Comment by aneriswanepoel** [comment]
@helendallas there is no column for common name - shall I add it?

**Comment by aneriswanepoel** [comment]
@helendallas just finished - again highlighted in orange the taxa that are not on GBIF. File is in the taxonomy folder with today's date

**Comment by helendallas** [comment]
@Aneri16 Thanks very much. I will generate a few more groups for checking soonest. Its a big help.
