### ISSUE TITLE
Extract GBIF data for Hemiptera 

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#116]
PLease can you extarct GBIF link, add scientific anme and authority, common name and check on details for Hempitera

FIle is Here:
https://www.dropbox.com/sh/yx3aj7p3kfe5rjv/AAAX1oIkaYfhOoZxTOmjeXRfa?dl=0

**Comment by aneriswanepoel** [comment]
@helendallas done - file with today's date
Shall I continue with Ephemeroptera and Mollusca?

**Comment by aneriswanepoel** [comment]
@helendallas finished with Mollusca - on Dropbox with today's date (15 September 2020). Would you like me to start with Ephemeroptera?
