### ISSUE TITLE
Change owner from Aneri Swanepoel to correct owner

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#118]
@Aneri16 For some reason you have been assigned ownership of these data. Please can you edit and assign correct owner.

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=[%22Aneri%20Swanepoel%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

Click on See more Site Visits
![image](https://user-images.githubusercontent.com/45286876/99647273-3a643100-2a5a-11eb-8b7c-fbc09173e116.png)

We can chat through workflow for this

**Comment by helendallas** [comment]
Can you also please figure out if these data were captured on the FBIS site or ingested, if the latter then we need to make sure ingested data are correctly assigned ownership.

**Comment by aneriswanepoel** [comment]
@helendallas okay will have a look tomorrow

**Comment by aneriswanepoel** [comment]
@helendallas 
I have tried to edit one of the sites so far - G1KUIL-00003
The correct collector/owner is F Mwangi. 
However, when I replaced my name with F Mwangi, your name got added as Collector for some reason. I am logged in as myself.

![Owner collector error](https://user-images.githubusercontent.com/55532903/99769773-87eea580-2b0f-11eb-826f-ad63c26809e9.png)

![collector error](https://user-images.githubusercontent.com/55532903/99769790-8de48680-2b0f-11eb-8721-f64f593db742.png)

Thoughts?

**Comment by aneriswanepoel** [comment]
@helendallas and then for another site G1KUIL-00009 I've had a look at whether data has been uploaded or ingested. 
The invert data has been uploaded by me (again F Mwangi data) but the fish data was ingested with Cape Nature SOB Database as source and Cape Nature specified as Author in the spreadsheet. However the Author column in the metadata table is blank.

![Author blank](https://user-images.githubusercontent.com/55532903/99771138-4959ea80-2b11-11eb-96be-342141578d3f.png)

I definitely would have added the correct owner/collector when uploading the data, and the correct author data is in the spreadsheet so not sure if FBIS is just not registering these things for some reason and then automatically making me the collector/owner?

**Comment by helendallas** [comment]
@Aneri16 Okay, I am not sure what is going on. Perhaps leave for now.

**Comment by helendallas** [comment]
@aneriswanepoel Please change ownership for these sites to the correct owner, You are listed as the owner.

![image](https://user-images.githubusercontent.com/45286876/122222173-4dd16080-ceb2-11eb-87a6-67e819f783b3.png)

**Comment by aneriswanepoel** [comment]
@helendallas that's really odd because I just checked those sites now and do not see my name as owner. Instead can only see the following:
E2GROO-EWR06 owner listed as Helen Dallas
H2HEXR-00005 & H2HEXR-00029 owner listed as D. Christie
H6DUTO-00055 owner listed as Kate Snaddon

**Comment by helendallas** [comment]
@aneriswanepoel I have gone through all these data and revised and now you are not the owner of any site. To remember:
Ownership is at both Site and Site Visit (Site + Sampling date)

Closing for now.
