### ISSUE TITLE
King and Schael 2001 Invertebrate data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#119]
@aneri Please can extract data from King and Schael 2001

File template to use is here: SA Invertebrate Data for FBISv5.xlsx
https://www.dropbox.com/sh/oyedi12bigmfzza/AAAa7X8Yi4bdJYLKr7SrfUfwa?dl=0

And the master list for checking taxa against.
SA Invertebrate Master List FBISv3_2020_10_16.xlsx

Please name data accordingly, thanks.

River and sites information is in Table 5.1. Ignore Zone
Appendix 8.1 is the species list. All species only have a presence or absence, just just include those with a A "+" denotes species presence. 

Table 7.1 Water chemistry - not sure if it was a once off. Dont include any dodgy readings.

Sampling method was Box/Surber

Biotopes are far to complicated, so ignore.

I will send you the report via wetransfer as it is over 30mb.

Please ask if you have any questions, thanks

**Comment by aneriswanepoel** [comment]
Completed - just need to generate the UUIDs. File is on Dropbox: https://www.dropbox.com/s/ltxb2w8eemv5hxc/King%20%26%20Schael%20invert%20data%20March%202021.xlsx?dl=0

**Comment by helendallas** [comment]
@aneriswanepoel 
Please confirm why the conductivity values are highlighted, thanks

**Comment by helendallas** [comment]
Also please indicate why some taxa are highlighted. Thanks

**Comment by aneriswanepoel** [comment]
@helendallas 
Conductivity was highlighted because I needed to check that the values were in the correct units (I had to convert μS/cm to mS/m but I must have just forgotten to clear the highlighting afterwards) and the taxa were highlighted because I needed to check against the masterlist for spelling but again forgot to clear the highlighting afterwards. I have cleared the highlighted sections on the Dropbox file now.

**Comment by helendallas** [comment]
Data checked and csv file ready for upload

**Comment by helendallas** [comment]
@aneriswanepoel 
You have added this link:
https://freshwaterbiodiversity.org/documents/384

But Schael is not in the FBIS Source References.  PLease can you check and revert

**Comment by aneriswanepoel** [comment]
@helendallas that's odd... it should be in the Source References page. @Janette-Lumley has also recently added a document via the link that Dimas provided however it also does not reflect on the FBIS Source References page. Seems like there could be a disconnect between the Geonode page and the FBIS Source References page?

**Comment by helendallas** [comment]
@aneriswanepoel I figured out that you were still listed as the author which is why I couldn't find it searching author = Jackie King. I have now fixed the authors and publication year.

Still not visible so I will have to check with Dimas

**Comment by helendallas** [comment]
@helendallas Waiting for source reference issue to be resolved by Dimas before uploading.

**Comment by helendallas** [comment]
Document added to FBIS, but waiting on retrieval of document number to add to upload file before uploading

**Comment by helendallas** [comment]
Uploaded but checking through error files

**Comment by helendallas** [comment]
Still waiting on upload of last two taxa
[Errors Second for King & Schael 2001.xlsx](https://github.com/helendallas/FRC_FBIS/files/7433903/Errors.Second.for.King.Schael.2001.xlsx)

**Comment by helendallas** [comment]
All data uploaded

@aneriswanepoel Please can you check all the site locations and do a random check of the data uploaded. I found quite a few issues with taxa, spelling, etc so please always be vigilant when checking if a taxon is in the master list. Thanks

The final csv files uploaded are here:
https://www.dropbox.com/sh/t6sjq53b0czr053/AADEwbUookoYRdKS_bcu0d4Ma?dl=0

Here is the URL

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221053%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by aneriswanepoel** [comment]
@helendallas will do. I can already see one site has ended up in the ocean so will investigate
