### ISSUE TITLE
SASS Data - Diep River

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#12]
Assign Biotope ratings based on datasheets
Assign all taxa and abundance = A, if not abundance values are given then no graphs are produced and scores cannot be calculated.

Add the following in the comments field:
![Screenshot_2019-09-19 FBIS SASS(4)](https://user-images.githubusercontent.com/45286876/65256296-99997f00-daff-11e9-96bb-70b4b0233abc.png)

Helen Dallas has the data - please come and speak to her about it.

**Comment by aneriswanepoel** [comment]
Certain sites still to be checked by HD

**Comment by helendallas** [comment]
Please reopen

**Comment by helendallas** [comment]
@Aneri16 
There were some sites that did not have codes, that I set aside - what did you do with these?

Please remember to comment and dont close any tickets.

**Comment by aneriswanepoel** [comment]
Oh sorry, I didn't realize I was closing the thread! Those sites haven't been checked on FBIS because there aren't any site codes for them. I think you wanted to still check re site codes.
