### ISSUE TITLE
Fish and invertebrate data for AWARD

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#122]

**Comment by aneriswanepoel** [comment]
Received the following data from Kyle on 30 April 2021:

1. SASS data from Robin Peterson
- Still to be uploaded onto FBIS

2. Fish data from Andrew (?)
- Must still have a look at the data and check it has not already been extracted as part of the other data sets

3. Fish data from Robin Peterson
- Still to be extracted

4. Nothobranchius fish data from Brian Watters
- Still to be extracted

5. KNP fish data 2009 
- 3277 records extracted (completed on 5 May 2021; to be checked for duplicates and uploaded onto FBIS)

6. Inkomati fish data 2020
- 439 records extracted (completed on 7 May 2021; to be checked for duplicates and uploaded onto FBIS)

7. Nepid fish data 2018
- 26912 records extracted (in progress; to be checked for duplicates and uploaded onto FBIS)

8. Andrew Russell PhD fish data
- Still to be extracted

9. Louis Olivier thesis fish data
- still to be extracted

@helendallas @Kyle-Mark

**Comment by helendallas** [comment]
Closing ticket as overview
