### ISSUE TITLE
1. Kruger National Park fish database

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#123]
3277 fish records extracted from KNP 2009 fish data
Ready for ingestion into FBIS

**Comment by helendallas** [comment]
Duplicates found and removed by @aneriswanepoel 

@aneriswanepoel to carefully check all Owners and dates, to make sure these are not included in other datasets, and that the dates are accurate.

All issues need to be captured in a separate spreadsheet and emailed to Robin for clarification

**Comment by helendallas** [comment]
@aneriswanepoel Please can you update ticket, rather than in an email
Thanks

**Comment by aneriswanepoel** [comment]
@helendallas 

Owners checked against other datasets for duplicate data - found duplicates that are in the IA Russell thesis spreadsheet. Duplicates removed from KNP 2009 sheet, amounting to 238 duplicates removed.

Only potential duplicate data is from L Olivier (same as the L Olivier thesis data) with the only difference being the year recorded as 1905 in the KNP 2009 dataset. This is likely wrong - therefore L Olivier could be removed from the KNP 2009 dataset as this data is already recorded in the separate L Olivier thesis dataset.

Waiting to hear back from Robin Petersen regarding the incorrectly recorded dates for the above mention data (L Olivier 1905) as well as data for A Deacon 1905 & 1972.

Referencing - waiting to hear from Robin regarding the correct referencing of "TEAM" as Owner/Collector, as well as how the entire KNP 2009 dataset should be referenced (currently it is Unpublished data)

**Comment by helendallas** [comment]
Thanks @aneriswanepoel 

Please remove L Olivier records from this dataset.
Please extract A Deacon 1905 & 1972 records from this dataset and create a separate excel file for checking later. I suspect Robin wont respond timeously.

Revise Team to read : "KNP Fish team"

**Comment by helendallas** [comment]
@aneriswanepoel 

I extracted all U Pienaar data and created a separate file as these data don't belong to Kruger Park.
I have made all data = "Database" This is easier to manage in the future

I standardised database names;
**River Health Programme**

I renamed: Kruger National Park fish data and Kruger National Park Fish Data 2009
to **Kruger National Park fish database**

I replaced: South African National Parks with Kruger National Park Scientific Services as Collector/Owner Institute

**Comment by helendallas** [comment]
Data from #129 added to Kruger National Park Data and source all made Kruger National Park Fish Database

**Comment by helendallas** [comment]
@aneriswanepoel Please check if any of these sites already exist on FBIS, for example, Crocodile river @ Crocodile Bridge is X2CROC-CROCB.
Then add this code to the FBIS Site Code column. The data will then be added to this site.

**Comment by aneriswanepoel** [comment]
@helendallas sites checked against those on FBIS - 13 out of 25 already on FBIS with river health codes. FBIS Site Code Column updated accordingly.

**Comment by aneriswanepoel** [comment]
@helendallas I had a Zoom with Robin to clarify some points: 

- He is going to look at the KNP drive and get back to me re the 1905 Andrew Deacon data.
- As we thought, the 1905 Olivier data is the same data from his thesis.
- TEAM is a group of students, and led by Robin, that collected data so he said we can reference him as the Collector/Owner.
- We must acknowledge SANParks for the collection and use of data, so I assume the Source must then be SANParks.

**Comment by helendallas** [comment]
Data extracted from Nepid that were labelled as Source = Kruger have been combine with data in this file. 
See ticket #142

**Comment by aneriswanepoel** [comment]
@helendallas holding off on FBIS live ingestion until Dimas has sorted out existing codes issue

**Comment by helendallas** [comment]
@aneriswanepoel Please confirm that these data were added to the 
![image](https://user-images.githubusercontent.com/45286876/187643785-5e3bee86-d9ff-4dd1-82bf-9f0fd4729a01.png)

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=["226"]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=["fbis","gbif","virtual_museum"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by aneriswanepoel** [comment]
@helendallas these need to be merged.. but I can't view records for the last two for some reason
![image](https://user-images.githubusercontent.com/55532903/187665009-078e5097-159b-4729-8c65-e1785e27de38.png)

**Comment by helendallas** [comment]
Done.
![image](https://user-images.githubusercontent.com/45286876/187696339-d7a94515-6013-4a70-a86e-43e7793baece.png)
