### ISSUE TITLE
2. Rivers of Life Inkomati fish data 2020

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#124]
438 fish records extracted from Rivers of Life 2020 Inkomati study
Ready for ingestion into FBIS

**Comment by helendallas** [comment]
@aneriswanepoel has emailed KM to check on source reference, as all data currently listed as unpublished

**Comment by aneriswanepoel** [comment]
Duplicate issue resolved.

**Comment by helendallas** [comment]
@aneriswanepoel Please can you provide more detail in the ticket on what the issues were and how they were resolved. thanks

**Comment by aneriswanepoel** [comment]
@helendallas 
Duplicate data was due to Biotope/Substratum data that was initially not included in the dataset but has since been included so there are no more duplicates.

**Comment by helendallas** [comment]
@aneriswanepoel Were there no fish broad biotopes included ?
Slow-Shallow
Slow-Deep
Fast-Shallow
Fast-Deep

**Comment by aneriswanepoel** [comment]
@helendallas no, only substrate data was given

**Comment by helendallas** [comment]
Gordon O'Brian of Rivers for Life emailed re this dataset

**Comment by aneriswanepoel** [comment]
@helendallas existing FBIS codes for three sites added to spreadsheet

**Comment by aneriswanepoel** [comment]
@helendallas do you still want to wait for Gordon O'Brien to get back to you before we upload?

**Comment by helendallas** [comment]
@aneriswanepoel No We have given him long enough. Go ahead and upload, thanks

**Comment by helendallas** [comment]
Uploaded and checked
