### ISSUE TITLE
Other Nepid fish data

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#126]
Busy splitting Nepid fish data into two separate data sets:

1. AWARD-relevant fish data
2. Fish data not relevant to AWARD

**Comment by aneriswanepoel** [comment]
Data split into AWARD and non-AWARD regions to the best of my knowledge but may need to confirm some rivers/areas. Conductivity values divided by 10

**Comment by helendallas** [comment]
Closing ticket as decision to have a single dataset of all Nepid data -  which will then be split into relevant sub datasets for example Mike Coke KZN needs to become a single dataset
