### ISSUE TITLE
Kruger National Park SASS data

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#127]
SASS data to be entered into FBIS with Hendrik Sithole as collector

**Comment by helendallas** [comment]
@aneriswanepoel Please check if any of these sites already exist on FBIS, for example, Crocodile river @ Crocodile Bridge is X2CROC-CROCB.
Then add this code to the FBIS Site Code column. The data will then be added to this site.

I suggest you check all the sites using coordinates on FBIS, if the site exists with river health code, then use this.

**Comment by aneriswanepoel** [comment]
@helendallas sites checked against those on FBIS - 13 out of 25 already on FBIS with river health codes. FBIS Site Code Column updated accordingly.

**Comment by helendallas** [comment]
Source References
![image](https://user-images.githubusercontent.com/45286876/187645328-ca87b1a4-2420-4bee-a481-a5428ede73e5.png)
