### ISSUE TITLE
Brian Watters Nothobranchius data

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#128]
To be extracted

**Comment by aneriswanepoel** [comment]
No useful information

**Comment by helendallas** [comment]
Reviewed but unable to extract any data. FRC received one or two reports/articles, neither of which included any occurrence data.

**Comment by helendallas** [comment]
@aneriswanepoel 
Can you please email Brian to see if he is able to provide georeference for the sites, How much data are there?

![image](https://user-images.githubusercontent.com/45286876/124936395-cab1af00-e006-11eb-8360-1dd9ff15672e.png)

**Comment by aneriswanepoel** [comment]
@helendallas I have tried to email him but email has failed to send... think the address is correct but it automatically failed due to anti-spam

**Comment by aneriswanepoel** [comment]
@helendallas I have emailed Robin Petersen about an alternative email address, or if he knows where I can access the study

**Comment by helendallas** [comment]
Closing ticket as Unable to get original data
