### ISSUE TITLE
SANParks – Limpopo & Komati (RHAM - Robin Petersen)

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#129]
To be extracted

**Comment by aneriswanepoel** [comment]
Complete

**Comment by helendallas** [comment]
@aneriswanepoel 
Also duplicates here – please check.
 
I recommend that you always sort the data as follows:
 
Original River Name
Original Site Code
Sampling Date
Taxon
 
Then add the concatenate column and duplicates checker before finalising the dataset.

**Comment by aneriswanepoel** [comment]
Duplicates checked - its to do with the Biotopes classified as "Mixed" but the specific biotopes are detailed in the Site Description column. So not actually duplicates.

**Comment by helendallas** [comment]
@aneriswanepoel This descriptions are the biotopes GHU means Geomorphological Habitat Unit so a description of specific biotope
So I used description to give specific biotope, for pool-run selected pool, for run-riffle selected run, and then kept description in for details.

**Comment by aneriswanepoel** [comment]
@helendallas ah okay I see, thanks.

**Comment by helendallas** [comment]
@aneriswanepoel 
These data should really be combined with the Kruger dataset,. Data added to Kruger fish database. Ticket closed.
