### ISSUE TITLE
5. Ian Russell PhD fish data

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#130]
To be extracted

**Comment by aneriswanepoel** [comment]
Complete but need to add Document Upload Link once document has been added to FBIS

**Comment by helendallas** [comment]
@aneriswanepoel 

Still to upload pdf of thesis (when ready on FBIS) and add to excel file before uploading.

Sampling date not specified in excel data file although 3 x winter surveys (May - September 1987, 1988 & 1989) & 1 x summer survey (November 1987 - February 1988) were undertaken; and methods used included seine netting and electro-fishing.

**Comment by aneriswanepoel** [comment]
@helendallas PDF has been uploaded to FBIS and DUL copied into the spreadsheet so this is ready for FBIS ingestion

**Comment by aneriswanepoel** [comment]
@helendallas some sites in this data are also existing RHP codes that are on FBIS so have updated accordingly

**Comment by aneriswanepoel** [comment]
@helendallas successfully loaded onto testing site so ready for live site ingestion

**Comment by aneriswanepoel** [comment]
@helendallas uploaded to live site but similar issue with existing FBIS codes not being linked to the new data

**Comment by helendallas** [comment]
No records, @aneriswanepoel Please check after Dimas has fixed missing records issue

**Comment by aneriswanepoel** [comment]
@helendallas all records restored
