### ISSUE TITLE
7. Andrew Deacon FRAI survey data

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#133]
To be extracted from FRAI spreadsheets

**Comment by aneriswanepoel** [comment]
@helendallas 
Methods not specified in the raw data so have selected "Unspecified". I am also not sure what the source of this data is.

**Comment by helendallas** [comment]
@aneriswanepoel Thanks looks fine. Where did you find the lats/longs?

**Comment by aneriswanepoel** [comment]
@helendallas I actually found a report that had used the same sites so was able to find the co-ordinates there for two of the sites, and for the other two sites the co-ordinates were given already

**Comment by helendallas** [comment]
Great thanks @aneriswanepoel

**Comment by helendallas** [comment]
@aneriswanepoel Please check that none of Andrew's data is in the Kruger database, thanks

**Comment by aneriswanepoel** [comment]
@helendallas checked for duplicates. Duplicates removed from FRAI dataset

**Comment by helendallas** [comment]
@aneriswanepoel Please check if any of these sites already exist on FBIS, for example, Crocodile river @ Crocodile Bridge is X2CROC-CROCB.
Then add this code to the FBIS Site Code column. The data will then be added to this site.

**Comment by aneriswanepoel** [comment]
@helendallas sites checked against those on FBIS - 13 out of 25 already on FBIS with river health codes. FBIS Site Code Column updated accordingly.

**Comment by aneriswanepoel** [comment]
@helendallas successfully loaded onto testing site so ready for live site ingestion

**Comment by aneriswanepoel** [comment]
Uploaded to FBIS live

**Comment by aneriswanepoel** [comment]
@helendallas seems the existing FBIS codes were not acknowledged when ingested and new codes were created instead. Will create a ticket too.

**Comment by helendallas** [comment]
Uploaded and checked
