### ISSUE TITLE
Nepid Fish data - remaining

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#134]
The full Nepid  fish dataset received from Kyle needs to be edited to remove subsets of data. PLease work with the full dataset and not the two separate ones split into Award and non-Award.

I spoke to Rob Palmer - the person who collated the database, and he was not even aware it had been shared with us.  A large portion of the dataset includes SAIAB data which we already harvest from GBIF. 

He is however very happy for us to upload the data to FBIS. The dataset includes valuable data from the late Mike Coke (KZN) and the late Johan Engelbrecht (MPU) as well as data from several consultants as well as data extratced by ROb from reports.

So the dataset needs to be thoroughly checked and edited before it is uploaded:

- Remove all data belonging to SAIAB - where the Source is specified as The South African Institute for Aquatic Biodiversity - please confirm that this is data labelled in the raw data file as being from SAIAB.

- Check the data listed as : Institute for Water   Quality Studies | Kleynhans N | 1989 | Department of Water Affairs is not already inFBIS as this may have been part of the Rivers Database.  Also Check Source = unspecified, but owner N Kleynhans as this might also be in FBIS. 

- Check all data listed as Source  = "Kruger Park......" - this may already exist in the Kruger datasets

- Check Angliss M | 2007 | Limpopo Department of Economic   Development, Environment and Tourism - this may already be in FBIS

- Revise all Source = "Nepid....."to Nepid fish data, Rob Palmer, unpublished data

- Please also check all edited data with raw data to ensure correct ownership etc, this one looks strange as not likely to be AfriDev Consultants as Johan was with Mpumalanga Parks Board Johan Engelbrecht | Mpumalanga Parks Board | Engelbrecht J | 1999 | AfriDev Consultants

Once you have done these please let me know so we can check again.

**Comment by aneriswanepoel** [comment]
@helendallas I have so far addressed the first three issues (bullet points) and just putting it here while it is still fresh in my mind:

1. SAIAB data checked against raw spreadsheet and removed from Nepid spreadsheet.

2. - The only Rivers Database data on FBIS is for 1996, 1997, 1998, 1999, 2000 and 2004; there is no 1989 data on FBIS.. 
    - In the Nepid spreadsheet (IWQS - Neels Kleynhans data) there is only data from 1978, 1979, 1989, 1997 and 2013. 
    - The 1997 data is the same as the 1997 Rivers Database data so can be removed from Nepid spreadsheet.
    - The "Unspecified" data is from 1997 and 2013
   
3. With "KNP..." as source, I worked through the list of collectors and found these issues:
    - Andrew Deacon data - listed as 1905 again
    - IA Russell data - a number of duplicates from Thesis data and from KNP data found; all duplicates removed from Nepid 
      spreadsheet
    - NAEBP - listed as 1905
    - U Pienaar data - duplicates from KNP dataset; duplicates removed from Nepid spreadsheet

**Comment by aneriswanepoel** [comment]
@helendallas I have finished checking this dataset:

4. M Angliss 2007 data - extracted in 2020 as part of Mo's expert data and ingested to FBIS; removed from Nepid spreadsheet
5. Nepid data - Source edited
6. AfriDev Consultants - J Engelbrecht listed as Collector in raw data sheet

**Comment by aneriswanepoel** [comment]
@helendallas I have finished checking this spreadsheet so I think it can be uploaded now

**Comment by helendallas** [comment]
@aneriswanepoel 

I dont think this data should be included as is. It is better to separate into different datasets based on Collector/Owner and Collector/Owner Institute and then try and find the original data/report, and or contact the owner. So for example 

- Gerhard Diedericks of Environmental Biomonitoring Services can be emailed. We should check if this data is on FBIS already as he has added fish data.
- Byron Bester - he is a consultant, will need to check.
- ORASECOM 2011 - I dont think we can add this data without getting permission
- Gaigher I, University of Venda - need to contact him or see if data are available in a report of doi
- C Muller, NA Strydom & OLF Weyl - created new dataset and upload to FBIS

So please separate data into separate datasets, create a ticket for each and then we systematically work through them

**Comment by helendallas** [comment]
Closing this ticket as no additional data for these records
