### ISSUE TITLE
8. SAEON Fish data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#135]
Data excel file received from file. Edited for uploading to FBIS.

Some issues noted:
I have done some editing and checking of the SAEON fish data for uploading to FBIS and am finding some duplicate entries. Please see column AX, highlighted in red. The numbers are different so I suspect that these were possibly different Broad biotopes , which you have not specified in the spreadsheet – please see dropdowns.
Slow-Shallow
Slow-Deep
Fast-Shallow
Fast-Deep

Response from Kyle:
Thanks for pointing that out. I amended it and should be fine now. He used abbreviations for the biotopes and didn’t realise that they fit in there. I have put them in now though and it should be good. It is attached here.

From Helen:
Thanks, sorry please check these again as there are still duplicates, with the same biotope, maybe you captured this incorrectly?
Colum AX, red highlighted

Response from Kyle:
Sorry, I should have checked if there were still duplicates. In the raw data, the duplicates are there, but the data has additional columns which make them differ. The columns are:
1.	Width of macrochannel
2.	Width of active channel
3.	Width of surveyed channel
Not sure how we would include that. Any suggestions?

From Helen:
Are you able to check with the authors?  Might it be an incorrect data capture? We cant keep both in, as clearly one of each duplicate has been incorrectly captured?

Kyle, is trying to find out details from the data owner, but he has not been forthcoming in the past.

**Comment by helendallas** [comment]
Emailed Kyle on the 9 July to check on duplicates. Awaiting feedback.

**Comment by helendallas** [comment]
Response from Kyle: Dated 13 July 2021.
I spoke to Tony Swemmer. He said he will go through the original datasheets to check where the duplicates may have come from.

**Comment by aneriswanepoel** [comment]
@helendallas all broad biotope information filled in so I think the duplicate issue is now sorted out

**Comment by helendallas** [comment]
@aneriswanepoel I cannot find this data on FBIS? Please check and include the Source Reference here

**Comment by aneriswanepoel** [comment]
@helendallas it's not on FBIS under SAEON Fish data as this data consists of three different papers, from Thabo Mohlala (of SAEON)

**Comment by helendallas** [comment]
Thanks, Uploaded and checked
