### ISSUE TITLE
9. U Pienaar Kruger fish data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#136]
@aneriswanepoel 

I have extracted all data owned by U Pienaar from the Kruger database. The original owner and citation needs to be the Source Reference. 

9. U Pienaar 2060 Kruger fish data

**Comment by helendallas** [comment]
@aneriswanepoel Please can you check the paper to see if there are any more details about sampling date and or biotope, sampling effort etc. Thanks
https://koedoe.co.za/index.php/koedoe/article/view/761

**Comment by aneriswanepoel** [comment]
@helendallas no specific dates given. Survey conducted over ten years with various methods used - I have included this in the notes column.

**Comment by aneriswanepoel** [comment]
@helendallas error file successfully loaded onto testing site so ready for live site ingestion

**Comment by aneriswanepoel** [comment]
Uploaded to FBIS live

**Comment by helendallas** [comment]
@aneriswanepoel Please also check site localities, for e.g this one must be wrong

https://freshwaterbiodiversity.org/location-site-form/update/?id=65862

**Comment by aneriswanepoel** [comment]
@helendallas those would have been the co-ordinates given with the AWARD data. Since the study was done in 1960 I'm assuming the co-ordinates aren't 100% accurate so not sure what to do

![image](https://user-images.githubusercontent.com/55532903/126636782-72f8b883-59cd-41d4-ab1e-3b3bc9c56bb6.png)

**Comment by helendallas** [comment]
@aneriswanepoel Challengin, leave for now, but we will need to try and get better coordinates perhaps by liaising with Robin who know the area. thanks

**Comment by helendallas** [comment]
@aneriswanepoel No data so think a mkssing data issue, please check once Dimas has fixed.

**Comment by aneriswanepoel** [comment]
@helendallas all records restored
