### ISSUE TITLE
SAEON SASS data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#137]
SASS data received from SAEON has been entered by Kyle Middleton into FBIS. There are however some outstanding issues that need to be resolved. some sites and data are missing.

Mainstem sites  =4
![image](https://user-images.githubusercontent.com/45286876/125058877-fb4b2480-e0aa-11eb-8a5d-a60ef8cf259a.png)

Tributaries  =2 sites
![image](https://user-images.githubusercontent.com/45286876/125059061-38afb200-e0ab-11eb-8552-1d5c8794e79f.png)

@Kyle-Mark Please check. If you are unable to do this please let @aneriswanepoel know and she can add the data, once you have shared these with us.

**Comment by helendallas** [comment]
As per email from @Kyle-Mark the SASS data is all captured.
@aneriswanepoel Please can you run queries to check the data, thanks

**Comment by aneriswanepoel** [comment]
@helendallas I have gone through the SASS data that Kyle sent through, and it seems that there is still quite a bit missing from FBIS...there should be more than 8 sites (according to the spreadsheet there are 21 sites with SASS data)

![image](https://user-images.githubusercontent.com/55532903/127305566-ed7a3fea-5446-428c-b534-7632859d46d9.png)

For the sites that are on FBIS, there also seems to be data missing for a number of sampling dates.

Kyle is also still the owner of two sites:
![image](https://user-images.githubusercontent.com/55532903/127306126-0577ef12-7a59-4ece-aeb1-e317f56fa04c.png)

**Comment by aneriswanepoel** [comment]
@helendallas search results with Validated and Non-Validated selected:

![image](https://user-images.githubusercontent.com/55532903/127307834-c2ac4eef-e671-4439-bb3b-b4e11057a17c.png)

**Comment by aneriswanepoel** [comment]
@helendallas Okay SASS data comes up when specifying TD Mohlala as owner:

![image](https://user-images.githubusercontent.com/55532903/127308911-56d27a91-6f75-49ae-8951-52b29d26fba7.png)

Not sure why the data doesn't come up when searching for the study reference though..

**Comment by helendallas** [comment]
Thanks @aneriswanepoel 
Please can you email Kyle and follow up with him. I think perhaps he needs to send you the data so that we can figure out what is missing.

**Comment by aneriswanepoel** [comment]
@helendallas so it seems all the data is there (I've checked the spreadsheet that Kyle sent through) and the metadata is correct. So it has been entered correctly. However, if you search by Study Reference, FBIS only returns 8 sites where it should return 21 sites. But if you search by Owner as TD Mohlala, FBIS returns all 21 sites.

**Comment by helendallas** [comment]
@aneriswanepoel Oh dear, please can you email Dimas with links so he can check and revert. Thanks

**Comment by Kyle-Mark** [comment]
Hi Helen and Aneri

I also encountered that issue of it not finding the study references. It also couldn't find site codes when I searched for them but when I input the coordinates, it showed them.
As for the dates that are missing from the data, this came about when I checked everything to look for possible reasons for why the SASS scored would have differed between samples. Within the data, there is a column which I missed the first time round which says whether to remove or exclude from SASS. I also removed the sampling dates where there were comments saying for example that only stones were sampled, and not vegetation or GSM. Does that make sense?

**Comment by aneriswanepoel** [comment]
Thanks @Kyle-Mark 
I'm going to email Dimas and see if he can figure out why the Study References aren't linked to all 21 sites

**Comment by aneriswanepoel** [comment]
@Kyle-Mark out of interest, do you have any further info on why so many dates had to be excluded? Or why there is an Exclude for SASS column and what determined the True/False?

**Comment by helendallas** [comment]
Please confirm the Source Reference of these data and Owner.

**Comment by helendallas** [comment]
![Uploading image.png…]()
