### ISSUE TITLE
Riviersonderend Data Southern Waters - algal data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#138]
Please extract the relevant algal data from the report. Using site descriptions and species list.

First check if the data are already in FBIS, thanks

**Comment by Janette-Lumley** [comment]
@helendallas I have added the algal data and uploaded the spreadsheet to dropbox. Could you let me know the name of the report, I tried to search for it but couldn't find anything.

**Comment by helendallas** [comment]
@Janette-Lumley So so sorry, getting my wires crossed.......I uploaded the report of SASS data of Rob Palmer. This one still needs to be uploaded once Dimas fixes the functionality to do so.

**Comment by Janette-Lumley** [comment]
@helendallas I have now added the document upload link

**Comment by helendallas** [comment]
@helendallas To upload once source reference is sorted.

**Comment by helendallas** [comment]
@Janette-Lumley 

I checked and tested uploading on FBIS testing, but several taxa not in Taxon Master list. Please can you check these against the latest master list you and Kate are working with. Error file below.


[error_Ractliffe_Snaddon__Brown_1996_DMHc9Vm.csv](https://github.com/helendallas/FRC_FBIS/files/8079536/error_Ractliffe_Snaddon__Brown_1996_DMHc9Vm.csv)

Lets try again once the algal master list is uploaded again.

**Comment by Janette-Lumley** [comment]
@helendallas 

I have checked this against the latest algae master list, there are 4 that are not in there. I have added these in red in the 2nd tab.

**Comment by helendallas** [comment]
@KSnaddon I thought it would be good for you to verify algal names not in the master list that you finalised.

Here is the edited xls file. 

[Ractliffe, Snaddon & Brown 1996.xlsx](https://github.com/helendallas/FRC_FBIS/files/11234115/Ractliffe.Snaddon.Brown.1996.xlsx)

The source reference is on FBIS so you can download it from there.

**Comment by helendallas** [comment]
@Janette-Lumley Is this all completed and ready for checking.

Where is the final xls file?

**Comment by Janette-Lumley** [comment]
@helendallas yes this is ready. Here is the spreadsheet:
[Ractliffe, Snaddon & Brown 1996.xlsx](https://github.com/helendallas/FRC_FBIS/files/12258599/Ractliffe.Snaddon.Brown.1996.xlsx)
Also added to dropbox "Janette only" folder

**Comment by helendallas** [comment]
@KSnaddon I can't see these on the alga master list

Chaetophora
Chaetomorpha incrassata

I can't find them in master list.

So, I realised that the latest version, Chaetophora has been deleted. And the second one is only given as genus.

So I assuming this is fine now. Please confirm.

Thanks

**Comment by helendallas** [comment]
@KSnaddon Please write in the ticket what you have done so that I know where this ticket is at. Also if you have changed the dataset please upload it to the ticket.

**Comment by helendallas** [comment]
Testing upload in testing site. Some issues. Need to check

**Comment by helendallas** [comment]
Uploaded after Dimas fixed Site code issue. Closing ticket
