### ISSUE TITLE
Riviersonderend Data Southern Waters - Invertebrate data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#139]
Please extract the relevant invertebrate data from the report. Using site descriptions and species list

**Comment by Janette-Lumley** [comment]
@helendallas I have added the invert data and uploaded to dropbox. I will just need to add the document upload link once we can upload documents on FBIS again.

**Comment by helendallas** [comment]
@Janette-Lumley Thanks. The pdf is already on the system as I added it when I first edited the SASS data.

**Comment by helendallas** [comment]
@Janette-Lumley So so sorry, getting my wires crossed.......I uploaded the report of SASS data of Rob Palmer. This one still needs to be uploaded once Dimas fixes the functionality to do so.

**Comment by helendallas** [comment]
@Janette-Lumley Please add the pdf of the source reference to this ticket.

**Comment by helendallas** [comment]
@Janette-Lumley Please can we chat about how you decided on the FBIS Site Code

**Comment by helendallas** [comment]
@helendallas Just need to add Source Reference and  then it can be uploaded

**Comment by helendallas** [comment]
Data uploaded to FBIS, closing ticket
