### ISSUE TITLE
Invertebrate Data-  Brown CA 1997

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#14]
Data for two rivers, above and below trout farm. Emailed Cate Brown re electronic data. Awaiting response.

Table A8 in 
Tables 3.3 and 3.4

Brown   C.A. | 1997 | Modelling and   managing the effects of trout farms on Cape rivers. | PhD thesis.   Zoology Department. University of Cape Town, South Africa.

**Comment by helendallas** [comment]
Cate Brown is not providing any further details. 
@Janette-Lumley 
Please go ahead and capture data from tables.

**Comment by Janette-Lumley** [comment]
@helendallas please could you send me the co-ordinates for the sites that you have when you get a chance. Thanks

**Comment by helendallas** [comment]
@Janette-Lumley Here we go. The sites should match those of Cate's on the Kraalstroom. Please shout if they don't.

[Kraalstroom Sites Cate Brown.xlsx](https://github.com/helendallas/FRC_FBIS/files/4883718/Kraalstroom.Sites.Cate.Brown.xlsx)

Are you managing with the others? Perhaps send me the descriptions and I can check. if any already exist in the FBIS

**Comment by Janette-Lumley** [comment]
@helendallas Thank you. The descriptions are different to the ones in the thesis. I have copied them all below:

Upstream   of the Earthdam farm | Molenaars | 
At the effluent outlet | Molenaars
50 m downstream of the outlet | Molenaars
200 m downstream of the   outlet | Molenaars
500 m downstream of the   outlet | Molenaars
1000 m downstream of the   outlet | Molenaars  |  

Upstream of the Portapool farm | Kraalstroom
At the effluent outlet | Kraalstroom
50 m downstream of the outlet | Kraalstroom
200m downstream of the outlet | Kraalstroom
500 m downstream of the outlet | Kraalstroom
1000 m downstream of the   outlet | Kraalstroom

**Comment by helendallas** [comment]
@Janette-Lumley Dont woryy about slight differences in wording, it means the same thing.  I did the work with Cate.
So all Kraalstroom sites are as per mine in the excel file.

Upstream of the Portapool farm | Kraalstroom - **H1KRAA-ABOVE**
At the effluent outlet | Kraalstroom **H1KRAA-BELOW**
50 m downstream of the outlet | Kraalstroom **H1KRAA-BEL50**
200m downstream of the outlet | Kraalstroom **H1KRAA-BE250**
500 m downstream of the outlet | Kraalstroom **H1KRAA-BE500**
1000 m downstream of the outlet | Kraalstroom H**1KRAA-B1000**

I will have a quick look at Molenaars

**Comment by helendallas** [comment]
Here is a shot of the Earthdam farm on the Molenaars - I reckon it is easiest to Use Google Earth to pin point each site, and then create a new site for each on FBIS.
![image](https://user-images.githubusercontent.com/45286876/86766797-5509b080-c04b-11ea-8d64-102f0a08cc4b.png)

**Comment by Janette-Lumley** [comment]
@helendallas ok great thanks for all this.

**Comment by helendallas** [comment]
@Janette-Lumley I see this is in the FBIS V4 folder. Is it completed? Any issues?

**Comment by Janette-Lumley** [comment]
@helendallas yes I wasn't sure what folder to add it to in FBIS, but it is complete as per the tables in the thesis, there are a few issues though, I wanted to ask if you could have a look when you get a chance, all the taxa in red has comments that I made, I compared it to the master list and found some discrepancies. 
Please let me know what to change and if you see other errors. Thanks.

**Comment by helendallas** [comment]
@Janette-Lumley Ok I can look at it now. Let me know when you have closed it so we dont create a conflicted copy

**Comment by Janette-Lumley** [comment]
@helendallas I have closed it now, thanks.

**Comment by helendallas** [comment]
@Janette-Lumley Okay I have gone through it.. please see my comments next to yours. I also picked up 2 other issues, in green. Please can you correct and then let me know once done and I will have a final check.

The Master list is here:
https://www.dropbox.com/s/tskyv34cslgirp9/SA%20Invertebrate%20Master%20List%20FBISv3_11%20May%202020.xlsx?dl=0

**Comment by Janette-Lumley** [comment]
Thanks @helendallas I have made the corrections, could you check my comments next to yours in blue and let me know. Thanks

**Comment by helendallas** [comment]
@Janette-Lumley I will take it from here. Easier. Only the taxon is ingested so you dont need all the other higher taxonomy, What is NB is that the taxon rank matches that in the master list, and that the taxon exists in the master list.

I will finalise now thanks

**Comment by Janette-Lumley** [comment]
Thanks @helendallas

**Comment by helendallas** [comment]
@Janette-Lumley Sorry still  few things for your to tackle now that I have looked at the data. I have done the following:

- I have deleted taxon Typanidae - this does now exist and I cannot find out what Cate meant.

- I have added Broad Biotope to all as all riffles are Stones in current, and all Backwaters are Stones out of current

- Abundances are given as density  - Abundances (10m2) - so I have added two colums where Density (m2) is given and divided your abundance by 10, to convert.  I left your original so that you can back check from your data for potential duplicates - see below.. But we can delete your two columns once checked .

- The conductivity needs to be converted to mS/m - I have divided this by 10. see screenshot below.

![image](https://user-images.githubusercontent.com/45286876/87669161-c47b5080-c76d-11ea-906a-5377106d4651.png)


- I checked for duplicates by running a concotenate script - these are highlighted in red. Most I suspect are because you havent include the SpF, SpJ, SpJJ etc in the notes column. Once you add these most should hopefully disappear.   PLease revise notes and then send back to me.

These seem to Chironomidae - where you have added species codes, and Notonemouridae, you have added Aphanicerca sp. twice instead of Aphanicercella sp.  Also some Simuliidae. I am afraid it is going to be quite a job checking :(

Some also look like true duplicates - these should be deleted once you have checked.

Please shout if you are unclear

**Comment by Janette-Lumley** [comment]
@helendallas thanks, I will get started on the corrections and let you know

**Comment by Janette-Lumley** [comment]
@helendallas I have made the corrections now, there should be no more duplicates.
