### ISSUE TITLE
Checking RHP SASS data - hard copy vs FBIS

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#140]
Please work through raw SASS datasheets and check if the data are already captured on FBIS. 

If they are not, and there is enough information, please capture the data.

**Comment by helendallas** [comment]
@Janette-Lumley Please can you update this ticket with a narrative. Doesnt have to be to detailed.

What still needs to be done with this data? or is it all sorted?

**Comment by Janette-Lumley** [comment]
@helendallas I have checked all the data sheets and added the ones that weren't in FBIS. There were 3 SASS data sheets that were not entered because there were no site coordinates visible on the hard copies.

**Comment by helendallas** [comment]
@Janette-Lumley Great thanks, closing ticket then
