### ISSUE TITLE
10a. Mike Coke & KZN river fish data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#141]
All data listed as Data provided by Mike Coke of Natal Parks Board/EKZNWildlife have been extracted from Nepid Database.

@aneriswanepoel Please can you go through this data and remove all records where the Original River Name is not specified. This extracted data can then be labelled **Mike Coke & KZN wetland fish data** and will be uploaded at a later stage. Please create a new folder for wetland data.

Can you also please do a spot check of the earlier records to see if the data are being brought down from GBIF.

And spot check the records listed as SAIAB; to see if they are brought down by GBIF, if they are then I suggest we delete them.
Collector/Owner Institute = The South African Institute for Aquatic Biodiversity

**Comment by aneriswanepoel** [comment]
@helendallas data has been split. A lot of records without Original River Name are specified as dams/streams/reservoirs etc in the Site Description column, so these records have been kept in the original file. The rest (specified as wetlands/swamps/pans etc in the Site Description column) have been added to the **Mike Coke & KZN wetland fish data** file. This also includes any St Lucia records.

**Comment by helendallas** [comment]
@aneriswanepoel I suggest you extract records using the province = KZN filter. Then download the csv file and compare with datafile. Make sure GBIF is clicked on.

**Comment by aneriswanepoel** [comment]
@helendallas data checked against the KZN GBIF data from FBIS and duplicates between the two removed. Also checked for duplicates within the Mike Coke data and removed.

**Comment by helendallas** [comment]
Thanks @aneriswanepoel 

I am still a bit concerned that some of the data here is also being brought down by GBIF. The collector names are often old JLB Smith or SAIAB.  please can you ask @jeremyshelton to check through these as well. 

Also lets ask Dimas how we can check for duplicates during the upload process. I dont know how the duplicate functionality is working.

**Comment by helendallas** [comment]
@aneriswanepoel Thanks for clarifying. As chatted about, re-harvest data from GBIF and then run the duplicates check again. Then once any duplicates are removed these data can be uploaded.

It may also be worth checking if Mo received any data from KZN wildlife and checking for duplicates before uploading.

**Comment by aneriswanepoel** [comment]
@helendallas data re-checked for duplicates and 68 duplicates removed (as discussed yesterday). I think this data can be uploaded unless you want to check it again?

**Comment by helendallas** [comment]
@aneriswanepoel Happy for you to upload, thanks

**Comment by helendallas** [comment]
Uploaded and checked
