### ISSUE TITLE
14. Clean Stream Biological Services

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#146]
@aneriswanepoel I have extracted all fish data from Nepid database owned by Clean Stream Biological Services and created its own file. I have emailed Pieter Kotze re uploading data to FBIS.

14. Clean Stream fish database

**Comment by helendallas** [comment]
@aneriswanepoel Please check the data that Mo has from Clean Stream and combine with this file. Then all data become the Clean Stream Biological Services Database

**Comment by aneriswanepoel** [comment]
@helendallas okay data has been combined, checked for duplicates and river health codes added for some sites

**Comment by helendallas** [comment]
Uploaded and checked
