### ISSUE TITLE
15. AfriDev Consultants J Engelbrech

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#147]
@aneriswanepoel Fish data extracted from Nepid.

15. AfriDev Consultants J Engelbrecht

**Comment by aneriswanepoel** [comment]
@helendallas successfully loaded onto testing site but holding off on live site ingestion until Dimas has sorted out the existing site code issue

**Comment by helendallas** [comment]
Uploaded and checked
