### ISSUE TITLE
16. Ecosun

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#148]
@aneriswanepoel Extracted from Nepid dataset - 
16. Ecosun

**Comment by helendallas** [comment]
@aneriswanepoel 
Please check for any datasets from Ecosun or Rohanne Rall and then combine with this one and check for duplicates.
Ecosun Database

**Comment by aneriswanepoel** [comment]
@helendallas checked for duplicates, but I'm not aware of any other J Rall/Ecosun data

**Comment by helendallas** [comment]
Uploaded and checked
