### ISSUE TITLE
17. Mpumalanga Tourism and Parks Agency 

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#149]
@aneriswanepoel Data extracted from Nepid dataset

17. Mpumalanga Tourism and Parks Agency

**Comment by aneriswanepoel** [comment]
@helendallas there are some sites here that are already on FBIS as river health codes so I need to go through them and update this spreadsheet before uploading to FBIS

**Comment by helendallas** [comment]
@aneriswanepoel Please check these 13 sites as they are outside the geographic range of Mpumalanga Tourism and Parks Agency. Not usre how they were included here - must of been mislabeled in the original data from Nepid? Have a look and see if you can resolve. 

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22840%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=[[26.16943359375,-32.054644690549296],[26.411132812500004,-33.385586268871016],[29.311523437500004,-33.23868752757412],[33.24462890625,-28.71949610755746],[31.574707031250004,-27.984700118612665],[27.92724609375,-29.257648503615542],[26.16943359375,-32.054644690549296]]&thermalModule=&dst=

**Comment by aneriswanepoel** [comment]
@helendallas okay changed to "Nepid fish database" reference
