### ISSUE TITLE
Leon Barkhuizen fish data

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#150]
@mokajee has email Leon regarding sampling dates and waiting for response. Data will then be ready for ingestion.

**Comment by mokajee** [comment]
Leon replied. All data extracted. @aneriswanepoel to double check and upload.

**Comment by jeremyshelton** [comment]
Nice one - than @mokajee

**Comment by aneriswanepoel** [comment]
@jeremyshelton to save as CSV, then uploaded to testing before live site ingestion

**Comment by jeremyshelton** [comment]
@aneriswanepoel done ✅
