### ISSUE TITLE
Expert & Gauteng fish data

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#151]
@aneriswanepoel busy checking data for duplicates before ingestion.

**Comment by aneriswanepoel** [comment]
All duplicates removed

**Comment by aneriswanepoel** [comment]
Pieter Kotze, Golder & Warren Aken data removed, and added to their respective database spreadsheets created by Helen. This data is in the AWARD folder

@mokajee @jeremyshelton

**Comment by aneriswanepoel** [comment]
@jeremyshelton to save as CSV for uploading to testing before live site ingestion

A number of these records were already on FBIS so were removed from this spreadsheet.

@mokajee

**Comment by jeremyshelton** [comment]
@aneriswanepoel done ✅
