### ISSUE TITLE
Wynand Vlok Fish Data

### ISSUE THREAD

**Issue by mokajee** [helendallas/FRC_FBIS#153]
@mokajee to sort, clean and extract data.

**Comment by aneriswanepoel** [comment]
@mokajee can you please clarify which species this is meant to be?
![image](https://user-images.githubusercontent.com/55532903/128015523-99081cc1-dfd4-417f-af11-b08f9818e14f.png)

**Comment by aneriswanepoel** [comment]
@mokajee why is this highlighted in red? And what is the Source for the rest of the column?

![image](https://user-images.githubusercontent.com/55532903/128018023-e1c1985c-9b20-4b85-bfe3-9b196dd22ab8.png)

**Comment by aneriswanepoel** [comment]
@mokajee to address above queries
Will confirm when @jeremyshelton can save as CSV for uploading
A lot of duplicate data found and removed.

**Comment by mokajee** [comment]
> @mokajee can you please clarify which species this is meant to be?
> ![image](https://user-images.githubusercontent.com/55532903/128015523-99081cc1-dfd4-417f-af11-b08f9818e14f.png)

Fixed.

**Comment by mokajee** [comment]
> @mokajee why is this highlighted in red? And what is the Source for the rest of the column?
> 
> ![image](https://user-images.githubusercontent.com/55532903/128018023-e1c1985c-9b20-4b85-bfe3-9b196dd22ab8.png)

Its highlighted red because these data were listed to have come from the RHP monitoring programme. I wasnt sure if these data were already in FBIS, so marked them.

I am not sure what to put down for the source for the other data. Its not clear from Vlok's datasheets. Perhaps a quick chat with Jem in the morning to clarify.
