### ISSUE TITLE
18. Golder Consultants - Letaba, Olifants & Shingwedzi RRD

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#155]
@aneriswanepoel 
Mo received a lot of data from Warren Aken. The data in 18. Golder Consultants.xlsx includes some data from Warren as well as Golder consultant.  Please can you check the datasets and preferably combine into one, if the actual study are listed as different sources then also best to keep as is. Ideally it would be best to have the pdf of the report that goes with each source.

**Comment by aneriswanepoel** [comment]
@helendallas data has been combined into one spreadsheet. I am not sure where/how to get the PDFs for the two reports. The third batch of data (from Mo) is Unpublished data.

**Comment by aneriswanepoel** [comment]
Emailed Warren Aken re PDFs of reports

**Comment by helendallas** [comment]
Still no reply, so lets go ahead with uploading. We need to keep the three separate, I will create dummy docs for each for including in the upload file and put in a blank pdf in the meanwhile:

Olifants River Reserve Determination = document 399
Letaba River Reserve Determination = document 400
Shingwedzi River Reserve Determination = document 401

![image](https://user-images.githubusercontent.com/45286876/132479867-f052edca-c473-42a4-96c1-ccddd5f80629.png)

**Comment by aneriswanepoel** [comment]
Spreadsheet updated (biotopes and DULs added) and ready for FBIS upload

**Comment by helendallas** [comment]
@aneriswanepoel Thanks. Dimas has fixed the issue with source and dates, so I reckon you can upload the data now. I had a quick final check and created the csv - in dropbox folder

**Comment by helendallas** [comment]
@aneriswanepoel Please confirm when this has been uploaded and if you have any issues with creation of multiple datasets again

**Comment by aneriswanepoel** [comment]
@helendallas I am trying to upload but it keeps getting stuck on 197/283 records so trying to figure out why..

**Comment by helendallas** [comment]
Not sure? data looks okay?

**Comment by aneriswanepoel** [comment]
@helendallas I've sent Dimas a message on Slack so hopefully it's sorted now!

**Comment by helendallas** [comment]
@aneriswanepoel I see some sites are in the ocean. Can you check the sites for accuracy. That should be part of our job when we upload sites. If there is no description, then make a note and email Warren

**Comment by aneriswanepoel** [comment]
@helendallas oh dear! Will have a look and investigate

**Comment by helendallas** [comment]
I reckon as annoying as it is when we upload other peoples data we need to check the site locations afterwards to make sure they are as accurate as possible. That should be the final stage in the validation process. '
FYI for all. @aneriswanepoel @jeremyshelton @Janette-Lumley 

Otherwise we run the risk of sites in completely incorrect locations. If we cannot fix the data then I would recommend excluding it by deleting the site.

@jeremyshelton  thoughts?

Example here of data just added by Aneri:
![image](https://user-images.githubusercontent.com/45286876/132809616-b3dc3920-1453-479a-8761-2c2f8a34348f.png)

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221014%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

**Comment by aneriswanepoel** [comment]
@helendallas what happened is the co-ordinates got dragged down in the spreadsheet which messed with the longitudes:

![image](https://user-images.githubusercontent.com/55532903/132811300-99645d86-c76e-4802-bd77-0fa09e47be4d.png)

I can go into the sites and fix them

**Comment by helendallas** [comment]
thanks Aneri. Please just systematically work through all site locations for all data sets that you have uploaded for biosmart project. Its relatively easy if you select by the study reference and then click through the sites, they should be on the river names etc

**Comment by helendallas** [comment]
@aneriswanepoel 

Here is the url for the 3 studies combined:

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221013%22%2C%221014%22%2C%221015%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

Can you please double check all the data were added
![image](https://user-images.githubusercontent.com/45286876/187634432-f6dbcf15-3196-4779-a540-bcf9ed6fecf6.png)

**Comment by helendallas** [comment]
Can you also email Warren again for the pdf. These should be publicly available so maybe also look on google or email Jackie Jay, Barbara Weston or Christa Thirion from DWS.

**Comment by aneriswanepoel** [comment]
@helendallas in the spreadsheet the Owner is Warren Aken, not Golder Associates. I will see if I can find the PDFs

**Comment by aneriswanepoel** [comment]
@helendallas I still haven't been able to track down the PDFs

**Comment by helendallas** [comment]
Emailed DWS colleagues - 28 Sep 2022

**Comment by helendallas** [comment]
@Janette-Lumley Will update the source reference for this as we now have the correct pdf. She will also add photographs of each site as these are available in the pdf

@Janette-Lumley Please confirm when this is completed, thanks

**Comment by Janette-Lumley** [comment]
@helendallas I have updated the source reference and added the photos

**Comment by helendallas** [comment]
Thanks @Janette-Lumley
