### ISSUE TITLE
Adding back the data that Dimas deleted

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#156]
@aneriswanepoel it's now time to add back the corrected versions of that data deleted by Dimas months back.
It's the '15 June' spreadsheet on dropbox: https://www.dropbox.com/s/57xwgcakmkpc15p/FBIS%20Fish%20Data%20for%20upload%2015%20June.xlsx?dl=0

Before uploading we need to (1) make sure the data match the fish upload template precisely and (2) add FBIS site codes for the existing Snaddon et al. 2019 SASS sites on FBIS. 

Then we're good to go 🚀

**Comment by aneriswanepoel** [comment]
@jeremyshelton okay done and renamed to "23 July"

**Comment by jeremyshelton** [comment]
Thanks @aneriswanepoel 
I have created a .CSV
Keen to try upload to FBIS....or shall we wait to Dimas to fix site code issue?

I have invited you and @mokajee to the FBIS2 folder.
This is where the fish occurrence data live:

<img width="378" alt="Screen Shot 2021-07-23 at 11 50 33 AM" src="https://user-images.githubusercontent.com/44292029/126765892-561f5208-ee4b-4955-b809-c38bad834d83.png">

**Comment by aneriswanepoel** [comment]
@jeremyshelton I think we should wait until Dimas has fixed the codes issue

**Comment by jeremyshelton** [comment]
Agreed.
