### ISSUE TITLE
Update on data uploads - 23 July 2021

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#157]
1. Six fish datasets successfully uploaded onto Live site (found in Dropbox folder: Uploaded CSV). The issues were:
   - 7. Deacon FRAI data - existing FBIS codes not pulled through with ingestion; Dimas to fix
   - 5. IA Russell thesis data - existing FBIS codes not pulled through with ingestion; Dimas to fix
2. Remaining four datasets (found in Dropbox folder: Checked and ready CSV) to be uploaded onto Live site once Dimas has sorted out the issue re existing FBIS codes not being pulled through when data is uploaded, as these datasets all contain existing FBIS codes

@helendallas @jeremyshelton

**Comment by jeremyshelton** [comment]
Great work.
Thanks @aneriswanepoel
