### ISSUE TITLE
Palmer 2006 Elefantes EWR - Inverts V1.1

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#158]
@Janette-Lumley 
Please can you check the existing data for the two sites in the attached file for August 2005, and then add the new data for May 2006.
Biotope ratings and physico-chemical data need to be added.

Also also please add photographs for each site for each date

All files are in the SASS Data/Rob Palmer folder in our shared dropbox
[Comparison of FBIS and Robs data 2006.docx](https://github.com/helendallas/FRC_FBIS/files/6908527/Comparison.of.FBIS.and.Robs.data.2006.docx)

The url for the sites n FBIS is

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=[%22Rob%20Palmer%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

Two sites are in Mozambique
![image](https://user-images.githubusercontent.com/45286876/127676795-1ffee796-3f5a-43b8-8b82-47399d45f3ae.png)

![image](https://user-images.githubusercontent.com/45286876/127676933-cf12d0cd-fd3e-406a-b7f6-d277b3173990.png)

**Comment by Janette-Lumley** [comment]
@helendallas I have checked the data in FBIS and added the biotope ratings and water chemistry. 
I also added the new data for May 2006.

**Comment by helendallas** [comment]
@Janette-Lumley Thanks so much. Looks great, closing ticket.
