### ISSUE TITLE
Invertebrate Taxon Data - Ketley ZA 2009

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#16]
Create a new spreadsheet for this study.

Ketley   Z.A. | 2009 | Stream   invertebrates and water temperature: Evaluating thermal tolerances in the   Cape Floristic Region (South Africa) - implications of climate change. | MSc thesis.   Zoology Department. University of Cape Town, South Africa.

Only data from chapter 4 to be included.
Site information - Table 4.1  - Six sites, details = Site description
Method - kick net
Biotope sampled  -  Stones
Sampled every 2 months, August 2008, October 2008, Dec 2008, Feb 2009, May 2009 .

Invertebrate data in Appendix 2 - Community composition
The total number of individuals for each species collected from three replicates per site from Window Gorge Stream from the source to below.  

Appendix 3 - Water quality variables

**Comment by helendallas** [comment]
@Janette-Lumley 
Please correct Taxon name, if Genus and species is recorded then Taxon becomes Genus species; if Genus only, then Taxon become Genus, if Family, then family etc.

New file is:  Ketley, Z.A. 2009 New 2019_10_03.xlsx

**Comment by helendallas** [comment]
@Janette-Lumley I have found some issues with this data after doing some checks with the final version for ingestion. I have had to remove the data from the consolidated file so that it can be corrected

1. You have not captured details in the Notes column when several species were found so these come through as duplicates in the data, but they are not.

For example Chironomidae Species 1, Species 2, Species 3 etc.
Please can you go back to the data and add in the details of the species i the notes column.

2. not all species have been capture correctly.

For example: Dytiscidae, Site 1 Dec 2008, Nebrioporus and Hydropeplus were not captured, and taxon was given as Dytiscidae. I have corrected it for this site/date but not the others.

Please can you systematically work through the data and correct the spreadsheet. 

Files are here:
https://www.dropbox.com/sh/3lrrqeup1sqaxni/AADaXjW9Ujg3G7w5T6g4RMraa?dl=0

Ketley, Z.A. 2009_For revision 2020_04_16.xlsx
Ketley Z.A. 2009 Inverts from Thesis.pdf

Please ask if unclear

**Comment by helendallas** [comment]
@Janette-Lumley Are you managing to tackle this? Any questions?

**Comment by Janette-Lumley** [comment]
@helendallas yes thanks, I am busy going through it systematically. I have also picked up a copy and paste issue, for example:
Chironomidae was pasted over as ChIronomidae (with a capital I instead of i), so must double check those. I will let you know if I have any questions. Thanks
--

**Comment by Janette-Lumley** [comment]
@helendallas I need to add in some missing data for February too, will this cause problems with the UUID?

**Comment by helendallas** [comment]
I have deleted the entire dataset from the data going into FBIS. It will go in in the new round. So please check carefully and add all missing data. we create new UUIDs once all data are conslidated

**Comment by Janette-Lumley** [comment]
@helendallas would you prefer for me to add the number of taxa instead of the percentage abundance? I remember you saying that with the percentage you lose out on important data numbers. For example in December - Site 1 there were 1810 Dytiscidae recorded.

**Comment by helendallas** [comment]
@Janette-Lumley She did not sample quantitatively, so percentage abundance is probably better. You calculated these previously right? Does this mean you will need to redo?

If so then just use numbers as given in the thesis.  This data will only go into FBIS in the next round.

**Comment by Janette-Lumley** [comment]
@helendallas I didn't need to recalculate the percentage abundance, I just double-checked them and then you will see 3 rows in the spreadsheet (highlighted) that are recorded as a number: 1, this is because as a percentage it comes out as 0. Should I delete those rather?

**Comment by helendallas** [comment]
@Janette-Lumley I reckon just include as 0.01%

**Comment by helendallas** [comment]
@Janette-Lumley PLease confirm this is completed and in the folder:
Final for FBISv4 folder

**Comment by Janette-Lumley** [comment]
@helendallas Yes that is the completed one.
