### ISSUE TITLE
Dallas et al 1998 Berg River Skuifraam Dam study - chapter 7

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#160]
Please can you consolidate data from Appendix 7.1 into a spreadsheet. Add notes for species A etc into notes column.

pdf, word doc and appendix in dropbox:

**Data for Consolidation/Invertebrate data/Original data received/Dallas et al 1998**

Please first generate the spreadsheet of taxa and then let me check . 

**Sites equal to these in FBIS.**

- Site C1 = G1BERG-BRBM1
- Site D2 = G1BERG-DEWDA
- Site D2  =G1BERG-SKUIF

Sampling dates in Table 7.1 

Thanks

**Comment by helendallas** [comment]
@Janette-Lumley Revised folders - created separate folder for this data - Dallas et al 1998 Berg River

**Comment by Janette-Lumley** [comment]
@helendallas just checking if this data should be entered for all the appendices (7.1 to 7.4) or 7.1 only?

**Comment by helendallas** [comment]
@Janette-Lumley All tables as each one is a separate season, using the dates provided, Thanks

**Comment by Janette-Lumley** [comment]
@helendallas I have entered the data and uploaded it to dropbox. I need to add the document upload link, I can't get it from FBIS because whenever I try I get a failed error.

**Comment by Janette-Lumley** [comment]
@helendallas I have now added the document upload link.

**Comment by helendallas** [comment]
@Janette-Lumley I picked up an issue with replicates in the riffle biotope. as discussed. So I have generated averages for each taxon.

Files is on dropbox: 
Dallas, Day, Musibono & Day 1998 Averages.xlsx

Please capture these averages into the original upload file

Please can you also add in notes - **Averaged from five replicate samples**

**Comment by helendallas** [comment]
@Janette-Lumley Can you also check if there are water quality data for each Site/date combination and add.

**Comment by Janette-Lumley** [comment]
@helendallas I have updated the spreadsheet with the averages. 
The only water quality data I can see is in graph format. Do you have the data in another format?

**Comment by helendallas** [comment]
Thanks @Janette-Lumley . Lets leave out the wq data as I don't have the raw data any more.  I will upload once I can check the doc number

**Comment by helendallas** [comment]
Data uploaded but there are some errors. Dimas needs to check why some taxa are not being uploaded
Error file in csv folder

Sites not visible on the map, Helen to check

**Comment by helendallas** [comment]
All data successfully uploaded to FBIS, but not showing when I select the study reference as a filter or in source references
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22862%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

@dimas to check

**Comment by helendallas** [comment]
Data are uploaded but not visible. I have created a ticket on FBIS V2, so will close this ticket now
