### ISSUE TITLE
Check citations in FBIS for Biobase references

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#162]
Please can you systematically work through the the **Source References** in FBIS, select **Published Report or thesis**; checking that all references in the Biobase report are included and are correct.

![image](https://user-images.githubusercontent.com/45286876/128315022-3786b20d-bca0-4b7c-9f10-439b3fc69176.png)

Please note which are missing, so we can try and find and add.

These are in the dropbox folder: 
FRC_FBIS Data for Consolidation/Data for Consolidation/Invertebrate Data/Biobase

[References from Dallas et al 2011 Biobase KV 262-10.pdf](https://github.com/helendallas/FRC_FBIS/files/6937020/References.from.Dallas.et.al.2011.Biobase.KV.262-10.pdf)

**Comment by Janette-Lumley** [comment]
@helendallas I have checked all the source references in the biobase and they all exist in FBIS and are correct.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley  Closing ticket
