### ISSUE TITLE
Dallas et al 1998 Breede River Chapter 4 - checking SASS and associated data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#163]
Once the site information has been added, see ticket #161 

Url for sites:
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=[%22Helen%20Dallas%22]&category=&yearFrom=1995&yearTo=1995&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=[%22value,primary_catchment_area,Region%20H%22]&reference=&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

Please can you do the following for each SASS assessment as per the data specified in the file - all Oct or Nov 1995

- Add photographs  - Helen still to find and provide
- check taxa are correct from datasheets- some taxa different, for e.g. Zygoptera juvs. not included anymore so leave. Ephemerellidae = Teloganodidae; Also there was a group TRICHOPTERA (CASE CADDIS 1 TYPES) ; 2 or 3.
- Add Water surface width from form
- Add Embeddedness from form
- Check Temperature, Conductivity, pH, Dissolved Oxygen, Turbidity NTU values - NB first check using SASS Dashboard, as sometimes data are there, but don't come up on the form
- Change Source Reference from Rivers Database to Published report Helen Dallas, Day JA, Musibono DE. & Day EG.  1998.  Water quality for aquatic ecosystems: tools for evaluating regional guidelines.  Water Research Commission Report No. 626/1/98.

**Comment by helendallas** [comment]
Site codes etc in dropbox folder: 
Breede river sites extracted from FBIS 2021_08_05.xlsx

All files and chapters in folder: Dallas et al 1998 Breede River

**Comment by Janette-Lumley** [comment]
@helendallas I have done the following:

- check taxa are correct from datasheets- some taxa different, for e.g. Zygoptera juvs. not included anymore so leave. Ephemerellidae = Teloganodidae; Also there was a group TRICHOPTERA (CASE CADDIS 1 TYPES) ; 2 or 3.
- Add Water surface width from form
- Add Embeddedness from form
- Check Temperature, Conductivity, pH, Dissolved Oxygen, Turbidity NTU values - NB first check using SASS Dashboard, as sometimes data are there, but don't come up on the form
- Change Source Reference from Rivers Database to Published report Helen Dallas, Day JA, Musibono DE. & Day EG. 1998. Water quality for aquatic ecosystems: tools for evaluating regional guidelines. Water Research Commission Report No. 626/1/98.

I just need to add the photos when you send them through. 
There is also a word doc with a lot of other water quality data, do I add that as well?

**Comment by Janette-Lumley** [comment]
@helendallas the water quality csv in FBIS is not pulling through for the sites with a single SASS entry (1995) the first one is correct for H4HOUT-DEHOE but then every other site the water data stays the same as H4HOUT-DEHOE.
The csv for sites with multiple SASS data on different dates pulls through correctly.

**Comment by Janette-Lumley** [comment]
@helendallas the csv is correct now and pulling through the correct data

**Comment by helendallas** [comment]
Thanks @Janette-Lumley closing ticket as I cant find the photos at the moment
