### ISSUE TITLE
Golder Associates Africa (Pty) Ltd. SASS data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#169]
Please can you capture the SASS data in folder:

File of sites is on dropbox:
Data for Consolidation/SASS data/Golder Associates Africa (Pty) Ltd/xxxxx
Please navigate to the Site and then Add SASS data. First check that the data are not yet in FBIS.

SASS data are in files named 

- Aquatic Macroinvertebrates_Let.xlsx, 
- Aquatic Macroinvertebrates_Oli.xlsx, 
- Aquatic Macroinvertebrates_Shi.xlsx

Awaiting feedback from Warren Aken re report pdf , biotopes etc.

**Comment by helendallas** [comment]
**Email sent to Warren:**
We are finally getting round to uploading the SASS data you shared with us. I noticed the data are at site level and not biotope level. Do you have the biotope level data? As well as biotope ratings and associated physico-chemical data?

Also what does OBS mean?

Are these data associated with specific reports? And if so are pdfs available?

**Response from Warren:**
The short answer, is yes, yes and yes.
These studies were conducted as part of the Olifants Reserve Determination, so I do have the detailed SASS5 data, IHAS and WQ data. I must just find it. 
As it was gazetted, I’m sure I can also send you the final reports.

**Comment by helendallas** [comment]
The OBS is for visual assessment, and need to be added to the relevant biotope. Record as "1'"

**Comment by helendallas** [comment]
@aneriswanepoel Once the fish data from warren has been fixed and uploaded to FBIS, then you need to run an exract of csv to get the same FBIS Site Codes, which can be used to then add the SASS data.

I am waiting on Warren to send use the SASS data per biotope and associated abiotic data. Once this is received then it can be uploaded to FBIS.

**Comment by aneriswanepoel** [comment]
@helendallas have you heard from Warren again re this data?

**Comment by helendallas** [comment]
@aneriswanepoel Please follow up again with Warren re the SASS data, thanks

**Comment by aneriswanepoel** [comment]
@helendallas still no reply from Warren
