### ISSUE TITLE
Validate SASS data for Thabo Mohlala

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#172]
@aneriswanepoel Please can you go through the unvalidated list, double check sites location and SASS data entry, the click Tick, to validate.  

![image](https://user-images.githubusercontent.com/45286876/131117164-437b6cf1-73ac-48cc-9c2a-d9e8ce62fc57.png)

Here is the link:

https://freshwaterbiodiversity.org/site-visit/list/?validated=%5B%22non+validated%22%5D&o=date&page=&collectors=%5B1249%5D&modules=21

![image](https://user-images.githubusercontent.com/45286876/131116895-57bfba32-9ca3-4c2f-8592-3be8dc8577ac.png)

**Comment by aneriswanepoel** [comment]
Complete
