### ISSUE TITLE
Validate SASS data for Hendrik Sithole

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#173]
@aneriswanepoel After capturing the SASS data, please can you go through the unvalidated list, and validate by clicking the Tick button  
![image](https://user-images.githubusercontent.com/45286876/131117164-437b6cf1-73ac-48cc-9c2a-d9e8ce62fc57.png)

Here is the link:

https://freshwaterbiodiversity.org/site-visit/list/?validated=%5B%22non+validated%22%5D&o=date&page=&collectors=%5B1051%5D&modules=21

![image](https://user-images.githubusercontent.com/45286876/131117085-857c0bba-65af-487f-89aa-0b2a25a96f07.png)

**Comment by aneriswanepoel** [comment]
Complete
