### ISSUE TITLE
Validate SASS data for Kate Snaddon

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#174]
@Janette-Lumley  Given that either you or Aneri added this data, I don't need to validate it, 

Please can you go through the unvalidated list, and click Tick, to validate.

![image](https://user-images.githubusercontent.com/45286876/131117164-437b6cf1-73ac-48cc-9c2a-d9e8ce62fc57.png)

Here is the link:

https://freshwaterbiodiversity.org/site-visit/list/?validated=[%22non%20validated%22]&o=date&collectors=%5B1287%5D#

![image](https://user-images.githubusercontent.com/45286876/131118408-93046525-11af-4e51-8460-34e18e4efdf1.png)

**Comment by helendallas** [comment]
Please shout if unsure?

**Comment by Janette-Lumley** [comment]
@helendallas I have validated all the records above

**Comment by helendallas** [comment]
@Janette-Lumley Thanks, closing ticket
