### ISSUE TITLE
Check and add Owner to Rivers Database SiteVisits when missing

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#179]
Please can you go through the 

In dropbox: FRC_FBIS Data for Consolidation/SASS Data checking FBIS/**Original Rivers Database from Christa Thirion with Owners 1Jul17.xlsx**

I have downloaded all SASS data assigned reference =  database, so this should be all Rivers Database data that was migrated into FBIS. File generated and in dropbox: 
**Rivers Dbase data extracted from FBIS 2021_09_03.xlsx**

You need to filter for sites that don't have a Owner in **Rivers Dbase data extracted from FBIS 2021_09_03.xlsx**
- then check on the Original Rivers Database from Christa Thirion with Owners 1Jul17 file, who the Owner should be, and then go to site on FBIS, select SASS assessment, edit, and then add owner from dropdown list, then submit. You dont need to go beyond the first submit. Then close. The owner should now be added.

Let's go through some together to check you are comfortable.

**Comment by helendallas** [comment]
@Janette-Lumley Can you update me on this one please. I cant remember.

**Comment by Janette-Lumley** [comment]
@helendallas I filtered for blank owners and then updated the SASS on FBIS to include the correct owner. Most of them were Umgeni Water that wasn't originally on FBIS.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley CLosing ticket
