### ISSUE TITLE
Fish data missing metadata

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#180]
@aneriswanepoel Please can you check what the correct details are for these unpublished fish data

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22870%22]&endemic=&conservationStatus=[]&modules=1&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

They only have a date, nothing else. We need the name of a person or organisation or study, thanks
![image](https://user-images.githubusercontent.com/45286876/132312972-25fc9ed4-0c26-4997-90e4-c3bb3cbd45c1.png)

**Comment by helendallas** [comment]
Actually there are a whole lot of dates
![image](https://user-images.githubusercontent.com/45286876/132313231-42bf7440-7dfc-4df3-9e25-2d04b6d08c50.png)

**Comment by aneriswanepoel** [comment]
@helendallas oh dear okay will investigate

**Comment by aneriswanepoel** [comment]
@helendallas can you explain how you got to all those dates so I can look at that same page of Source-less data?

**Comment by helendallas** [comment]
@aneriswanepoel 
Go to Administration, Source Reference, click Unpublished and apply

here is link:
https://freshwaterbiodiversity.org/source-references/?type=unpublished&collectors=&page=2

Then if you click on the Records, you can see the sites and data for each. If this is all the same source, then we need to combine into one that is correctly named.

**Comment by aneriswanepoel** [comment]
@helendallas great thanks. I have managed to download the CSV for all the Source-less data and oddly enough the collector names are specified so not sure why FBIS didn't pull them through.

**Comment by aneriswanepoel** [comment]
@helendallas I have added the Collector names, but not sure how to combine as one Source? Do I just make it "Mick Angliss Unpublished Data" and leave out the years so that it combines as one?

![image](https://user-images.githubusercontent.com/55532903/132326469-d10443c0-edfd-44a4-a47c-fbdfe45af0cf.png)

**Comment by helendallas** [comment]
Tahnks, I combined into one Paul Fouche Unpublished Data, and Mick Angliss Unpublished data. If we dont combine we will end up with so many separate datasets
