### ISSUE TITLE
Source reference unpublished data needs fixing

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#181]
@aneriswanepoel Please also check these: we need more details: who. what organisation. 

One is able to combine if they are the same person or organisation, just click update and make sure the title is correct and then copy the same title for all datasets that are the same. Then the data get combined into one file. I can show you if unclear.

![image](https://user-images.githubusercontent.com/45286876/132314631-b0f81349-c02c-40f8-90ad-8831e239c726.png)

**Comment by aneriswanepoel** [comment]
@helendallas I have done this for all three (data belongs to Leon Barkhuizen) and this is the result:

![image](https://user-images.githubusercontent.com/55532903/132328946-010a0839-1683-43e8-92b6-94c46163efdc.png)

**Comment by helendallas** [comment]
@aneriswanepoel Okay I will sort remainder. Just need to delete one with no records,a

**Comment by aneriswanepoel** [comment]
@helendallas 
I've also had a look at this reference:
![image](https://user-images.githubusercontent.com/55532903/132329866-25caa445-558b-4da9-b1c3-f63cfa41b4c1.png)

Again there are actually various Collector names specified in the CSV but FBIS did not pull them through. So this one may be tricky to Edit/Update because there are a whole lot of different names

**Comment by helendallas** [comment]
That might of been consolidated. Can you attach the xls file to the ticket so I can  check, thanks

**Comment by aneriswanepoel** [comment]
@helendallas 
[Unpublished data.xlsx](https://github.com/helendallas/FRC_FBIS/files/7120856/Unpublished.data.xlsx)

**Comment by helendallas** [comment]
@aneriswanepoel Thanks. Okay so what we need to do is to open each site - Site visit and change the source reference. However at the moment we cant add new Unpublished datasets. I have asked Dimas to add this functionality in ticket #2761.

When he has done this can you please go though the data and correct to make the source reference separate for each user/organisation, so for e,g.

 **Unpublished data, Gerhard Diedericks** (also Gerhard)
 **Unpublished data,  Michiel Jonker - Ecotone Freshwater Consultants** (also Michiel) - He is also Ecotone Freshwater Consultants
 etc.

There might be some queries, so shout if you come unstuck.

**Comment by aneriswanepoel** [comment]
@helendallas okay thanks will do

**Comment by helendallas** [comment]
@aneriswanepoel Please dont forget to tackle this. thanks

**Comment by aneriswanepoel** [comment]
@helendallas I am able to add new Unpublished Datasets but for some reason it is not being retained in the dropdown list... I added "Gerhard Diedericks Unpublished Data" but it is not there in the dropdowns so I have to keep adding each time?

![image](https://user-images.githubusercontent.com/55532903/139427200-52b4fd07-ff47-4ea9-8b59-3d4ca65f7e2a.png)

**Comment by aneriswanepoel** [comment]
@helendallas this is complete now. There are 8 remaining records that I am battling with. For some reason they have 0 Site Visits so I can't locate them in the site visit page to change the metadata

![image](https://user-images.githubusercontent.com/55532903/140304468-2672574b-2d28-482e-a816-39e22dd46c09.png)

**Comment by helendallas** [comment]
@aneriswanepoel There are sites and data when I go to records

![image](https://user-images.githubusercontent.com/45286876/140308475-507f1f82-f02a-4ab1-a68d-b31475c52a69.png)

![image](https://user-images.githubusercontent.com/45286876/140308377-3c711502-43f4-4336-96fd-7752182c3801.png)

have you tried downloading the csv and checking?

mostly fish, two invert taxa? not sure how to find the original data?

**Comment by aneriswanepoel** [comment]
@helendallas yes I've downloaded the CSV files but for some reason those sites and data don't show up when I search for them in Site Visits... for example when I search B2KLIP-00011, I get 2 site visits but from different dates to what is in the CSV and from data that is actually referenced as Database, not Unpublished. Out of the 4 sites in your screenshot above, the first three say "0 visits" so I'm thinking that might be the issue but not sure how to solve the problem..

**Comment by helendallas** [comment]
@aneriswanepoel  So none of these sites have site visits (sampling dates), although they have data


![image](https://user-images.githubusercontent.com/45286876/141420211-d245607f-9828-4a8a-a51b-c6fa4b5b7385.png)


B2KLIP-00011 Michiel Jonker
https://freshwaterbiodiversity.org/admin/bims/locationsite/27232/change/?_changelist_filters=q%3DB2KLIP-00011

B2UNSP-DWAAL Rob Palmer
https://freshwaterbiodiversity.org/admin/bims/locationsite/11111/change/?_changelist_filters=q%3DB2UNSP-DWAAL

C9KLEI-00002 OdonataMap
https://freshwaterbiodiversity.org/admin/bims/locationsite/48445/change/?_changelist_filters=q%3DC9KLEI-00002

I have created a ticket for Dimas to check

**Comment by helendallas** [comment]
Closing ticket as resolved on site
