### ISSUE TITLE
Please check Source References - Published report or thesis

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#182]
Please systematically go through each Source reference and make sure the Title, Source, Year, Authors are all correct and that the doc/thesis has the correct link and or pdf.

![image](https://user-images.githubusercontent.com/45286876/132336025-04b22fd7-81a7-4cc0-bde3-00c9d93d2185.png)

Please note any duplicates, or other problem children

**Comment by Janette-Lumley** [comment]
@helendallas I have checked all the Published reports and Thesis. I have made notes of the duplicates and problem ones.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley Please can we chat about correcting these.

**Comment by Janette-Lumley** [comment]
[Report or Thesis errors.xlsx](https://github.com/helendallas/FRC_FBIS/files/7310941/Report.or.Thesis.errors.xlsx)

@helendallas I this is the list of errors.

**Comment by helendallas** [comment]
Thanks, please can you add author column and then try and figure out why the url is not working. You can edit it by clicking update.

Basically please play detective to get each of the links working properly. If you cannot find a working url then upload a pdf, for e.g. the wrc report.

All of these should be available online, so just dig around. Please make a not of what you do in the excel file.

thanks

**Comment by helendallas** [comment]
Any progress on this @Janette-Lumley

**Comment by Janette-Lumley** [comment]
@helendallas I have added the author column and I corrected the urls that were not correct. I made a note of what was done.

**Comment by Janette-Lumley** [comment]
[Report.or.Thesis.errors (2).xlsx](https://github.com/helendallas/FRC_FBIS/files/7762679/Report.or.Thesis.errors.2.xlsx)

**Comment by helendallas** [comment]
Checked and updated. Awaiting Dimas to fix issue with duplicate references. New file here:
[Report.or.Thesis.errors.2.xlsx](https://github.com/helendallas/FRC_FBIS/files/8079347/Report.or.Thesis.errors.2.xlsx)

**Comment by helendallas** [comment]
All checked and fixed. closing ticket
