### ISSUE TITLE
Please check Source References - Peer-reviewed scientific article

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#183]
Please go though all Peer-reviewed scientific articles and check they are correct - most of these are harvested automatically 

![image](https://user-images.githubusercontent.com/45286876/132336398-52695689-b2b5-4b53-9708-3db07152fb07.png)

Please also make a note of any thesis that have been misclassified as Peer-reviewed scientific article

**Comment by Janette-Lumley** [comment]
@helendallas I have gone through all the Peer-reviewed scientific articles and have made a note of the links that arent working and other issues.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley Please can we chat about fixing these

**Comment by Janette-Lumley** [comment]
[Scientific Article Errors.xlsx](https://github.com/helendallas/FRC_FBIS/files/7310946/Scientific.Article.Errors.xlsx)

@helendallas this is the list of errors for the Scientific articles.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley I have gone through these and fixed some. I will fix remainder once Dimas has added a bug fix.

**Comment by helendallas** [comment]
Checked all but one still problematic, try to reassign source references once updated
Pienaar U 
![image](https://user-images.githubusercontent.com/45286876/145197995-bdf0fd74-6007-4d71-9161-f91fc5b76d73.png)

**Comment by helendallas** [comment]
Fixed, closing ticket
