### ISSUE TITLE
Ian Russel Bontebok National Park - fish data missing in FBIS

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#184]
Ian Russel Bontebok National Park -  I assume it is fish.
(I deleted a source reference that had no data in it.)

Please can you check sometime in the old excel files, if and when these data were uploaded as they are no longer in the FBIS.

**Comment by aneriswanepoel** [comment]
@helendallas I've had a look at the old spreadsheets and can't find this data - but it was extracted originally sometime in 2019 (we kept a record of metadata that was extracted). I've had a look at the PDF and there are no co-ordinates given so my guess is that I extracted the data based on estimations of the co-ordinates but we obviously later decided not to include data that didn't have exact co-ordinates.

**Comment by helendallas** [comment]
ok thanks @aneriswanepoel I will close this ticket
