### ISSUE TITLE
19. Golder Associates - other

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#185]
Other data from Warren Aken - awaiting response to email regarding correct citation and PDF availability

**Comment by aneriswanepoel** [comment]
@helendallas Report PDF for Kuka Ropeway data received but Warren has said he is not sure where the 2008 biomonitoring data is from so I have called it "Golder Associates Unpublished Biomonitoring Report" as Unpublished Data

**Comment by aneriswanepoel** [comment]
@helendallas this dataset is also ready to be uploaded

**Comment by helendallas** [comment]
@aneriswanepoel I edited source to match company name already on FBIS. Should be good to go.

Again please check site locations in FBIS as the final step.

**Comment by helendallas** [comment]
@aneriswanepoel There is no source reference for this

![image](https://user-images.githubusercontent.com/45286876/187638768-6696ad90-3def-4c49-9d15-8132989952c1.png)

here is the url for all
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22226%22%2C%22268%22%2C%221016%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

and the url for missing one 
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=["226"]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=["fbis","gbif","virtual_museum"]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

There is not data, please can you check

**Comment by aneriswanepoel** [comment]
@helendallas seems to be another missing records issue
![image](https://user-images.githubusercontent.com/55532903/187667534-ed2fc873-bc5d-4af5-8e0a-d9cf2f669f42.png)

**Comment by helendallas** [comment]
@Janette-Lumley Please canyou add SASS data to these sites using Appendix C. Ignore OBS. And also add photos for each site visit (sampling date please)

**Comment by Janette-Lumley** [comment]
@helendallas I have added the SASS data and the photos for each site.

**Comment by helendallas** [comment]
Please check photos, there are two for B2KLIP-00001

**Comment by helendallas** [comment]
@Janette-Lumley PLease can you check the photos and revert so that I can close this ticket, thanks

**Comment by Janette-Lumley** [comment]
@helendallas I deleted one of the photos. You can go ahead and close the ticket. Thanks.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley
