### ISSUE TITLE
Please update owner

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#188]
Please update the owner of the SASS and fish data from Lydeah Masomera to Dale Kindler. He is SASS accredited so please tick for all SASS assessments. 

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=[%22Lydeah%20Masomera%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=

Also please allocate all data that is currently:
![image](https://user-images.githubusercontent.com/45286876/133241455-825e142e-d743-4b5b-ae56-2dd88e472966.png)

To the following:
![image](https://user-images.githubusercontent.com/45286876/133241678-b55d2d9a-f17d-4826-be12-e4b839d13a5a.png)

**Comment by Janette-Lumley** [comment]
@helendallas the owner has been changed to Dale Kindler and unpublished data changed to the database requested

**Comment by helendallas** [comment]
Thanks @Janette-Lumley
