### ISSUE TITLE
20. Muller, Strydom & Weyl 2015

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#189]
Fish data to be uploaded to FBIS

**Comment by helendallas** [comment]
This is outside the Kruger rivers region. Suggest you shift to FBIS project rather @aneriswanepoel

**Comment by helendallas** [comment]
@aneriswanepoel Checking that this is now not included in the list of source references captured for BioSmart

**Comment by aneriswanepoel** [comment]
@helendallas correct, it's been excluded

**Comment by helendallas** [comment]
Checked, all fine, closing ticket
