### ISSUE TITLE
SASS Data - Chantel Petersen

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#19]
@toniolsen 
Please can you check add the data from Chantel  into FBIS. I did a spot check and it definately not all there.

Also the correct Reference Source can now be added, which is her PHD. I have added it to her SASS folder.

Can you also try and get the biotope ratings - from thesis, or contact her.
Also all sites need a Site Description.

I have transformed the data -attached. May even be easier to get it from the original tables

Please take the necessary time to see it is done correctly, thanks

[SASS Data FCG and C Petersen_transformed to enter.xlsx](https://github.com/helendallas/FRC_FBIS/files/3636401/SASS.Data.FCG.and.C.Petersen_transformed.to.enter.xlsx)
 Chantel sent.

**Comment by toniolsen** [comment]
@helendallas I entered Chantel's data into our bulk upload template (attached), with Justine's data last year.
@Janette-Lumley is capturing this data. I just need to get the biotope ratings from Chantel, I have emailed her.
[CFR Invertebrate SASS Data Bulk Import Template.xlsx](https://github.com/helendallas/FRC_FBIS/files/3646103/CFR.Invertebrate.SASS.Data.Bulk.Import.Template.xlsx)

**Comment by toniolsen** [comment]
Chantel' response:

_Hi Toni

I don't think I have that in a digital format. Would you need it for each sampling event? That would take some time and I would need to get it from the raw data. Unfortunately I am a bit swamped at this week and then out of the office for two weeks. Let me know so that I can find some time to get it for you.

Chantel_

Perhaps we can still capture the data into FBIS and then add the biotope ratings at a later stage once Chantel has had the time to get them from her raw data?

@helendallas @Janette-Lumley

**Comment by helendallas** [comment]
@toniolsen @Janette-Lumley 
I suggest we enter the data on FBIS, and leave the biotope ratings blank for now.  The spreadsheet I attached was the bulk upload sheet - just transposed to make data capture easier. 

https://github.com/helendallas/FRC_FBIS/files/3636401/SASS.Data.FCG.and.C.Petersen_transformed.to.enter.xlsx

@Janette-Lumley Please indicate status of this please

**Comment by Janette-Lumley** [comment]
@helendallas I will be ready to start capturing this data today.

**Comment by helendallas** [comment]
@Janette-Lumley 
Great, Please use Transformed sheet. or original if easier for you. For each Site there is data for each taxon as follows:

PORIFERA_S - this is the stones
PORIFERA_V - this is the vegetation
PORIFERA_G - this is the GSM
PORIFERA_T - this is the Site - need to check and revise abundances


so please check if the FCG data is in. Check Organisation row.

Then enter CSIR data. for each Site, please add all necessary data including Site decription. Read PhD for details and sampling site details .  Owner should be Chantel Petersen, Reference Source, her PhD.
Geomorphic Zone = our refined Geomorphological Zone. Only enter if different from Geomorphological zone.

https://www.dropbox.com/sh/impkprhzc2ncd9d/AADCj60IlO_VCrItB18zfk-la?dl=0

**Comment by toniolsen** [comment]
@Janette-Lumley 
Here are the biotope ratings for Chantel's data:
[Sass_biotopes.xlsx](https://github.com/helendallas/FRC_FBIS/files/3676309/Sass_biotopes.xlsx)

@helendallas

**Comment by Janette-Lumley** [comment]
@helendallas I have re-entered all the SASS data according to the new spreadsheet you sent. I have also filled in the biotope ratings.

**Comment by helendallas** [comment]
@Janette-Lumley 

Please add Original Site Code for all sites, and Original River Name.
Please add physio-chemical data
[WQ_Wilderness_data.xlsx](https://github.com/helendallas/FRC_FBIS/files/4090320/WQ_Wilderness_data.xlsx)

Check with me if unsure of wq names

**Comment by helendallas** [comment]
![image](https://user-images.githubusercontent.com/45286876/72795115-c1cbf280-3c45-11ea-852d-6b74860a722a.png)

@Janette-Lumley 
Alos need to revise the site location so that it lies on the river. This is not easy to do at the moment, I have created a ticket for Kartoza (Rivers visible on Update a location site #1866)

Always check georeference against map in paper/thesis and shift onto river if slightly off.

**Comment by Janette-Lumley** [comment]
@helendallas I have added original site codes and site names as well as updated the co-ordinates so that the site lies on the river.
I don't see anywhere to add physio-chemical data though, please could you assist.

**Comment by helendallas** [comment]
@Janette-Lumley 
I have edited file with correct headers - attached.  Click on below to open

[Chantel Petersen Abiotic data_data.xlsx](https://github.com/helendallas/FRC_FBIS/files/4375248/Chantel.Petersen.Abiotic.data_data.xlsx)

**Comment by Janette-Lumley** [comment]
@helendallas the excel spreadsheet data is different from the data in the Thesis. Please could you check before I continue? I added the thesis table to the spreadsheet on dropbox.

**Comment by Janette-Lumley** [comment]
@helendallas please could you also check if conductivity is the correct measurement. Thanks

**Comment by helendallas** [comment]
@Janette-Lumley 
The data look the same to me.
![image](https://user-images.githubusercontent.com/45286876/78555155-b5027800-780c-11ea-81de-688321683bd7.png)

conductivity (mS m-1) see page 39

**Comment by Janette-Lumley** [comment]
Thanks @helendallas, something must've gone wrong with the original spreadsheet, the COD column had the Ph data in and the rows got a bit messed up. I added another tab "Thesis" with the correct data. I have now added the data in FBIS.
