### ISSUE TITLE
22. ORASECOM Data

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#191]
Going to park this data for now

**Comment by helendallas** [comment]
Again please give reason, thanks @aneriswanepoel

**Comment by aneriswanepoel** [comment]
@helendallas if I remember correctly it's because we don't have any context for the data (ie collector names, PDFs etc) but I can try do some digging

**Comment by helendallas** [comment]
I think it was because we dont have permission to use this data. It came Via Rob Palmer/ Nepid database. I suggest leaving for now

**Comment by helendallas** [comment]
It would be really good to explore what data we can include from this programme.

https://wis.orasecom.org

Some data are readily available in the reports but it may make better sense to go to the source.

**Comment by helendallas** [comment]
Closing ticket as we don't have permission to share these data
