### ISSUE TITLE
Fix unpublished data duplicates for Data provided by Mike Coke of Natal Parks Board/EKZNWildlife

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#194]
Please go into Source Reference and rename all 
![image](https://user-images.githubusercontent.com/45286876/133588716-ed15404d-6a18-4b89-a6a9-d8040fcee7c0.png)

Should all be:
Data provided by Mike Coke of Natal Parks Board/EKZN Wildlife

Then the records should be merged if the name is the same

Link:

https://freshwaterbiodiversity.org/source-references/?type=unpublished&page=3&q=&collectors=

**Comment by helendallas** [comment]
Use this to copy and paste into Title and Source Name, so that they are identical

**Data provided by Mike Coke of Natal Parks Board/EKZN Wildlife** must be overwritten in both these fields for the records to be reassigned.

![image](https://user-images.githubusercontent.com/45286876/133589977-0f69947f-6535-49f4-aa23-f6f6d6f8e5dc.png)

**Comment by Janette-Lumley** [comment]
@helendallas I have fixed the duplicates so there is only one now with all data merged.
