### ISSUE TITLE
TMG Algal data

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#195]
Please capture the algal data from the **TMG wetlands sites**

- The original data file is on dropbox:
- Modules/Algae/.................................

The site location is in Table xxx
[1. KNP fish data - raw.xlsx](https://github.com/helendallas/FRC_FBIS/files/7209094/1.KNP.fish.data.-.raw.xlsx)

![image](https://user-images.githubusercontent.com/45286876/134310811-61261060-21f2-4068-99db-1a60e3cd017f.png)

**Comment by KSnaddon** [comment]
TMG algae data are on Dropbox - EPM1 (2008 - 2010) and EPM2 (2011 - 2013)  
[FINAL_algae_spp_TMGA_EPM1.xlsx](https://github.com/helendallas/FRC_FBIS/files/7237709/FINAL_algae_spp_TMGA_EPM1.xlsx)

[TMG Algae Species Dataset_EPM2.xlsx](https://github.com/helendallas/FRC_FBIS/files/7237718/TMG.Algae.Species.Dataset_EPM2.xlsx)

The EPM2 file was a macro-enabled spreadsheet, so I've saved it as an xlsx file. I will need to check to see how this impacts the data / pivot tables.

**Comment by KSnaddon** [comment]
I have copied the co-ordinates of all sites into the relevant spreadsheet - there is a sheet named "Seep algal sample sites" in both the EPM1 and EPM2 files.

**Comment by Janette-Lumley** [comment]
@KSnaddon and @helendallas I will check the progress and report back

**Comment by helendallas** [comment]
[TMG wetland algae taxa not on Master List 16 May 2023.xlsx](https://github.com/helendallas/FRC_FBIS/files/11488966/TMG.wetland.algae.taxa.not.on.Master.List.16.May.2023.xlsx)


There are more taxa to add to the Algal Master List, based on the TMG wetland algal data. These data are ready for upload, but we need to add the taxa, and the algal sampling method ("sediment sample") to the upload template.

@helendallas

**Comment by helendallas** [comment]
@KSnaddon @Janette-Lumley 
Are these data ready for uploading yet?

**Comment by KSnaddon** [comment]
@helendallas They have been for some time. @Janette-Lumley Can you please send me the data for a once-over before I send to Helen?

**Comment by helendallas** [comment]
@KSnaddon Please confirm once these data are ready for uploading.

**Comment by helendallas** [comment]
From #226 The upload files have been separated into EMP1 and EMP2 and wq data added to EMP1.

Lets please schedule some time next week to upload these data so that I can show you the process.

Here are the relevant file for your records

[Snaddon.et.al.2014.EMP1 TMGA.ALGAE.FINAL.xlsx](https://github.com/helendallas/FRC_FBIS/files/13113963/Snaddon.et.al.2014.EMP1.TMGA.ALGAE.FINAL.xlsx)

[Snaddon.et.al.2014.EMP2 TMGA.ALGAE.FINAL.xlsx](https://github.com/helendallas/FRC_FBIS/files/13113966/Snaddon.et.al.2014.EMP2.TMGA.ALGAE.FINAL.xlsx)

**Comment by KSnaddon** [comment]
@helendallas Thanks.  Yes, let's please do this together next week.

**Comment by KSnaddon** [comment]
Just need to delete the last column, which concatenates site, date and taxon

[Snaddon.et.al.2014.EPM2 TMGA.ALGAE.31Oct2023.xlsx](https://github.com/helendallas/FRC_FBIS/files/13279159/Snaddon.et.al.2014.EPM2.TMGA.ALGAE.31Oct2023.xlsx)
[Snaddon.et.al.2014.EPM1 TMGA.ALGAE.31Oct2023.xlsx](https://github.com/helendallas/FRC_FBIS/files/13279160/Snaddon.et.al.2014.EPM1.TMGA.ALGAE.31Oct2023.xlsx)

**Comment by KSnaddon** [comment]
@helendallas Please can you share the latest TMG seep algae spreadsheets, as of this morning?  Janette needs to make some edits etc

**Comment by helendallas** [comment]
Here we go. I didn't add in in Analyst and Institute to EPM 2 yet, so @Janette-Lumley please can you add.

[Snaddon.et.al.2014.EPM1.TMGA.ALGAE.31Oct2023.xlsx](https://github.com/helendallas/FRC_FBIS/files/13295246/Snaddon.et.al.2014.EPM1.TMGA.ALGAE.31Oct2023.xlsx)
[Snaddon.et.al.2014.EPM2 TMGA.ALGAE.31Oct2023.xlsx](https://github.com/helendallas/FRC_FBIS/files/13295248/Snaddon.et.al.2014.EPM2.TMGA.ALGAE.31Oct2023.xlsx)

**Comment by Janette-Lumley** [comment]
Thanks @helendallas will do

**Comment by KSnaddon** [comment]
@helendallas I have added "Botrydiopsis" via BIMS Taxa (Production site), but it isn't appearing on the Algae list, if I search in Taxon Management.  What am I missing? Or is this a bug?

It isn't on GBIF, but is on Algaebase as a Genus.

**Comment by KSnaddon** [comment]
@helendallas If I upload the same dataset again (on Test site), after correcting errors (eg. TMG EPM2 algal data), do I need to delete the ones that were loaded the first time around?  Or can I just re-load to Test site?  Assume that I can do so until it's succesful, and then load to Production Site?

I am just waiting to see how to resolve the Botrydiopsis issue before trying again!

**Comment by KSnaddon** [comment]
@Janette-Lumley Was the issue relating to EPM1 solved? I think it was to do with the Source Reference?

**Comment by Janette-Lumley** [comment]
@KSnaddon yes Dimas fixed the error, I have uploaded the document

**Comment by KSnaddon** [comment]
@helendallas @Janette-Lumley I am uploading the EPM1 data to the Production site, as the upload to the Test site was succesful and everything is in the right place.

EPM2 will be next.

Here are the final Excel and csv files for EPM1:

[Snaddon.et.al.2010.EPM1.TMGA.ALGAE.27Nov2023_Updated.csv](https://github.com/helendallas/FRC_FBIS/files/13484500/Snaddon.et.al.2010.EPM1.TMGA.ALGAE.27Nov2023_Updated.csv)
[Snaddon.et.al.2010.EPM1.TMGA.ALGAE.27Nov2023_Updated.xlsx](https://github.com/helendallas/FRC_FBIS/files/13484499/Snaddon.et.al.2010.EPM1.TMGA.ALGAE.27Nov2023_Updated.xlsx)

**Comment by helendallas** [comment]
Great @KSnaddon Thanks

**Comment by KSnaddon** [comment]
@helendallas We have just picked up the fact that although the upload of EPM1 was successful, there are sites missing.  The upload report lists these missing sites as being there, and having been successfully uploaded, but then they don't appear on the map.  I suspect that this is due to sites being very close together??  This is a problem, as there could be wetland sites within a wetland polygon that are close to each other.

**Comment by helendallas** [comment]
Are the sites listed when you open them here. It's then a resolution issue.If this sites ar every close together then you may not be able to see them

<img width="658" alt="Screenshot 2023-11-28 at 10 05 44" src="https://github.com/helendallas/FRC_FBIS/assets/45286876/327938cc-b2b8-4f00-8a98-3e515a239e5b">

**Comment by helendallas** [comment]
Also @KSnaddon The site are being coded as per river coding not wetland coding :(

**Comment by KSnaddon** [comment]
@helendallas Gosh, yes, you're right.  Is this an issue for Dimas?

**Comment by helendallas** [comment]
Yes I have created a ticket.

I also noticed when you elect Ecosystem type = wetland and then add a site code, you get all sites returned. I will make another ticket for that now

**Comment by KSnaddon** [comment]
@helendallas If I use the Lasso, I only get 4 sites returned instead of 5.  

Also, I downloaded the occurrence data from FBIS, and there are quite a few sites missing.  The total number of actual records uploaded is 4538 (in the csv file for upload) but only 2837 in the downloaded Occurrence Data file. Hope that makes sense.
[OccurrenceData.csv](https://github.com/helendallas/FRC_FBIS/files/13486140/OccurrenceData.csv)

**Comment by helendallas** [comment]
Oh dear. Did this not happen on the testing site?

**Comment by KSnaddon** [comment]
@helendallas I'm afraid I didn't realise - I looked at the Success Report, then the sites on the map, and checked that they were in the correct location.  I also thought I wasn't seeing them due to resolution.

**Comment by Janette-Lumley** [comment]
@helendallas and @KSnaddon let me know when the issue is resolved and then I can compare the FBIS csv to the upload spreadsheet and create a new upload spreadsheet with just the missing sites.

**Comment by helendallas** [comment]
@KSnaddon Let me check and revert. Then we might need to get Dimas to check

**Comment by helendallas** [comment]
I ma uploading csv file again. will let you know result.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley but we need to figure out what the problem is

**Comment by helendallas** [comment]
SO when I concatenated lost and long, you have 95 unique sites

![image](https://github.com/helendallas/FRC_FBIS/assets/45286876/0898226e-8f62-4be6-bca0-126559ecd170)

And when I do the same with User Site Code there are 100, so some sites have the same co-ordinates

![image](https://github.com/helendallas/FRC_FBIS/assets/45286876/bb59a8b8-2f06-4489-b21b-39bc7e49f7fb)

Here you can find the sites with the same co-ordinates. If a site has the same co-ordinate then it will be considered the same site when data are uploaded. This may partly explain why some data are missing.

![image](https://github.com/helendallas/FRC_FBIS/assets/45286876/760aedd4-cee7-4197-bdc5-ac3c3956093a)

**Comment by KSnaddon** [comment]
@helendallas Thanks - that's a useful way to check. I'll remember that for future uploads.  It's weird because the sites are not on top of each other on my GIS map (see P1 and P5 below)!  It could be a decimal place issue.

![image](https://github.com/helendallas/FRC_FBIS/assets/91128958/80cfb805-6361-462c-8840-722850a792d7)

**Comment by Janette-Lumley** [comment]
@KSnaddon I just checked on the spreadsheet that I copied the coordinates over from and for H6_1 S1 and S5 have the same coordinates. So this must be the issue here. I will go through the file and highlight duplicate coordinates. 

![Picture1](https://github.com/helendallas/FRC_FBIS/assets/55576335/fd04f1e2-a0d9-45ea-bf7c-1872364641b0)

**Comment by helendallas** [comment]
Yeah I create a pivot table. I am uploading to testing again to check if that is the only issue

**Comment by helendallas** [comment]
SO I uploaded to testing and all data uploaded fine. File attached.

I will try and upload to production now.

[success_Snaddon.et.al.2010.EPM1.TMGA.ALGAE.xlsx](https://github.com/helendallas/FRC_FBIS/files/13488753/success_Snaddon.et.al.2010.EPM1.TMGA.ALGAE.xlsx)

**Comment by KSnaddon** [comment]
@helendallas There isn't a problem with uploading (it worked fine for me too) but that the points with the same co-ords are creating a problem.  I need to correct the co-ords before we upload again.

**Comment by helendallas** [comment]
This has been completed and successfully uploaded to FBIS. 

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221270%22]&endemic=&conservationStatus=[]&modules=22&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

Closing ticket
