### ISSUE TITLE
TMG invertebrates - wetlands

### ISSUE THREAD

**Issue by KSnaddon** [helendallas/FRC_FBIS#196]
Capture invert data from TMG wetlands

sdbgalsjddbjvgalsjdbv

**Comment by helendallas** [comment]
@KSnaddon Please add to this ticket

**Comment by KSnaddon** [comment]
I have added the TMG seep invert data to Dropbox
[TMG Inverts Raw Data from Denise 270510.xlsx](https://github.com/helendallas/FRC_FBIS/files/7237649/TMG.Inverts.Raw.Data.from.Denise.270510.xlsx)

This file (and the algae too) may be need some explaining.

**Comment by KSnaddon** [comment]
The co-ords for these sites are the same as for the algae (usually up to 5 sampling points per seep).  Note that there are few entries for seep inverts, as we recorded very few.

**Comment by helendallas** [comment]
@Janette-Lumley @KSnaddon Pease update me on this ticket

**Comment by KSnaddon** [comment]
@Janette-Lumley I've gone blank on whether you have prepared these for upload?

**Comment by Janette-Lumley** [comment]
@KSnaddon @helendallas I have captured the data, I parked it until the wetland module was ready, not sure about the status on that but I would just need to do a final check against the master list etc. Let me know when you need it for upload. Thanks.

**Comment by helendallas** [comment]
@Janette-Lumley Please can you share the file with me. O don't know where you are keeping it on dropbox. Maybe you need t join the consolidation folder again as the different folders are getting confusing.

**Comment by Janette-Lumley** [comment]
@helendallas I have saved it to the Janette only folder on dropbox. I won't have enough space to join the consolidation folder. 
There are 6 taxa not in the master list:
Acarina
Forficulidae
Scutigeromorpha
Forficulidae
Araneae
Stempellinella

@KSnaddon do you have a pdf version of the report?

**Comment by KSnaddon** [comment]
@Janette-Lumley The file is too big to drop here.  Here is a Dropbox link: https://www.dropbox.com/scl/fi/jsvm9dty2hjglz75e4mq0/TMGA-EMA_report_Vol_A_FINAL_22July2010.pdf?rlkey=iemzxs8tuay27543dp6h7u2wl&dl=0

**Comment by KSnaddon** [comment]
@helendallas Will you add those taxa to the ML? Or should I?

**Comment by helendallas** [comment]
Let me do the invertebrates - I won't get to it until next week though

**Comment by KSnaddon** [comment]
@helendallas I had a look at the original data, and at GBIF, to check these taxa that are not on the ML; see my notes below:

Acarina should be Hydracarina (genus) - doubtful on GBIF, but should be added to FBIS as it's commonly used
Forficulidae = earwig; terrestrial but occurs in damp soils
Scutigeromorpha = centipede; terrestrial but occurs in damp soil
Araneae = spiders; terrestrial but occurs around wetlands in the veg
Stempellinella = a genus of Chironomidae, so should add this

**Comment by helendallas** [comment]
@helendallas To update invert master list. Then @Janette-Lumley @KSnaddon to update data file, add FBIS site codes, and upload

**Comment by helendallas** [comment]
Master list updated as follows: Note production add taxonomy still not working so added to master list and testing for now -  still to add to production
Acarina should be Hydracarina (genus) -  Made family Hydrachnidae
Forficulidae = earwig; terrestrial but occurs in damp soils - Added
Scutigeromorpha = centipede; terrestrial but occurs in damp soil -  Added
Araneae = spiders; terrestrial but occurs around wetlands in the veg -  Added although I have excluded these for rivers as not aquatic
Stempellinella = a genus of Chironomidae - added

**Comment by helendallas** [comment]
Upload on testing had errors:

These taxa were missing -  added to Master list and Testing =. still to add to production
Trissopelopia
Isotomidae

Upload file fixed- successful upload on the testing site.

**Comment by helendallas** [comment]
@KSnaddon I have uploaded missing invert taxa to testing as Dimas has still not deployed fix to production. He promised he will do this first thing on Monday.

I found two extra missing taxa - see above - which I have added.

I am not sure if you want to add 
User Hydrogeomorphic Type before I upload

Also Are these sites different to the TMG algal sites?  If they are the same then we need to first upload the algae data, then add the Site code into the invert upload file, before uploading.

**Comment by helendallas** [comment]
@KSnaddon Here is the most recent data file for you to work with.

[Snaddon K, TMGA Ecological and Hydrogeological Monitoring.xlsx](https://github.com/helendallas/FRC_FBIS/files/13456775/Snaddon.K.TMGA.Ecological.and.Hydrogeological.Monitoring.xlsx)

**Comment by helendallas** [comment]
All taxa added to FBIS Production. Ready to upload once @KSnaddon has reverted

**Comment by KSnaddon** [comment]
@helendallas I will look at this over the weekend and revert

**Comment by KSnaddon** [comment]
@helendallas I will give @Janette-Lumley the list of FBIS codes for the TMG EPM1 sites - can I ask her just to add them to the Excel file?
[Snaddon.et.al.2010.EPM1.TMGA.INVERTS.28Nov2023_Updated.xlsx](https://github.com/helendallas/FRC_FBIS/files/13484566/Snaddon.et.al.2010.EPM1.TMGA.INVERTS.28Nov2023_Updated.xlsx)

**Comment by helendallas** [comment]
@KSnaddon Yes that will be great.

**Comment by KSnaddon** [comment]
@Janette-Lumley Please note that the FBIS codes are wrong for these sites - they are being generated as though for river sites and not wetland sites.  So put this on hold please.

**Comment by Janette-Lumley** [comment]
Thanks @KSnaddon will do.

**Comment by helendallas** [comment]
Update on this ticket please ? @Janette-Lumley @KSnaddon

**Comment by Janette-Lumley** [comment]
@KSnaddon was this uploaded to FBIS successfully?

**Comment by KSnaddon** [comment]
@helendallas @Janette-Lumley The FBIS codes have now been generated correctly - i.e. as for wetlands, and not rivers.  I have now matched the sites for the algae data (previously uploaded) and these invertebrate data, and have successfully uploaded to the Test Site.  If OK with you Helen, I can upload to the Production Site.

**Comment by helendallas** [comment]
Thanks @KSnaddon Happy for you to upload to production.

**Comment by helendallas** [comment]
@KSnaddon @Janette-Lumley Please can you attach the final version of the file that has been uploaded to FBIS thanks. I always try and do this when data are uploaded.

**Comment by KSnaddon** [comment]
@helendallas Attach where?

**Comment by helendallas** [comment]
drop xls file in this ticket

**Comment by KSnaddon** [comment]
[Snaddon.et.al.2010.EPM1.TMGA.INVERTS.17May2024.KATE.xlsx](https://github.com/user-attachments/files/16282482/Snaddon.et.al.2010.EPM1.TMGA.INVERTS.17May2024.KATE.xlsx)
