### ISSUE TITLE
Invertebrate Taxon Data - add DOI and "Document Upload Link"

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#20]
We need to include DOI for the invertebrate taxon data we are consolidating as per the fish.

Response from Toni:
We just need to add two columns:
1.) "DOI"
2.) "Document Upload Link"
Janette and Aneri – please add these columns to all future spreadsheets. 

These two columns come after the "Reference category" column in the sheet.
DOI must be in this example format: 10.3377/004.044.0109

The document upload link column is used for Published reports and theses (i.e. when we need to upload an actual PDF). This requires uploading the PDF to the document management site on FBIS. I can do this, just let me know when you are ready.

Janette - Could you please add the two new columns to all your datasheets and populate the DOI column where possible. Once that has been done could you let me know all the studies done that are either a published report or thesis so I can upload the document. Thanks.

**Comment by helendallas** [comment]
@toniolsen @Aneri16 @Janette-Lumley 
Please add two columns to all new invertebrate taxon spreadsheets as suggested by Toni

Toni - please confirm that these are at the end.

Also Toni - please can you go through all existing invertebrate taxon spreadsheets and add the two columns, then add the DOI, or "Document Upload Link"

No PDFs can be uploaded yet as the invertebrate data needs to be ingested into FBIS first.

**Comment by toniolsen** [comment]
@Janette-Lumley @helendallas @Aneri16 
I have added these two columns into all existing sheets in the Invert species "Data to combine" folder.
@Janette-Lumley could you please confirm that these are the final datasheets for invert species data in this data to combine folder?

@helendallas, I am able to upload the documents even if the data is not in FBIS. It just creates a link that I paste for each record. So I will do this for all the invert species documents (published reports and theses).
