### ISSUE TITLE
S Pollard PhD thesis 2001

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#201]
Extracted; to be checked and uploaded to FBIS

**Comment by aneriswanepoel** [comment]
Waiting for feedback from Sharon re correct data

**Comment by aneriswanepoel** [comment]
Kyle trying to convert the data into readable format. If he does not come right then will send the CD down to me in Cape Town.

**Comment by aneriswanepoel** [comment]
Raw data received from Kyle

**Comment by helendallas** [comment]
Uploaded to FBIS but not able to check as records missing. Please check again @aneriswanepoel once Dimas has fixed missing issue records
