### ISSUE TITLE
Check fish data with no metadata

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#217]
There are some with no metadata for these fish records. 
@aneriswanepoel Please can you check the following

Site code ; Pseudobarbus phlegethon, sampled in 1998 by Ernst Swartz
E1OUDS-00030
E1BOSK-00035
E1NOOR-00066
E1TEER-00080

**Comment by aneriswanepoel** [comment]
@helendallas those records were duplicates so I have deleted them

**Comment by helendallas** [comment]
Thanks @aneriswanepoel
