### ISSUE TITLE
SASS Data - Dallas Eerste River and tribs

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#22]
Check SASS data for Dallas 1997 (Dallas 1995)
several sites

    Correct sampling Dates
    Add biotope ratings (see on datasheets) HD has added
    Check taxa
    Change Reference Source to:
    Peer-reviewed Scientific Article
    DOI: 10.1080/10183469.1997.9631389

Add in Notes;
Dallas, H.F. 1995. An evaluation of SASS (South African Scoring System) as a tool for the rapid bioassessment of water quality. Master of Science Thesis, Department of Zoology, University of Cape Town.

**Comment by aneriswanepoel** [comment]
Teloganodidae not on SASS sheets and Ephemerillidae not on FBIS invert list so unsure how to proceed with data entry for some sites/dates

**Comment by helendallas** [comment]
Telagonodidae is the new name for ephemerellidae. Also please don't close any issues. Just move into done column. Once I have checked in will sign off and close the ticket

**Comment by aneriswanepoel** [comment]
Okay thanks for clarification!
