### ISSUE TITLE
1. Invertebrates - Malakane thesis 2019

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#220]
Invertebrate data extracted from Google Scholar search results for Lowveld Region
https://www.dropbox.com/sh/w07c6yj0nxy56rr/AADgq_Fajqg-DlJCxkxXZvMPa?dl=0

**Comment by helendallas** [comment]
@Janette-Lumley Please cna you check that all the data has been correctly added by Aneri.

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221187%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=

**Comment by Janette-Lumley** [comment]
@helendallas the data has been added correctly, there are just a few missing because they aren't on the master list.
I have sent the missing ones to Kate and will add them in once the algae master list has been updated.

**Comment by helendallas** [comment]
@Janette-Lumley But these are invertebrates not algae? Why sending to Kate.

**Comment by Janette-Lumley** [comment]
@helendallas the link you sent goes to sites with only algae. I see now the heading for this ticket is different, I will check that data too.

**Comment by helendallas** [comment]
Sorry @Janette-Lumley Here is link

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221133%22]&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=

**Comment by Janette-Lumley** [comment]
Thanks @helendallas I have checked and everything is correct
