### ISSUE TITLE
TMG seep WQ data for algal module

### ISSUE THREAD

**Issue by KSnaddon** [helendallas/FRC_FBIS#226]
I have copied EPM1 water quality data for the TMG seeps onto the FBIS wetland Dropbox folder.  Also here:
[TMG EPM1 WQ data.xlsx](https://github.com/helendallas/FRC_FBIS/files/7609260/TMG.EPM1.WQ.data.xlsx)

There are no data for EPM2 for the seeps / algal sampling points

**Comment by KSnaddon** [comment]
[TMG wetland algae taxa not on Master List 16 May 2023.xlsx](https://github.com/helendallas/FRC_FBIS/files/11488966/TMG.wetland.algae.taxa.not.on.Master.List.16.May.2023.xlsx)
There are more taxa to add to the Algal Master List, based on the TMG wetland algal data. These data are ready for upload, but we need to add the taxa, and the algal sampling method ("sediment sample") to the upload template.

@helendallas

**Comment by helendallas** [comment]
@KSnaddon @Janette-Lumley Were these waters quality data added to the algal upload file or are they needing to be uploaded as a separate physics-chemical spreadsheet?

**Comment by KSnaddon** [comment]
@Janette-Lumley Can you check whether I sent you the WQ data (very sparse) for the TMG seep sites?

**Comment by Janette-Lumley** [comment]
@KSnaddon yes I have captured the water quality data into the upload file

**Comment by KSnaddon** [comment]
Thanks!

**Comment by KSnaddon** [comment]
@helendallas @Janette-Lumley I have deleted a couple of occurrence data records from the EPM1 and EPM2 spreadsheets due to spelling errors or inadequate ID (cysts), etc..  These two datasets are ready for upload as soon as we can upload wetland datasets.

[Snaddon et al 2014. TMGA ALGAE FINAL.xlsx](https://github.com/helendallas/FRC_FBIS/files/12918082/Snaddon.et.al.2014.TMGA.ALGAE.FINAL.xlsx)

**Comment by helendallas** [comment]
Thanks @KSnaddon @Janette-Lumley .  I think this file belongs in #195, not this one which is about water quality data.

I have downloaded the attached file and split it to EMP1 and EMP2. 

I noted that the wq data for ph, cond and temp have been added to upload file for EMP1

Closing as #195 is relevant
