### ISSUE TITLE
6. Invertebrates - Soko 2014

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#227]
Google scholar search result. To be checked then uploaded to FBIS.

**Comment by aneriswanepoel** [comment]
Some issues with taxa not on masterlist (Prosopistomatidae & Bulininae) @helendallas

**Comment by helendallas** [comment]
@aneriswanepoel 

Added Prosopistomatidae  -  again was already in my master list?

Bulininae is not recognised on GBIF. I suggest you add as Family **Bulinidae**. I have added this in Taxon Management

You should be able to upload now

**Comment by aneriswanepoel** [comment]
Successful upload to testing, but upload to Live does not recognize Polymitarcyidae for some reason.

**Comment by helendallas** [comment]
Strange, as in master list. I have added it to Taxon Management now so should be able to upload.

**Comment by helendallas** [comment]
Uploaded but cannot check and missing records. Issue that Dimas will be fixing. @an please check again.

**Comment by aneriswanepoel** [comment]
@helendallas all records restored
