### ISSUE TITLE
SANPArks SASS survey 2021

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#228]
SASS data received from Robin Petersen for recent SASS survey by KNP team. Waiting for SASS data from Sabie and Crocodile surveys

**Comment by aneriswanepoel** [comment]
Issue with adding Metadata. Adding PDF/source document not working.

**Comment by helendallas** [comment]
@aneriswanepoel What is the status of this?
No SASS data 
![image](https://user-images.githubusercontent.com/45286876/189901006-65923c8d-c9ca-4bed-89bd-eb47120ec2f4.png)

**Comment by aneriswanepoel** [comment]
The SASS data was recorded under Gerhard Diedericks. Robin only sent the data to me.
![image](https://user-images.githubusercontent.com/55532903/189903978-5549cc7f-6ccc-43fa-a8c7-cc96a32238cf.png)

@helendallas

**Comment by helendallas** [comment]
Please add the photos for each sampling visit from the SASS data sheets. Always do this when available please.

**Comment by aneriswanepoel** [comment]
@helendallas photos have been added
