### ISSUE TITLE
Invertebrate Taxon data - SR Daniels Potamonautidae

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#23]
Awaiting feedback from Prof Daniels re his data on freshwater crabs
@Janette-Lumley  I will alert you once he has responded

**Comment by helendallas** [comment]
@Aneri16 Several papers received from author. 

Please add all of these to the CFR Master List Study References in the dropbox folder below. And always add DOI or document link as per ticket #20

[Invertebrates CFR Master List Study References.xlsx](https://github.com/helendallas/FRC_FBIS/files/3655941/Invertebrates.CFR.Master.List.Study.References.xlsx)

**Comment by aneriswanepoel** [comment]
Only one paper has co-ordinates. The rest don't have co-ordinates and one of them is not a South African study. Must I still add all of them to the reference list? I am going to see if I can get the co-ordinates in the mean time.

**Comment by aneriswanepoel** [comment]
@Janette-Lumley @helendallas 
Of the papers Savel sent me, only one has co-ordinates. I have tried to find the co-ordinates for the other papers but this doesn't look promising or likely to come to anything so I am going to go ahead with data extraction of what we do have. I have found one more paper on the knowledge database (Daniels et al 2006) that has co-ordinates so will extract that data too. I must just contact Savel re the dates of data collection.

**Comment by helendallas** [comment]
Papers we have in the Knowledge database include:
@Aneri16 please check to see if any of these are useful and add to the adhoc file

Daniels   S.R. | 2003 | Examining the   Genetic Structure among Populations of the Common Cape River Crab Potamonautes Perlatus from   River Systems in South Africa Reveals Hydrographic Boundaries . | Journal of   Crusacean Biology 23(4): 936-950.

Daniels S.R., Gouws G. & Crandall K.A. | 2006 | Phylogeographic   patterning in a freshwater crab species (Decapoda: Potamonautidae: Potamonautes) reveals the signature   of historical climatic oscillations. | Biogeography 33(9):   1538-1549.

Daniels S.R., Stewart B.A. & Burmeister L. | 2001 | Geographic   patterns of genetic and morphological divergence amongst populations of a   river crab (Decapoda, Potamonautidae) with the description of a new species   from mountain streams in the Western Cape, South Africa. | Zoologica   Scripta 30(3): 181-197.

Daniels S.R., Stewart B.R. & Gibbons M.J. | 1998 | Genetic   and morphometric variation in the potamonautid river crab Potamonautes parvispina (Decapoda:   Potamonautidae) from two Western Cape rivers, South Africa. | Journal   of Natural History 32(8): 1245-1258.

Gouws G., Stewart B.A. & Daniels S.R. | 2004 | Cryptic   species within the freshwater isopod Mesamphisopus   capensis(Phreatoicidea: Amphisopodidae) in the   Western Cape, South Africa: allozyme and 12S rRNA sequence data and   morphometric evidence. | Biological   Journal of the Linnean Society 81(2): 235-253.

Gouws G., Stewart B.A. & Mathee C.A. | 2005 | Lack   of taxonomic differentiation in an apparently widespread freshwater isopod   morphotype (Phreatoicidea: Mesamphisopidae: Mesamphisopus) from South Africa. | Molecular   Phylogenetics and Evolution 37(1): 289-305.

**Comment by aneriswanepoel** [comment]
@helendallas 
I have extracted the Daniels et al 2006 paper. The rest do not have co-ordinates.

**Comment by helendallas** [comment]
@Aneri16 
Please can you email me all the papers he sent us.  I want to add them to the knowledge database, even thoughonly one has data that are included.

**Comment by helendallas** [comment]
@Aneri16 Please can you add all these references to our master list, indicating that they have no oc-ordinates, hence data cannot be captured.

https://www.dropbox.com/s/62cyyzuuqdeiram/Invertebrates%20CFR%20Master%20List%20Study%20References.xlsx?dl=0
