### ISSUE TITLE
8. Invertebrates - Dos Santos 2016

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#231]
Invert data from fish study on FBIS. Species name not on the masterlist (Paradiplozoon krugerense)

**Comment by helendallas** [comment]
@aneriswanepoel 

I have added this species to FBIS Taxon MAnagement. You should be able to upload now.

**Comment by aneriswanepoel** [comment]
Fish parasite..

**Comment by helendallas** [comment]
Okay removed from Taxon Management until we decide on route for fish parasites

**Comment by helendallas** [comment]
Not including fish parasites, closing ticket
