### ISSUE TITLE
9. Invertebrates - Nunes et al 2016

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#232]
One species not on masterlist - Procambarus clarkii

**Comment by helendallas** [comment]
@aneriswanepoel 
I have added this non-native species to FBIS Taxon management. You should be able to upload now.

**Comment by aneriswanepoel** [comment]
One Site Code not correct after uploading to Testing.

**Comment by helendallas** [comment]
@aneriswanepoel so your comment re one site code? Did you correct and is data now on FBIS?

**Comment by helendallas** [comment]
Uploaded and checked
