### ISSUE TITLE
10. Invertebrates - Van As 2017

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#233]
Species not on masterlist (Chonopeltis meriodionalis)

**Comment by helendallas** [comment]
So this is a fish parasite, not a free-living invertebrate. Lest park this for now as it requires consideration as to if and how this get included.  There are bound to be many more records from Jo van As and colleagues work in SA. Perhaps we need a separate module down the line?

**Comment by helendallas** [comment]
Not including fish parasites, closing ticket
