### ISSUE TITLE
Inverts not on FBIS

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#234]
There are a few inverts that aren't being recognized by FBIS when I try to upload. Some are in the masterlist, some aren't. Also some are in masterlist but not when you search in taxon management.
1. Inverts on masterlist but not when searching taxon management: Hydrometridae; Prosopistomatidae; Bulininae
2. Inverts not on masterlist: Paradiplozoon krugerense; Procambarus clarkii; Chonopeltis meriodionalis

@helendallas

**Comment by aneriswanepoel** [comment]
@helendallas I am going to mention this in the quarterly report that I have just started with, so we can tackle it afterwards.

**Comment by helendallas** [comment]
Thanks @aneriswanepoel I will close this ticket as I have addressed each in the individual tickets.
