### ISSUE TITLE
13. Invertebrates (Molluscs) - De Kock papers

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#237]
Some Molluscs not on masterlist

**Comment by helendallas** [comment]
Please add the spreadsheet and highlight the ones that are missing . Thanks

**Comment by aneriswanepoel** [comment]
@helendallas I have highlighted the missing ones (according to error sheet from testing site upload)
[De Kock et al 2002 2006.xlsx](https://github.com/helendallas/FRC_FBIS/files/8387040/De.Kock.et.al.2002.2006.xlsx)

**Comment by helendallas** [comment]
**Following corrections made to spreadsheet:**
Spathopsis wahlbergi is a synonym of Chambardia wahlbergi -  added synonym as legacy name in Taxon Management
Spathopsis petersi is a synonym of Chambardia petersi -  added synonym as legacy name in Taxon Management
Added Cleopatra bulimoides to Taxon Management
Ceratophallus natalensis is a synonym of Afrogyrorbis natalensis -  added synonym as legacy name in Taxon Management
Oxyloma striata is not in any databases - record deleted

@aneriswanepoel Should be good to upload now.

[De.Kock.et.al.2002.2006.xlsx](https://github.com/helendallas/FRC_FBIS/files/8415824/De.Kock.et.al.2002.2006.xlsx)

**Comment by helendallas** [comment]
Please can you include details of the papers included?  Thanks @aneriswanepoel

**Comment by aneriswanepoel** [comment]
@helendallas Two scientific papers on KNP mollusc diversity.
