### ISSUE TITLE
IUCMA SASS data

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#238]
SASS data received from IUCMA; data for 299 sites to be added

**Comment by aneriswanepoel** [comment]
Complete. 464 assessments uploaded.

**Comment by aneriswanepoel** [comment]
@helendallas I have added SASS data (10454 records) and fish data (108) for IUCMA. Remind me... is it possible to link the two source references so that both SASS and fish data come up simultaneously when you search on the map? At the moment if you search for "Inkomati-Usuthu Catchment Management Agency Database" only the SASS data comes up even if you select both modules. I can only see the fish data when I search the collectors name (Mthobisi Soko)

![image](https://user-images.githubusercontent.com/55532903/166411265-79b2f36a-0212-44c1-9ca2-c45a961a5764.png)

**Comment by helendallas** [comment]
SO there are two source references:
![image](https://user-images.githubusercontent.com/45286876/166428814-414b983f-4bb4-4d39-a126-c6f1015d4210.png)

There seems to be an issue with getting the second one which is the fish data?

I have already created a ticket. Is this urgent? Dimas is on leave till next week and I am not sure if he has signed off on the fix yet?

**Comment by aneriswanepoel** [comment]
@helendallas okay great thanks. No not urgent at all

**Comment by aneriswanepoel** [comment]
@helendallas

**Comment by helendallas** [comment]
Uploaded and checked.
