### ISSUE TITLE
Koen et al KNP Diatom Data 2018-2021

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#249]
Diatom report received from Robin Petersen
[KNP Report_Diatoms 2018- 2021.pdf](https://github.com/helendallas/FRC_FBIS/files/8554872/KNP.Report_Diatoms.2018-.2021.pdf)

@helendallas I am not familiar with this module so perhaps you can take a look first

**Comment by helendallas** [comment]
First step is to confirm the FBIS Site code for each of these sites. Do this for all sites

Second step is to go to each Site, e.g. X3SABI-LUBYE and click Add algal data
![image](https://user-images.githubusercontent.com/45286876/167090578-6f82fc0e-1a57-427a-bad7-13eb038b334e.png)


https://testing.healthyrivers.kartoza.com/algae-form/?siteId=9383

Then fill in whatever data you can in this form:

- Sampling dates were either: September of 2018 and 2019, September of 2020 and 2021
- Owner would be Robin I guess?
- Populate the other fields as I have in the screenshot
- Add photos where possible, if available for a site and sampling date. Right click on pdf and save photo. Keep a record in the dropbox folder named photographs.

![image](https://user-images.githubusercontent.com/45286876/167090051-555dabaf-80d6-41ac-8783-d8a02e38440e.png)

I dont think anything in this section is in the report, but please check with Philip/Kate re the Autotrophic Index
![image](https://user-images.githubusercontent.com/45286876/167091038-1f709073-d083-4e5f-9f18-1271b5cc0347.png)


Then add the taxa recorded, by clicking Add Taxa, select Percentage abundance, click Observed and add abundance value
![image](https://user-images.githubusercontent.com/45286876/167088747-20358196-7cef-430b-9e18-c18bb809d10c.png)

If a taxon is missing make a note, check with Janette and Kate re algal master list.  This should probably be done first to check all species before you start the data capture.

Then add the abiotic data:
![image](https://user-images.githubusercontent.com/45286876/167090828-3a338766-7a35-4441-95cb-e6fe93ea70a0.png)
Table 4: Water quality measured, in situ, during 2018 and 2019.
Table 5: Water quality parameter values measured and calculated during 2021.
Remember to check the units are correct.

Last Select Source Reference

![image](https://user-images.githubusercontent.com/45286876/167091404-c6f108bd-2883-4ca0-923d-8ad778c82914.png)

Work carefully and systematically through the data.

I suggest you first upload one or two to testing to ensure you are comfortable with the process.

**Comment by KSnaddon** [comment]
@aneriswanepoel is making a list of Algal taxa not on the Master List

**Comment by aneriswanepoel** [comment]
All data added.. Missing taxa are:
Encyonopsis krammeri
Brachysira vitrea
Cymbella kappii
Achnanthidium rivulare
Gomphonitzschia ungeri
Gomphonema pumilum var. rigidum
Anorthoneis dulcis
Kolbesia ploenensis
Hippodonta
Nitzschia dicompressa
Rhopalodia operculata
Ulnaria nyanse
Achnanthidium crassum
Navicula vandamii
Navicula microlyra
Fallacia umpatica
Craticula subminuscula
Navicula viridula

@helendallas @KSnaddon

**Comment by aneriswanepoel** [comment]
I've found some more taxa not on FBIS so I've just created a spreadsheet to keep track because the list is getting quite long!
[Missing algae taxa.xlsx](https://github.com/helendallas/FRC_FBIS/files/8832599/Missing.algae.taxa.xlsx)

@KSnaddon

**Comment by helendallas** [comment]
@KSnaddon Not sure if you added these taxa to the master list?

**Comment by helendallas** [comment]
No data on FBIS???? Cannot find xls file

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=[%22Robin%20Petersen%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=22&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=

**Comment by helendallas** [comment]
Data found but ownership Ruan Koen. I have emailed Robin Petersen to check. May need to get Janette to correct.

**Comment by helendallas** [comment]
HD Contacted Ryan Koen and have reassigned correct ownership and uploaded revised pdf from Robin Petersen

**Comment by KSnaddon** [comment]
@helendallas Am I checking the missing taxa from the KNP diatom data, or are you?  I don't think I've looked at the Missing Taxa  list before.

**Comment by helendallas** [comment]
Its all completed and closed

**Comment by KSnaddon** [comment]
@helendallas There are quite a few not on the ML.  I can add these?

**Comment by KSnaddon** [comment]
@helendallas Sorry I may be missing something.  Did you upload a new ML?

**Comment by helendallas** [comment]
mmm ok, Azeri unfortunately left us hanging here. I have lost track and will need some time to figure things out. please park for now

**Comment by helendallas** [comment]
No I am. not touching the master list but I don't know what Azeri did with this data before she left and I can't find the xls file either. I need time to figure out what is going on

**Comment by KSnaddon** [comment]
@helendallas Sure thing, I will leave for now.

**Comment by KSnaddon** [comment]
@helendallas Just for the record, I checked which ones are not on the June 2023 ML, so you don't need to do that.

**Comment by helendallas** [comment]
Okay, I think Aneri added data on master list and then left out missing taxa.

@KSnaddon please can you add new taxa that are legitimate.
@Janette-Lumley Please can you then add to the algal form directly as described above. I suspect most site visits will exist.

Note Data Owner is Ryan Koen (Not Robin Peterson).

Here are the sites

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=[%22Ruan%20Koen%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=

This is the study reference
<img width="1310" alt="Screenshot 2023-09-27 at 12 48 48" src="https://github.com/helendallas/FRC_FBIS/assets/45286876/4165a2f9-8767-4cf0-8a68-6072285aaf54">

**Comment by helendallas** [comment]
@KSnaddon @Janette-Lumley Please update me on this ticket

**Comment by KSnaddon** [comment]
@helendallas I have a relatively short list of taxa to add to the ML.  There was an issue last week and I was waiting for Dimas to fix something.  I will check later today when I get back to see whether I can add them.

I will then let Janette know which taxa need to be corrected or removed from the spreadsheet.

**Comment by KSnaddon** [comment]
@helendallas I am still unable to add a taxon manually using "Taxa" on BIMS admin.  I need to do it this way, as the GBIF taxa offered to me is either wrong or needs editing.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/KATESN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/KATESN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Taxon | Comment
-- | --
Snowella | Need to edit the nomenclature on FBIS - change to Snowella Elenkin
Achnanthidium crassum | Unable to add to FBIS
Brachysira vitrea | Edit on FBIS - synonym
Gomphonema vitreum | Added as accepted species of B vitrea
Cymbella kappii | Unable to add to FBIS
Fallacia umpatica | Unable to add to FBIS
Gomphonema pumilum var. rigidum | Unable to add to FBIS - not on GBIF, but is on Algaebase
Kolbesia ploenensis | Unable to add to FBIS - Only on GBIF as Kolbesia ploenensis var.   ploenensis
Nitzschia dicompressa | Unable to add - spelling mistake?? Not on GBIF or Algaebase
Ulnaria nyanse | Unable to add - spelling mistake?? Not on GBIF or Algaebase



</body>

</html>

**Comment by helendallas** [comment]
@KSnaddon I HAVE ADDED USING WORK AROUNDS, PLEASE CHECK.

> Taxon	Comment
> Snowella	Need to edit the nomenclature on FBIS - change to Snowella Elenkin - CORRECTED BY FIXING GBIF ID
> Achnanthidium crassum	Unable to add to FBIS - ADDED BY ADDING VARIANT AND THEN EDITING
> Brachysira vitrea	Edit on FBIS - synonym - REVISED AND ADDED GBIF ID
> Gomphonema vitreum	Added as accepted species of B vitrea
> Cymbella kappii	Unable to add to FBIS - ADDED BY ADDING VARIANT AND THEN EDITING. THIS IS A SYNONYM OF Cymbella kappii (Cholnoky) Cholnoky, 1956
> Fallacia umpatica	Unable to add to FBIS -  ADDED AND ADDED GIBIF ID SYNONYM
> Gomphonema pumilum var. rigidum	Unable to add to FBIS - not on GBIF, but is on Algaebase ADDED - NEED TO SELECT FAMILY FROM LIST
> Kolbesia ploenensis	Unable to add to FBIS - Only on GBIF as Kolbesia ploenensis var. ploenensis ADDED BY ADDING VARIANT AND THEN EDITING.
> Nitzschia dicompressa	Unable to add - spelling mistake?? Not on GBIF or Algaebase ADDED NOW
> Ulnaria nyanse	Unable to add - spelling mistake?? Not on GBIF or Algaebase NOT DONE YET

**Comment by KSnaddon** [comment]
@helendallas  Cymbella kappii is a species and not a variety, as far as I can see.  I have edited it to be species but just checking to see whether this is correct?   C kappii is a synonym of C turgidula

> Cymbella kappii Unable to add to FBIS - ADDED BY ADDING VARIANT AND THEN EDITING. THIS IS A SYNONYM OF Cymbella kappii (Cholnoky) Cholnoky, 1956

**Comment by KSnaddon** [comment]
@helendallas For this one - I changed it from a species to a variety and corrected the scientific name to the one provided on Algaebase.

> Gomphonema pumilum var. rigidum Unable to add to FBIS - not on GBIF, but is on Algaebase ADDED - NEED TO SELECT FAMILY FROM LIST

**Comment by KSnaddon** [comment]
@helendallas Found this on GBIF as a synonym so changed from species to synonym on FBIS.  Also added the accepted species  

> Kolbesia ploenensis Unable to add to FBIS - Only on GBIF as Kolbesia ploenensis var. ploenensis ADDED BY ADDING VARIANT AND THEN EDITING.

N dicompressa doesn't appear anywhere but happy that you've added it so that we can upload the data! 

> Nitzschia dicompressa Unable to add - spelling mistake?? Not on GBIF or Algaebase ADDED NOW

Added Ulnaria nyanse

**Comment by KSnaddon** [comment]
@helendallas This dataset needs one more cross-check with the ML, and then it's ready for upload

**Comment by KSnaddon** [comment]
@helendallas @Janette-Lumley Do you want to send me the occurrence data spreadsheet for a last check?  I don't think any of the data need to be deleted as we have added all the taxa?

**Comment by Janette-Lumley** [comment]
@KSnaddon I wasn't involved in capturing this data. Looking at this ticket from the beginning I assume that Aneri captured this data mannually into FBIS. @helendallas do I need to capture the ones that were missing as per Aneri's excel file above and have they all been entered into the master list?

**Comment by KSnaddon** [comment]
@Janette-Lumley Helen and I have added the ones that were missing off the Master List, so if we assume the list of missing taxa that Aneri put together is the full list, then all should be OK for upload.

**Comment by helendallas** [comment]
@Janette-Lumley Plase can you contact Azeri and check. I am not sure what she did here / or check taxa against the report.

**Comment by helendallas** [comment]
@Janette-Lumley Please update me on this ticket soonest. Thanks

**Comment by Janette-Lumley** [comment]
@helendallas Aneri captured this data manually into FBIS as at the time there was no upload template for algae. She left out the ones that weren't on the master list. I have captured the missing ones now in the upload template. Attached here and added to the Janette Only folder on dropbox. There is just one missing from the master list now. It is Ulnaria nyanse. 
[Koen et al Water Quality Report_Diatoms_KNP Missing data.xlsx](https://github.com/helendallas/FRC_FBIS/files/13113890/Koen.et.al.Water.Quality.Report_Diatoms_KNP.Missing.data.xlsx)

**Comment by helendallas** [comment]
@Janette-Lumley Thanks. DO you know how to add a taxon onto FBIS but selecting the site and editing the data....it's quite easy and will be better than uploading because of issues with making new erroneous site codes which I am still trying to resolve with Dimas

**Comment by Janette-Lumley** [comment]
@helendallas ok I will add the data into FBIS, I did start like that but the system kept hanging so it was taking very long. I will try again.

**Comment by helendallas** [comment]
actually lets leave it. O am not happy with the data as it has been labelled frustule count??? not Sur eif that is correct.

I would prefer to delete the data on FBIS and for to add you xls data to the file I have downloaded. I will send shortly.
Thanks

**Comment by KSnaddon** [comment]
@helendallas What is the issue with Frustule count?  Can I also see the spreadsheet?

**Comment by helendallas** [comment]
@Janette-Lumley I managed to download the Koen data Aneri added to FBIS. Attached. Please can you add your missing data file to this making sure that the final combined file has all the taxa listed in the original report with correct information. Thanks

@KSnaddon Please can you check what the correct Abundance measure is. Aneri has used a mix of frustule count and percentage. My knowledge of algae is suspect, so would appreciate guidance on the correct measure.

Once completed, please send to me for a final check. I will then delete the current Koen study on FBIS and we can upload the new datafile.



[Koen et al Kruger Algae from FBIS.xlsx](https://github.com/helendallas/FRC_FBIS/files/13224027/Koen.et.al.Kruger.Algae.from.FBIS.xlsx)

**Comment by KSnaddon** [comment]
Will do @helendallas

**Comment by KSnaddon** [comment]
@helendallas The KNP diatom data are recorded in the original report as both a count and a %.  The units for the count are not recorded, and it's unclear from the methods.  If I have to guess it may be a count per 400 ul.  However, it may be the best plan to just add % or proportion as an option for algal data?

**Comment by KSnaddon** [comment]
@Janette-Lumley has now checked the data as entered, and they have been entered correctly but should all be %.

**Comment by Janette-Lumley** [comment]
@helendallas and @KSnaddon here is the updated spreadsheet, I have added the missing taxa.

[Koen.et.al.Kruger.Algae.from.FBIS.xlsx](https://github.com/helendallas/FRC_FBIS/files/13226672/Koen.et.al.Kruger.Algae.from.FBIS.xlsx)

**Comment by Janette-Lumley** [comment]
@helendallas and @KSnaddon don't use the above spreadsheet, I am just fixing up some of the original data so I will send the final one as soon as I am finished. Thanks

**Comment by Janette-Lumley** [comment]
@helendallas and @KSnaddon These are the final spreadsheets, I have entered the data into the latest upload template and also to the file you downloaded from FBIS Helen. I am not sure which is best to use for uploading the data.
[Koen.et.al.Kruger.Algae.from.FBIS.xlsx](https://github.com/helendallas/FRC_FBIS/files/13238895/Koen.et.al.Kruger.Algae.from.FBIS.xlsx)
[Koen.et.al.Kruger.Algae.Final.xlsx](https://github.com/helendallas/FRC_FBIS/files/13238899/Koen.et.al.Kruger.Algae.Final.xlsx)

**Comment by KSnaddon** [comment]
@helendallas Let me know when we can sit together and do the various uploads?

**Comment by helendallas** [comment]
@helendallas Doing final check and edits . Old data needs to be deleted first. then new excel file uploaded

**Comment by helendallas** [comment]
@KSnaddon I uploaded this to testing but one taxon is still missing

Ulnaria nyanse

**Comment by KSnaddon** [comment]
@helendallas LOL - I had added that species to the Fish module by mistake a few weeks back!  I kept on wondering why I couldn't find it in Algae.  I have corrected that now.

**Comment by helendallas** [comment]
ha ha

**Comment by helendallas** [comment]
@KSnaddon Please can you add it to testing as well as I need to upload it there first so Janette can check.

**Comment by KSnaddon** [comment]
@helendallas Done

**Comment by helendallas** [comment]
@helendallas Needs to check what Koen sites are already on FBIS with this data. May be best to just stick to same sites as created by Aneri and to re upload the data to these sites

**Comment by helendallas** [comment]
@Janette-Lumley Please can you check the final upload file - attached here

[Koen.et.al.Kruger.Algae.Final.xlsx](https://github.com/helendallas/FRC_FBIS/files/13456986/Koen.et.al.Kruger.Algae.Final.xlsx)


With this file of data downloaded from FBIS testing site.

[Koen Data from FBIS.xlsx](https://github.com/helendallas/FRC_FBIS/files/13457024/Koen.Data.from.FBIS.xlsx)

They should be the same I hope

**Comment by helendallas** [comment]
Data have been duplicated, I have asked Dimas to add functionality to delete occurrence records associated with a specific source reference.

The. I need to delete and upload data file again

**Comment by helendallas** [comment]
@Janette-Lumley 
Something is not right with this revised upload file you prepared. See highlighted site...same site, with same co-ordinates but its has multiple site codes. also where did these codes come from?  Unless you are 100% bit is the same site as one already on FBIS, then you need to leave it blank and allow FBIS to generate a site code.

This is just one example

Please have a through recheck of this datafile before I create a ticket for Dimas to fix something. Make sure you please check agains the original data as well please. 

[Koen.et.al.Kruger.Algae.Final.xlsx](https://github.com/helendallas/FRC_FBIS/files/13511318/Koen.et.al.Kruger.Algae.Final.xlsx)

**Comment by Janette-Lumley** [comment]
@helendallas it looks like that was my fault when dragging down in excel to copy the code and it incremented the numbers. I have checked all the sites and it was only that one site I made the error with.
I have fixed it.

The FBIS site codes are from the csv file downloaded from FBIS. 

[Koen.et.al.Kruger.Algae.Final30112023.xlsx](https://github.com/helendallas/FRC_FBIS/files/13511593/Koen.et.al.Kruger.Algae.Final30112023.xlsx)

**Comment by helendallas** [comment]
Thanks,

So there are 4 sites in the new upload file that were not on FBIS.

A9LUVU-00195
A9LUVU-00198
A9LUVU-00206
X3SABI-ANTHO

Why did you give these sites an FBIS Site Code if they were not yet on the system?

**Comment by Janette-Lumley** [comment]
@helendallas those sites are in the csv file that was downloaded from FBIS so they must be in FBIS. I didn't allocate any site codes I just copied them from the csv file or am I misunderstanding?

**Comment by helendallas** [comment]
No I think I worked out the issue. Sorry my bad. I deleted one or two site visits, so now only 16 sites. I remember now there were 20 sites, so all good. Sorry for the hassle.
PS. there is still the issue of duplicate records that I have emailed Dimas about.

**Comment by Janette-Lumley** [comment]
Ok phew thanks :)

**Comment by helendallas** [comment]
@helendallas To check and upload csv file

**Comment by helendallas** [comment]
Koen et al data deleted on FBIS - Site codes removed. Data ready to be uploaded again as a clean dataset.

**Comment by helendallas** [comment]
Uploaded. closing ticket
