### ISSUE TITLE
Invertebrate Taxon data - de Moor F.C. 2010

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#25]
Data ready for capture:  Reference Source is:
[de Moor F.C. 2010.pdf](https://github.com/helendallas/FRC_FBIS/files/3641249/de.Moor.F.C.2010.pdf)

Site information is in paper and excel spreadsheet
Species data is in table :
TABLE 1. Species and numbers of Trichoptera recorded at each of the rivers during the survey undertaken in 2005
Survey done in April 2005,

[De Moor 2010 Supplementary data.xlsx](https://github.com/helendallas/FRC_FBIS/files/3641284/De.Moor.2010.Supplementary.data.xlsx)

**Comment by aneriswanepoel** [comment]
Need to add document upload link

**Comment by helendallas** [comment]
@Aneri16 
Please make a comment related to the completion of the task when the data consolidation is finalised.  @toniolsen please can you arrange a session with Janette and Aneri around the document management system.

@Aneri16 
Please don't close any issues -  just move them to done for me to check. I will sign off and close

**Comment by aneriswanepoel** [comment]
I have completed and finalised the data consolidation and have put the datasheet in the "data to combine" folder on Dropbox. I have added the DOI so then no need to add document upload link. @toniolsen can have a look at the datasheet and let me know if anything is missing

**Comment by toniolsen** [comment]
@helendallas I have created a ticket (#30) with detailed screenshots of the PDF upload process.
@Aneri16, @Janette-Lumley let me know if anything is unclear because then we can schedule a Zoom.

**Comment by toniolsen** [comment]
@Aneri16, Looks fine to me.

@Janette-Lumley and @Aneri16 could you please change the name of the "Count" column to "Number" for all invertebrate species data sheets in the data to combine folder.
Also if the sampling method is unknown, please include an "unspecified" category and populate the blank cells. Thanks!

**Comment by aneriswanepoel** [comment]
@toniolsen sure will do. Just realized I need to fill in the taxon rank column for the De Moor data so will do that this morning.

**Comment by toniolsen** [comment]
Great. Thanks @Aneri16
