### ISSUE TITLE
Matthew - Ehemeroptera in the Komati River

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#250]
@aneriswanepoel PLease have a look at the pdf and see if it is possible to extract useful data from this thesis. Can you also see if you can get the url or pdf of the complete thesis

[Uploading Matthew 1968 Ephemeroptera Komatirivier.pdf…]()

**Comment by aneriswanepoel** [comment]
@helendallas this PDF link doesn't work?

**Comment by helendallas** [comment]
Trying again
[Matthew 1968 Ephemeroptera Komatirivier.pdf](https://github.com/helendallas/FRC_FBIS/files/8687114/Matthew.1968.Ephemeroptera.Komatirivier.pdf)

**Comment by aneriswanepoel** [comment]
Old paper so no co-ordinates @helendallas
