### ISSUE TITLE
De Moor et al 1993 - Invertebrates in the Tugela River

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#252]
We need to extract the data for 1999 as listed in Table 4 to 8 (some may not be relevant). The earlier data are already in FBIS.

First you need to check the FBIS site codes for the sites in the earlier studies and make sure to use the same site codes for the 1999 data.

![image](https://user-images.githubusercontent.com/45286876/167114994-53b25762-4705-4a10-b178-1f2d63e16e9f.png)

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22630%22%2C%22641%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

[Uploading De Moor et al 1999 October 1999 Tugela Bushmans.pdf…]()

Lets chat through this before you get going

**Comment by aneriswanepoel** [comment]
@helendallas could you please re-attach the PDF. Thanks

**Comment by helendallas** [comment]
[De Moor et al 1999 October 1999 Tugela Bushmans.pdf](https://github.com/helendallas/FRC_FBIS/files/8698470/De.Moor.et.al.1999.October.1999.Tugela.Bushmans.pdf)

**Comment by aneriswanepoel** [comment]
@helendallas I've had a look and we can't use this data as it's too vague - results aren't site specific
