### ISSUE TITLE
De Moor & Barber-James 2003 Kabouga River

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#253]
Please extract invertebrate data in this report

Dates: 2I-23 February 2003

Aquatic macroinvertebrates from aquatic biotopes at five sites along the river (Table 1) were sampled and flying adults of aquatic insects were collected with hand nets and by means of light traps set up over two nights

Table 4 records the physical water quality parameters recorded and table 5 presents the aquatic macroinvertebrates recorded during the three-day monitoring survey in February 2003.

Details as follows:
![image](https://user-images.githubusercontent.com/45286876/167118327-479790f5-c73a-47e1-8dd2-2f447f238a00.png)

Please add photographs by saving from doc - ask if you are not sure
![image](https://user-images.githubusercontent.com/45286876/167118515-c9da757e-ec62-4c30-ada6-9493eb1d5e69.png)

[De Moor & BarberJames August 2003 Kabouga River.pdf](https://github.com/helendallas/FRC_FBIS/files/8639450/De.Moor.BarberJames.August.2003.Kabouga.River.pdf)

**Comment by aneriswanepoel** [comment]
@helendallas 
The following invert taxa aren't on the masterlist that I can see:
![image](https://user-images.githubusercontent.com/55532903/170993081-a4a30d90-984b-4bdc-9b1c-9f32e36fe2af.png)

**Comment by aneriswanepoel** [comment]
@helendallas I am attaching this spreadsheet here
[De Moor & Barber-James 2003.xlsx](https://github.com/helendallas/FRC_FBIS/files/9623621/De.Moor.Barber-James.2003.xlsx)

**Comment by helendallas** [comment]
Fixed some taxa and remainder added to FBIS, still to upload next week

**Comment by helendallas** [comment]
@Janette-Lumley Please check if these data are on hard drive. not sure if the file mentioned above is the final one?

**Comment by Janette-Lumley** [comment]
@helendallas this one and the one saved on the hard drive are the same.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley I have worked with the one you send. Looks okay except for a few changes needed.

**Comment by helendallas** [comment]
Ready for uploading, waiting on Dimas. @helendallas to do

**Comment by helendallas** [comment]
@Janette-Lumley I have uploaded to FBIS, please can you add photos to each of the sites for the relevant dates. Thanks

[De Moor & BarberJames August 2003 Kabouga River.pdf](https://github.com/helendallas/FRC_FBIS/files/10228491
/De.Moor.BarberJames.August.2003.Kabouga.River.pdf)

**Comment by helendallas** [comment]
@Janette-Lumley Please can you check in report and photos where possible, for site and sampling date

Report is here

[Uploading De Moor & BarberJames August 2003 Kabouga River.pdf…]()

**Comment by helendallas** [comment]
Done except for Tanytarsini -  wont upload @helendallas to check

**Comment by helendallas** [comment]
Tanytarsini not uploading. Redo in the new year once Dimas has fixed uploader

**Comment by helendallas** [comment]
@Janette-Lumley Alos please check coordinates

https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221238%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by helendallas** [comment]
Tanytarsini not uploading. Redo in the new year once Dimas has fixed uploader

**Comment by helendallas** [comment]
Fixed on testing but can only upload to production once fix has been deployed

**Comment by helendallas** [comment]
Uploaded occurrence file successfully to FBIS production. Closing ticket. NB to have no spaces SubFamily, SubSpecies etc
