### ISSUE TITLE
Mangold and De Moore 1996 - Transkei rivers

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#254]
Please extract data from this report.

Table 2: List of sites and biotopes sampled for invertebrates, during the Transkei river survey, October - November 1996.

![image](https://user-images.githubusercontent.com/45286876/167120435-e2300243-1f56-4939-b8e6-e68d5129df94.png)

Tables 3 A and 3 B give family level data for all taxa.
Tables 4a to 8 give genus and species for a sub section of these families. Where genus or species are noted, do not include family.

Please check with me if unsure.

[Uploading Mangold & De Moor 1996 Rivers former Transkei Region.pdf…]()

**Comment by aneriswanepoel** [comment]
@helendallas please attach the PDF again. Looks like there was an issue with attaching the PDFs

**Comment by aneriswanepoel** [comment]
List of taxa in the study that aren't on the masterlist:

![image](https://user-images.githubusercontent.com/55532903/177719743-9691ca65-bcf0-4817-8561-11611c8cb6aa.png)

@helendallas

**Comment by aneriswanepoel** [comment]
[Mangold & De Moor 1996.xlsx](https://github.com/helendallas/FRC_FBIS/files/9061492/Mangold.De.Moor.1996.xlsx)

**Comment by helendallas** [comment]
@aneriswanepoel Please see my comments below

Afroptilum excisum -  I have added this to FBIS live, it is a synonym of Cheleocloeon excisum (Barnard, 1932), https://www.gbif.org/species/6931947

Araneidae - this is a terrestrial spider, please exclude

Chironomini -  should be Chironominae (SubFamily)

Hirudinea -  should be Hirudinidae (Family)

Neritina gagates -  added to FBIS live, synonym of Vittina gagates https://www.gbif.org/species/10343672

Poduridae - added to FBIS live

Potamonidae - I suspect this should be Potamonautidae or Potamididae??? please check

Sminthuridae - added to FBIS live

Tanytarsini - this is a tribe within SubFamily  Chironominae, I cannot add a tribe, so just add as a SubFamily


I suggest you wait until next week when the testing site is mirrored from the live site and then try and update on testing first so that you can pick up issues.

**Comment by aneriswanepoel** [comment]
@helendallas I fixed all these errors and the upload to testing was fine but when I uploaded to live, these two taxa are missing from the masterlist. So they're on testing but not live...

Acentrella monticola
Acentrella natalensis

**Comment by helendallas** [comment]
I think it best to use the accepted names for each,

Demoreptus monticola not Acentrella monticola
Demoreptus natalensis not Acentrella natalensis

also Demoreptus capensis for Acentrella capensis

I have included the old names in the taxon
Here is a useful paper, thanks

https://www.ru.ac.za/media/rhodesuniversity/resources/martin/baetidae.html

**Comment by helendallas** [comment]
@Janette-Lumley Please can you check these sites as some seem to be in Lesotho. Aneri was meant to check but not sure if she did?
https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221213%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

I will send pdf by email

Thanks

**Comment by Janette-Lumley** [comment]
@helendallas I have checked and the coordinates are correct, there is one site that is in Lesotho, the description in the pdf is "Quthing (in Lesotho)" the original site is 11 and FBIS site code is D1ORAN-00021.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley Closing ticket

**Comment by helendallas** [comment]
All fixed, closing ticket
