### ISSUE TITLE
De Moor & BarberJames 1994 Freshw. Inverts East Cape Rivers

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#255]
Table 1. List of collecting sites, with grid reference coordinates and altitudes for each site

![image](https://user-images.githubusercontent.com/45286876/167123031-d2bec186-11fa-4212-8bff-2c91bbf4bef3.png)

![image](https://user-images.githubusercontent.com/45286876/167123251-b9b2807b-6349-471f-b82b-28e2073ea42e.png)

Table 5 to 14 Taxon data

Plates - photographs for saving and uploading Please add photographs by saving from doc - ask if you are not sure

![image](https://user-images.githubusercontent.com/45286876/167124432-dcb5a630-da9a-4bea-89ce-e0a9939a0741.png)

[De Moor & BarberJames 1994 Freshw. Inverts East Cape Rivers.pdf](https://github.com/helendallas/FRC_FBIS/files/8639671/De.Moor.BarberJames.1994.Freshw.Inverts.East.Cape.Rivers.pdf)

Please check if unsure.

I suspect you will need to capture these data manually. Also then when they are uploaded to testing the coordinates need to be checked.

**Comment by Janette-Lumley** [comment]
@helendallas Do you know the dates for the sampling? In the report it states sampling was done from 3-7 December 1990, 
21-27 March 1991 and 26 March - 2 April 1993, but when I look at the tables with the recorded inverts there are no dates.
(Table 5 to 14 Taxon data)

**Comment by helendallas** [comment]
Thanks @Janette-Lumley 

So if you look at table 2, you will see that most sites were only sampled once, e.g. Site 8 was only sampled in Dec 1990. here they report the chemical data which you must also capture please. Remember EC = conductivity and it has to be divided by 10 to get mS/m

Some sites were sampled more than once, e.g. Site 2, please then just select the middle or last date for capturing the data.

I suggest you make the taxon list first. Remember to include in notes in it is a type or specie 1 etc, and then only include genus and species
Tricorythus reticulatus

I suggest you print the pages and create the tables, or it is going to be very difficult.

Before you start I am downloading the Albany Museum invert data from GBIF. We need to check that the data have not already been added here. @aneriswanepoel this applies to all Albany Museum data you have been working on as well.



You need to check that all taxa are included in the Invert master list as well once this taxon list has been created.

**Comment by Janette-Lumley** [comment]
@helendallas there are a few taxon not on the master list that I made notes in the notes column, when you get a chance could you have a look and let me know if I should delete them or not, and then if you are happy for me to upload to FBIS.

[De Moor F and Barber-James H 1994.xlsx](https://github.com/helendallas/FRC_FBIS/files/9240626/De.Moor.F.and.Barber-James.H.1994.xlsx)

**Comment by helendallas** [comment]
Thanks @Janette-Lumley 
Some comments:

Please fill in Taxon rank for all taxa, there are many blanks -  sort of taxon rank and click blank

In future, please create a list of missing taxa as a separate sheet in the file, and remove duplicates, thanks. I have added a sheet to the file on dropbox.  Please also triple check that the correct taxa have been recorded as it is easy to make mistakes given the bad table formatting etc. My comments below:

Afroptilum excisum   - added to FBIS live, please wait till next week to mirror on testing .
Antocha transvaalia - added to FBIS live,   please wait till next week to mirror on testing .
Aphididae - delete these are not aquatic
Ceciomyiidae - delete these are not   aquatic
Cemoulinia crassi - incorrect it should   be Demoulinia crassi (always double check spelling, and existence of GBIF)
Centroptiloides bifasciata - spelling   should be Centroptiloides bifasciatum
Chriptocironomus - spelling should be   Cryptochironomus
Derallus - added to FBIS live, please   wait till next week to mirror on testing .
Dolichopeza chaka - added to FBIS live,   please wait till next week to mirror on testing .
Elophorus - synonym of Helophorus (change   and make a note in notes of original name)
Eriopterini - I think it should be   Erioptera - please check
Forcipomyiinae - change to Forcipomyia
Gerrinae -  this is a subFamily of Gerridae, I cant add   it, include as Gerridae
Haemotopota -  spelling should be Haematopota
Halobatinae -  this is a subFamily of Gerridae, I cant add   it, use Family Gerridae
Hemianax - added to FBIS live, please   wait till next week to mirror on testing .
Hexatoma    - added to FBIS live, please wait till next week to mirror on testing   .
Limonia kraaiensis  - added to FBIS live, please wait till next   week to mirror on testing .
Limonini -  use Family Limoniidae
Lymnophilomyia - added to FBIS live,   please wait till next week to mirror on testing .
Micronecta dorothea - added to FBIS live,   please wait till next week to mirror on testing .
Micronecta gorogaiqua - added to FBIS   live, please wait till next week to mirror on testing .
Micronecta monomatapae - added to FBIS   live, please wait till next week to mirror on testing .
Nephrotoma edwarsi - added to FBIS live,   please wait till next week to mirror on testing .
Pelecypoda -  old name include as Class Bilvalvia
Pentaneurini -  cannot add as it is a tribe, include as   respective genera only
Physa actua -  should be Physa acuta
Tanytarsini  - this is a tribe within SubFamily   Chironominae, I cannot add a tribe, so just add as a SubFamily
Tanytarsus luctosus -  should be Tanytarsus luctuosus
Tipula -    this is already in FBIS
Tipula draconis - added to FBIS live,   please wait till next week to mirror on testing .
Virgatanytarsus ardennensis -  should be Virgatanytarsus arduennensis
Zavreliella dewulfi  - I only see Zavreliella marmorata in the   pdf? Please check dewulfi  -  it is usually Polypedilum dewulfi

**Comment by Janette-Lumley** [comment]
@helendallas I have updated the taxa according to your notes

**Comment by helendallas** [comment]
Data file checked, Ready for upload, but issues with uploader. Awaiting feedback from Dimas

**Comment by helendallas** [comment]
Data file checked, Ready for upload, but issues with uploader. Awaiting feedback from Dimas

**Comment by helendallas** [comment]
@Janette-Lumley I am uploading these data now.
Please can you add photos to these sites. You will probably need to take a screen shot. Comment on ticket when done, thanks

**Comment by helendallas** [comment]
@Janette-Lumley Please can you also double check the coordinates are all correct by checking on the map

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221194%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by Janette-Lumley** [comment]
@helendallas I have added the photos to the sites. Not all the sites had photos, these are: 
T1XUKA-00016
T1MBAS-00013
T3INXU-00021
D1INXU-00001

There are also a few issues with some sites that I couldn't save the photo's in, there is an error message saying "Invalid Site Code format":
T3POT-00007
T3POT-00008
T3POT-00009
T3POT-00010
T3POT-00005

I also checked the coordinates and the following site T1XUKA-00015 - issue with coordinates in FBIS - site not coming up

**Comment by helendallas** [comment]
Thanks @Janette-Lumley 

Please add R after POT for each. Site code must include 4 letters of river.
T3POT-00007
T3POT-00008
T3POT-00009
T3POT-00010
T3POT-00005

I have this site T1XUKA-00015 
https://freshwaterbiodiversity.org/map/#search/T1XUKA-00015/taxon=&search=T1XUKA-00015&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221194%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=&abioticData=&ecologicalCategory=&rank=&siteIdOpen=115470&dst=

**Comment by helendallas** [comment]
@Janette-Lumley Has this been finalised yet?

**Comment by Janette-Lumley** [comment]
@helendallas Yes I added the R after POT and it worked so the photos have been uploaded now.

**Comment by helendallas** [comment]
Thanks closing ticket
