### ISSUE TITLE
BarberJames 2000 Salt River September 2000 

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#256]
Please extract data from this report

A survey of the aquatic macroinvertebrates in the Salt River was undertaken from 11 to 13 August, 2000

Collecting of aquatic macroinvertebrates was done using fine-meshed hand nets.

Most sampling was done from stones-in-current, water flowing over hygropectirc regions, marginal and floating vegetation, and from pools to a lesser extent.

![image](https://user-images.githubusercontent.com/45286876/167134260-d574502b-5cab-4b8e-9f41-2d50fee15cea.png)

Approximate sites using the description and map.
![image](https://user-images.githubusercontent.com/45286876/167134431-e46b31fa-febc-4cdd-a642-2ac608ed8f12.png)

Extract photos if available
[BarberJames 2000 Salt River September 2000 .pdf](https://github.com/helendallas/FRC_FBIS/files/8640119/BarberJames.2000.Salt.River.September.2000.pdf)

**Comment by helendallas** [comment]
Note De Moor et al 2004 have coordinates for some of the sites.
https://github.com/helendallas/FRC_FBIS/issues/257

**Comment by Janette-Lumley** [comment]
@helendallas I have extracted the data from this report, there is one taxon not in the master list that I have highlighted in red

**Comment by helendallas** [comment]
@Janette-Lumley 
Please double check using the printed list and fix up some families that are noted as Order. Then also maybe double check the taxa are in the correct sites. And pls change date to 11 Aug 2000, not 1 Aug 2000.

**Comment by Janette-Lumley** [comment]
@helendallas I have fixed up all the families that were entered as order and double checked the correct sites and changed the date. The one taxa that is not in the master list is Salpingidae.
[BarberJames 2000 Salt River September 2000.xlsx](https://github.com/helendallas/FRC_FBIS/files/11016154/BarberJames.2000.Salt.River.September.2000.xlsx)

**Comment by helendallas** [comment]
Salpingidae added, data checked ready to upload to FBIS Production

**Comment by helendallas** [comment]
Uploaded to Production.
