### ISSUE TITLE
De Moor et al 2004 -  Salt river

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#257]
Please extract data from this report. Same sites as 
https://github.com/helendallas/FRC_FBIS/issues/256

This survey (April 2004) follows previous surveys carried out by the Albany Museum during the winter/early spring season (Barber-James 2000) and summer (de Moor & Barber-James 2001). Another survey of relevance is that conducted by Bok (2000) of the fish fauna in the region.

Sampling was limited to four sites (S4, S6, 57 and the lower section of S8), the former three sites corresponding to those with the same numbers from previous surveys (Fig. 1).

Mixed biotopes, mixed sampling method.

Table 1 and 2: Physico-chemistry
Tables 3,4,5 SASS data
Table 7 to 16. Please extract data for April 2004, and then if feasible also add for 2000 surveys.

Lets go through together to figure out what makes sense.

Extract photos from plates

Tables 7 to 

Tables 1 to 18,
Plates for photos

**Comment by Janette-Lumley** [comment]
@helendallas please could you send this report to me, I can't find it on dropbox.
Thanks.

**Comment by Janette-Lumley** [comment]
@helendallas I have entered the data in the report. There are two taxon that are not in the Master list: Paractenelmis and Tanytarsini.
[De Moor et al 2004.xlsx](https://github.com/helendallas/FRC_FBIS/files/11200531/De.Moor.et.al.2004.xlsx)

**Comment by helendallas** [comment]
@Janette-Lumley the attached file seems to be the same as the Barber-James 2000. PLease check thanks

**Comment by Janette-Lumley** [comment]
@helendallas I have removed the few duplicates that are also in Barber-James 2000
[De Moor et al 2004.xlsx](https://github.com/helendallas/FRC_FBIS/files/11232831/De.Moor.et.al.2004.xlsx)

**Comment by helendallas** [comment]
@Janette-Lumley  Please extract sites for BarberJames 2000 Salt River, so that same FBIS Site codes are used where the sites are the same. Please check both pdfs to confirm then add the FBIS Site Code.

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221240%22]&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=

Also there seem to be some duplicates. Please check the extra column that I added where I concatenated some fields. Red ones are duplicates.

**Comment by helendallas** [comment]
Here is the file to work from please
[De Moor et al 2004 Salt.xlsx](https://github.com/helendallas/FRC_FBIS/files/11233626/De.Moor.et.al.2004.Salt.xlsx)

**Comment by helendallas** [comment]
@Janette-Lumley Please also make a note to add photographs once I have uploaded the data.

**Comment by Janette-Lumley** [comment]
@helendallas I have fixed the duplicates and added the relevant FBIS site codes.

[De.Moor.et.al.2004.Salt.xlsx](https://github.com/helendallas/FRC_FBIS/files/11248835/De.Moor.et.al.2004.Salt.xlsx)

**Comment by helendallas** [comment]
Uploaded to FBIS
