### ISSUE TITLE
BarberJames & De Moor 1995 Survey Mpofana lions river

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#258]
Please extract data from this report:

Invertebrate samples were collected by staff of Umgeni Waters from two sites along the Nlpot-ana River (March 1995) and from two sites on the Lions River (Juty 1995) (Fig' 1; Table i).

![image](https://user-images.githubusercontent.com/45286876/167139806-802c7d62-4425-4099-8fc1-59e8398f33fb.png)

![image](https://user-images.githubusercontent.com/45286876/167139783-bff266cc-dd2b-4a4a-bfbd-863efa055bbb.png)

Include for all sites if possible including Mooi River

![image](https://user-images.githubusercontent.com/45286876/167139974-8a824b98-6010-4f46-96dc-d111ff1cfcee.png)

We might need to chat about sites??
[BarberJames & De Moor 1995 Survey Mpofana lions river.pdf](https://github.com/helendallas/FRC_FBIS/files/8640318/BarberJames.De.Moor.1995.Survey.Mpofana.lions.river.pdf)

**Comment by Janette-Lumley** [comment]
@helendallas when you get a chance could you have a look, there are a few taxon that weren't in the master list, I made notes on those in the notes column, then let me know if you are happy for me to upload to FBIS.

[Barber-James H and De Moor F 1995.xlsx](https://github.com/helendallas/FRC_FBIS/files/9240246/Barber-James.H.and.De.Moor.F.1995.xlsx)

**Comment by helendallas** [comment]
@Janette-Lumley I have gone through the taxa and included a sheet in the excel file, also recorded here:

Afroptilum excisum | Added to FBIS live, - Cheleocloeon excisum   please wait till next week to mirror on testing .
Afroptilum falcatum | Added to FBIS - Cheleocloeon falcatum
Afroptilum flavum | Added to FBIS - CRASSABWA flavum
Afroptilum indusii | Added to FBIS - Dabulamanzia indusii
Afroptilum medium | Added to FBIS - Dabulamanzia medium
Aphididae | Aphididae - delete these are not aquatic
Aranaeida | Araneidae - this is a terrestrial spider, please exclude
Atrichopogon hirsutipennis | Added to FBIS live, please wait till next week to mirror on testing .
Caridina | This is already in FBIS
Centroptiloides bifasciatum | Centroptiloides bifasciata - spelling should be Centroptiloides   bifasciatum
Chironomus palistris | Spelling : Chironomus palustris - Added to FBIS
Cryptochironomus coronatus | - spelling should be   Cryptochironomus
Eucyclops eucanthus | Taxonomy doubtful - delete
Helichus | Added to FBIS
Helobdella scutifera | Just add as Helobdella as species is doubtful
Limnebius | Added to FBIS
Limnothricidae | Delete - cannot find taxon anywhere
Megasternum | Added to FBIS
Paracyclops finitinius | Spelling - Paracyclops finitimus -    added to FBIS
Paragordius | Added to FBIS
Pentaneura appendiculatus | Cannot find taxon - suggest just record as Pentaneura
Pentaneura tinctoria | Cannot find taxon - suggest just record as Pentaneura
Planaria | Added to FBIS
Poduridae | Added to FBIS
Renatra | Spelling - should be Ranatra - is in FBIS
Scirtes | Added to FBIS
Tanytarsus furcus | Cannot find taxon - suggest just record as Tanytarsus (combine with   other)
Tetragnatha | delete these are not aquatic

**Comment by Janette-Lumley** [comment]
@helendallas I have updated the taxa according to your notes

**Comment by helendallas** [comment]
Ready for uploading, awaiting fixes from Dimas

**Comment by helendallas** [comment]
All uploaded to testing except SubSpecies Pseudagrion spernatum natalense
To check next year once Dimas has reverted.

**Comment by helendallas** [comment]
@Janette-Lumley 
Please can you add photos to these sites. You will probably need to take a screen shot. Comment on ticket when done, thanks

**Comment by helendallas** [comment]
@Janette-Lumley alos please check coordinates

https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221193%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by helendallas** [comment]
All uploaded to testing except SubSpecies Pseudagrion spernatum natalense
To check next year once Dimas has reverted.

**Comment by Janette-Lumley** [comment]
@helendallas the coordinates have been checked, there are no photo's in this report.

**Comment by helendallas** [comment]
Added Pseudagrion spernatum natalense, Data uploaded to production

**Comment by helendallas** [comment]
@helendallas Please check all taxa from hard copy before uploading. Checked , called Pseudogrion ?natalensis in report. Correct name is Pseudagrion spernatum natalense.

Uploaded to FBIS Production. Closing ticket
