### ISSUE TITLE
De Moor 2002 

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#259]
Please check these data have not already been captured via one of De Moor's other studies. e.g #252 

![image](https://user-images.githubusercontent.com/45286876/167358009-e9075317-2f9a-4fe7-8b84-d9df29c78ccc.png)

Here is the pdf
[De Moor 2002 Trichoptera SILAustralia.pdf](https://github.com/helendallas/FRC_FBIS/files/8649470/De.Moor.2002.Trichoptera.SILAustralia.pdf)

**Comment by aneriswanepoel** [comment]
@helendallas again can't use this data as results are too vague - not site or date specific.
