### ISSUE TITLE
Wolmarans C.T., Kemp M., de Kock K.N. & Wepener V.  2017

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#263]
Please extract mollusc data, using the map and tables provided.
![image](https://user-images.githubusercontent.com/45286876/167385346-78763cdf-717e-4ae4-983e-ff90c44161da.png)

![image](https://user-images.githubusercontent.com/45286876/167385413-77bc56a3-38cb-42e8-b57e-30890992bfaa.png)

![image](https://user-images.githubusercontent.com/45286876/167385452-9739fe77-56d2-455a-b4f2-763121f6ba81.png)

[Wolmarans C.T., Kemp M., de Kock K.N. & Wepener V.  2017.pdf](https://github.com/helendallas/FRC_FBIS/files/8650574/Wolmarans.C.T.Kemp.M.de.Kock.K.N.Wepener.V.2017.pdf)

**Comment by Janette-Lumley** [comment]
@helendallas The paper you attached here was not the mollusc data it is invert data for the same sites. The 1st page is the title of the mollusc paper but you will see if you scroll to the next page it is actually "The possible association between selected sediment characteristics and the occurrence of benthic macroinvertebrates in a minimally affected river in South Africa"

The mollusc data is already in FBIS but I have captured the invert data from this paper and uploaded the spreadsheet on dropbox.

**Comment by helendallas** [comment]
Uploaded to FBIS, @helendallas still need to check before closing ticket

**Comment by helendallas** [comment]
Data file checked, Ready for upload, but issues with uploader. Awaiting feedback from Dimas

**Comment by helendallas** [comment]
Issue with existing site codes on FBIS testing and FBIS production. Waiting for Dimas to get back to me

**Comment by helendallas** [comment]
Uploaded but created new sites instead on tagging onto existing sites in FBIS. Closing ticket now
