### ISSUE TITLE
Vallidate sites you have created

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#266]
@aneriswanepoel Please can you vlaidate the sites you ahve created.

Always add the Original Rive name and teh Refined geomorphological name if available

e.g. here are sites of Sharon Pollard
https://freshwaterbiodiversity.org/nonvalidated-site/?owner=Sharon%20Pollard

https://freshwaterbiodiversity.org/nonvalidated-site/

Also found here: Admin dropdown - Validate sites

Only do the ones you added, and double check they are in the correct location, and have all required data. If there are photos, upload them to the site or even better to the sampling date

**Comment by aneriswanepoel** [comment]
@helendallas okay will do
