### ISSUE TITLE
Add sampling options to Algal data entry template/page

### ISSUE THREAD

**Issue by KSnaddon** [helendallas/FRC_FBIS#267]
Need to add:
1. Sampling: add "Water column - grab" to sampling options
2. Curation: add "Preserved - formaldehyde" as an option, plus be able to choose multiple options, and give detail in notes.

@helendallas

**Comment by KSnaddon** [comment]
@helendallas, can we add a wetland-specific algal sampling method to the data upload template now, so that we can upload the TMG wetland algal data by end of May 2023?  This is "sediment sample", which covers all types of sediment sampling techniques (cores, scrapes, plots etc).

**Comment by helendallas** [comment]
@KSnaddon 

I have added in extra sampling methods and curation as detailed above. New upload template is on dropbox.

Generic Data Upload Template with latest dropdowns 2023_05_24

I have added to your dropbox folder as well

**Comment by KSnaddon** [comment]
Thanks!
