### ISSUE TITLE
Sabie River Algal data - Erasmus 2018

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#268]
Literature search result
Need to update Sampling Method and Curation Process
Need to update collector for all sites
Some taxa missing from FBIS

**Comment by helendallas** [comment]
Data extracted from FBIS, have PDF, but cannot find upload file

**Comment by helendallas** [comment]
@Janette-Lumley Please cna you check that all the data has been correctly added by Aneri., and photos if available

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221187%22]&endemic=&conservationStatus=[]&modules=22&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=

**Comment by helendallas** [comment]
@Janette-Lumley Please let me know when completed, thanks

**Comment by Janette-Lumley** [comment]
@helendallas the data has been checked and is correct.

**Comment by helendallas** [comment]
Thanks
