### ISSUE TITLE
Taxonomic Backbone issue - If a new species is added not on the master lists.

### ISSUE THREAD

**Issue by toniolsen** [helendallas/FRC_FBIS#27]
We need to give some thought into the process that needs to happen if someone adds a new species that is not currently in our master lists (and Github). Suggestion: A prompt to the uploader that they are uploading a new species. All taxonomic data for this new species will need to be added by the uploader. (Will we need a new form for this?)

@helendallas @jeremyshelton @philipfrenzel

**Comment by jeremyshelton** [comment]
@toniolsen that sounds like a good idea to me. We would just need to check with Dimas if its easy for that new taxon to then join the existing master list in the FBIS. 
@helendallas would we need to have a verification check when a user adds a new species?
...I suspect we will need a form.

**Comment by helendallas** [comment]
Issue resolved, ticket closed
