### ISSUE TITLE
Algal data - Phungula 2018

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#270]
Literature search for algal data in KNP area

**Comment by aneriswanepoel** [comment]
Some algal taxa missing; added to spreadsheet.

**Comment by helendallas** [comment]
Data extracted from FBIS, have PDF, but cannot find upload file

**Comment by helendallas** [comment]
@Janette-Lumley Please check if Aneri has added all the data correctly, including photographs if available

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221190%22]&endemic=&conservationStatus=[]&modules=22&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=

**Comment by Janette-Lumley** [comment]
@helendallas the data has been added correctly and the sites have photos. 
Two site codes have been duplicated but with different data:
A6NYLR-00003 - 2 sites with the same name and different data
A6NYLR-00002 - 3 sites with the same name and different data
Do we need to merge them?

**Comment by helendallas** [comment]
The first site
A6NYLR-00003 - there are only occurrences at one site - second one has zero occurrences.
<img width="713" alt="Screenshot 2023-09-19 at 14 53 16" src="https://github.com/helendallas/FRC_FBIS/assets/45286876/d96fabf5-bc7b-4646-bd07-77a39c8441a5">

Second site: A6NYLR-00002

Only first site has occurrence data. Can you check the descriptions of 1 and 3.

<img width="658" alt="Screenshot 2023-09-19 at 14 56 51" src="https://github.com/helendallas/FRC_FBIS/assets/45286876/356fe628-acad-43fe-9458-382bbfaa6566">

I think Azeri must of created more than one site ?????

Once you confirm you agree, I will delete the sites with no occurrence records. Thanks

**Comment by helendallas** [comment]
its very strange to have duplicate sites....must be a bug????

**Comment by Janette-Lumley** [comment]
@helendallas this is very strange, when I go into those sites I get different results with occurences in all sites:

![image](https://github.com/helendallas/FRC_FBIS/assets/55576335/50a4662c-d8f2-403e-ba36-3810bb2cddeb)
![image](https://github.com/helendallas/FRC_FBIS/assets/55576335/f7b7dd0d-8b32-45c8-a772-04d361f4b578)

**Comment by helendallas** [comment]
@Janette-Lumley Please can you check these again on testing. Here is the link. Dimas said it has been fixed

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221190%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=

**Comment by helendallas** [comment]
sorry above link was wrong. try this one please

https://testing.healthyrivers.kartoza.com/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221190%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by Janette-Lumley** [comment]
@helendallas yes there is only one of each sites now on the testing. Not sure if some data relating to those sites has been removed though because for example in site A6NYLR-00002 originally one of them had 18 occurances of algae data and on the second site 26 occurances of invert data. Now on the testing there is just 26 occurances of invert data and no algae so it doesnt come up with that source reference anymore, if you remove the source reference you will see the site with invert data linked.

**Comment by helendallas** [comment]
But the Phungule study only had algal data right. Can you check against the actual data, thanks

The invert data was for a different study so now has its own code as they are slightly different coordinates

**Comment by Janette-Lumley** [comment]
@helendallas yes so basically the algae data for A6NYLR-00002 has suddenly dissapeared completely whereas before there were 18 occurances of algae data.

**Comment by helendallas** [comment]
Ok, but did you check this again the pdf

**Comment by helendallas** [comment]
or rather against the xls. Forget about the site code. It may have change to something else. You need to check that all the data are in from this spreadsheet, regardless of the site code.
[Phungula 2018.xlsx](https://github.com/helendallas/FRC_FBIS/files/12748340/Phungula.2018.xlsx)

**Comment by Janette-Lumley** [comment]
Oh ok so the code changed to A6NYLR-00180. I don't think the excel spreadsheet is the correct one but I have checked the data now on testing against the live site as well as the pdf and all looks good.

**Comment by helendallas** [comment]
Brilliant thanks. As long as the data are all still there :) and no sites are missing, then I can close the ticket

**Comment by Janette-Lumley** [comment]
:) Yes it is all still there so you can close the ticket.  Thanks.
