### ISSUE TITLE
2. Frogs - various

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#273]
Google scholar results for frog data. Various studies. Combining all into one spreadsheet as datasets are not large.

**Comment by helendallas** [comment]
@aneriswanepoel to provide xls and csv file in AWARD BioSmart folder for data curation

**Comment by helendallas** [comment]
Uploaded and checked. Closing now, as data curation will be undertaken by @aneriswanepoel
