### ISSUE TITLE
3. Dyamond - KNP Wetland Inverts

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#276]
Literature search 
Missing taxa in spreadsheet:

https://www.dropbox.com/s/eaaptjsx83f1w3p/Invertebrate%20Template%20-%20wetland%20inverts.xlsx?dl=0

@helendallas

**Comment by helendallas** [comment]
Checked @aneriswanepoel 

Notes in spreadsheet and here

Hirudinea | make Hirudinea - Family
Naboandelus africanus | Added to FBIS
Africasia radiata | Cannot find anywhere - check for spelling?
Ephydra | Added to FBIS
Barborophilus | Spelling - should be Borborophilus -    already in FBIS
Halobates | Added to FBIS
Leptoconops | Added to FBIS
Neumania | Added to FBIS
Phyllomacromia | Spelling  - Phyllomacromi - it is   in FBIS

**Comment by aneriswanepoel** [comment]
@helendallas not sure what happened to the taxa you added to FBIS but I can't find these on FBIS...:
Hirudinea
Ephydra
Halobates
Neumania

**Comment by helendallas** [comment]
sorry typo or did in a hurry so forgto to add to FBIS, just added to master list -  all in now to live, so will be available on testing next week from monday

![image](https://user-images.githubusercontent.com/45286876/185417343-58c8d472-4ba9-4f45-aefc-bc18e72d42c8.png)

![image](https://user-images.githubusercontent.com/45286876/185417949-940b91b9-566e-4890-9637-67bce6647e77.png)

![image](https://user-images.githubusercontent.com/45286876/185418244-238e5e86-efa3-46ae-ba00-f8b4c8441495.png)

![image](https://user-images.githubusercontent.com/45286876/185418477-f334ba13-171e-48be-8291-3d8387250bde.png)

**Comment by helendallas** [comment]
Uploaded and checked.
