### ISSUE TITLE
8. KNP Wetland Algae - Kock 2017

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#277]

**Comment by helendallas** [comment]
@aneriswanepoel Again some details please

**Comment by helendallas** [comment]
Not finding data - might be the same issue as we had with missing records.

https://freshwaterbiodiversity.org/map/#search//taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221214%22]&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

Please make a note @aneriswanepoel to check again once Dimas has fixed the missing records issue. Thanks

**Comment by aneriswanepoel** [comment]
@helendallas I think it's because there are two source references for some reason - one with records and one without:

![image](https://user-images.githubusercontent.com/55532903/188103200-1559a4ae-deef-4e98-b3ba-d58443e727fb.png)

**Comment by aneriswanepoel** [comment]
North-West University Masters thesis, found on Google scholar.
