### ISSUE TITLE
7. KNP Wetland Algae - WRC Report

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#278]
Literature search result.

**Comment by helendallas** [comment]
@aneriswanepoel Please give more details of what this is and what has been done, thanks Especially Source reference so that we can find data on FBIS

**Comment by aneriswanepoel** [comment]
Assessment of ecological integrity of Zaalklapspruit wetland in Mpumalanga (before and after rehabilitation). Data added directly to FBIS.

**Comment by helendallas** [comment]
@aneriswanepoel Please provide full citation including author

**Comment by helendallas** [comment]
Not to worry I have added is
Oberholster PJ 2016. Assessment of the ecological integrity of the Zaalklapspruit wetland. Water Research Commission Report No. 2230/2/16
