### ISSUE TITLE
6. Baker - Nylsvley inverts

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#279]
Literature search

**Comment by aneriswanepoel** [comment]
Taxa not on masterlist:

Dicranomyia   capicola
Dicranomyia tipulipes
Hydra oligactis
Hydrachna
Leptocerinae
Radix natalensis
Schoenobiinae
Stratiomys
Teinobasis
Tipula pomposa
Trianodes
Tricholeichiton

@helendallas

**Comment by helendallas** [comment]
Completed

Dicranomyia   capicola | Added to FBIS live
Dicranomyia tipulipes | Added to FBIS live
Hydra oligactis | Added to FBIS live
Hydrachna | Added to FBIS live
Leptocerinae | Change to Leptocerina (Genus)
Radix natalensis | Added to FBIS live
Schoenobiinae | Include as Crambidae (Family)
Stratiomys | Added to FBIS live
Teinobasis | Added to FBIS live
Tipula pomposa | Added to FBIS live
Trianodes | Should be Triaenodes
Tricholeichiton | Should be Tricholeiochiton -  I have added to FBIS
