### ISSUE TITLE
Uniform form mock up for all modules

### ISSUE THREAD

**Issue by toniolsen** [helendallas/FRC_FBIS#28]
Hi @helendallas, @jeremyshelton, @philipfrenzel 
Here is the form I mocked up that could be used to upload data for all modules:

[Form_All modules.pdf](https://github.com/helendallas/FRC_FBIS/files/3642251/Form_All.modules.pdf)
[Form_All modules.docx](https://github.com/helendallas/FRC_FBIS/files/3642256/Form_All.modules.docx)

Please comment and let me know if I can ticket it to present to Kartoza on Wednesday.
Note: I have left dropdown options blank and can fill in once we have decided on the ones to use. This is just the skeleton for the form.

**Comment by jeremyshelton** [comment]
Looking good @toniolsen

A few comments/questions:  

1. I wonder if we need a heading below 'Owner' called 'Sampling details' or something like that? @helendallas ?  
@jeremyshelton @toniolsen what would one include here?  A general comments field is always handy but don't think it needs to be specific.

2. Should the 'Taxon Rank' column not come before 'Taxa' column? @helendallas  @jeremyshelton @toniolsen - No I think Taxon first then taxon rank

3. Some notes for the 'Biomass (Algae only)' section:
- looks like sampling location has the drop-down meant for sampling method?
- sample curation needs an indication that there will be a dropdown
- AI is the ratio of AFDM:Chl a, so should this be auto-populated if the user enters vales for AFDM and Chloroformed a @philipfrenzel ?

4. Do we need to decide which field are mandatory and which are not?  @jeremyshelton @toniolsen - yes, this needs some thought

**Comment by helendallas** [comment]
@toniolsen 
Are these also on dropbox folder?  
Form_All modules.pdf
Form_All modules.docx

**Comment by helendallas** [comment]
@toniolsen  found them

**Comment by philipfrenzel** [comment]
Hi @toniolsen @jeremyshelton @helendallas 

Apologies for only getting to these tickets now. Been away for at the SER conference and then fieldwork. I will work through these comments systematically now - sorry if the comments come in a little bit late.

Re the Biomass (algae only section):
- Point 1+2: agreed @jeremyshelton 
- Point 3: There may be value in making the AI ratio automated, however, I am a bit cautious for two reasons: i) in the instance when only one of the two biomass values has been calculated, an undefined value may appear in the AI cell, or ii) if several replicates of both biomass indicators were taken at a site (in this instance, adding an average Chl A, AFDM and AI would be more valuable than an average of all the AFDM:Chl A ratios for the AI value). Does this make sense @jeremyshelton @helendallas ?

**Comment by jeremyshelton** [comment]
OK thanks @philipfrenzel 
So you reckon no auto populate for AI, rather manual entry - that correct?

**Comment by philipfrenzel** [comment]
I think a manual entry would be best, yes @jeremyshelton

**Comment by jeremyshelton** [comment]
Cool.

**Comment by helendallas** [comment]
Issue resolved, ticket closed
