### ISSUE TITLE
Check data owned by J Lumley

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#280]
There are several sites that have J Lumley as the owner. This cannot be the case and I am assuming that you added the data. It is SASS data.

Please check these data and provide the correct SASS assessor and source reference. Lets chat if you cannot resolve.

https://freshwaterbiodiversity.org/sass/dashboard-multi-sites/?taxon=&search=&siteId=&collector=%5B%22Janette%20Lumley%22%5D&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&abioticData=&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&thermalModule=&dst=

**Comment by Janette-Lumley** [comment]
@helendallas this was strange because when I went into the SASS entries on FBIS the owner column was blank. The sites were owned by Ian Bailey, so I added him as the owner of the SASS data for those sites, there was no other data associated with them, only SASS.

**Comment by helendallas** [comment]
Thanks , looks good, closing ticket
