### ISSUE TITLE
Check data owned by A Swanepoel

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#281]
Please check these sites: In the csv file Aneri is the owner. Please ask her or check with Kate who is the correct owner of the sites/site visits. and change.

H6AMAN-00024 -2/23/2021
H6DUTO-00055 - 3/26/2009

**Comment by Janette-Lumley** [comment]
@helendallas I have checked these two and both are owned by Kate.

**Comment by helendallas** [comment]
Thanks, closing ticket
