### ISSUE TITLE
RIversMoore and Hill 2018 Blackfly data Orange river

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#288]
Please can you add biological data into an occurrence upload xls file

Sites are already in FBIS, so you need to use those in the pivot table tab of the attached file. 

I need an average per species site per sampling date (so you need to first add larvae and pupae), then calculate an average

Lets check when I am in the office.

Here is the file: use the Edited data sheet

[Blackfly species vs variables_complete.xlsx](https://github.com/helendallas/FRC_FBIS/files/10898598/Blackfly.species.vs.variables_complete.xlsx)

**Comment by helendallas** [comment]
here is the paper as well for the extra info needed

[River Research Apps - 2018 - Rivers%E2%80%90Moore - A predictive management tool for blackfly outbreaks on the Orange River .pdf](https://github.com/helendallas/FRC_FBIS/files/10898680/River.Research.Apps.-.2018.-.Rivers.E2.80.90Moore.-.A.predictive.management.tool.for.blackfly.outbreaks.on.the.Orange.River.pdf)

**Comment by Janette-Lumley** [comment]
@helendallas I have entered in the data from the paper. I entered the averages as requested.
[Rivers-Moore and Hill 2018.xlsx](https://github.com/helendallas/FRC_FBIS/files/11200565/Rivers-Moore.and.Hill.2018.xlsx)

**Comment by helendallas** [comment]
@Janette-Lumley I picked up two duplicates, for one of the sites, in red in last column. Pls can you check that this is not a data capture error. 

Please work on attached file as I have updated it.

[Rivers-Moore.and.Hill.2018.xlsx](https://github.com/helendallas/FRC_FBIS/files/11233938/Rivers-Moore.and.Hill.2018.xlsx)

**Comment by Janette-Lumley** [comment]
@helendallas I had entered the incorrect date for the one duplicate, it should've been March not July.
I have fixed it now.
[Rivers-Moore.and.Hill.2018.xlsx](https://github.com/helendallas/FRC_FBIS/files/11247900/Rivers-Moore.and.Hill.2018.xlsx)

**Comment by helendallas** [comment]
Issue with biological data and water temp sites not matching. Checking
D3ORAN-00094 Douglas - no WT data
D7ORAN-00165 Prieska
D7ORAN-00166 Gifkloof
D7ORAN-00167  Uppington
D7ORAN-00168 On edge of river upstream of railway bridge
D7ORAN-00169 Site 6_Druiswater
D7ORAN-00170 Kanoneiland 
D7ORAN-00171 Upstream of Keimos, downstream of Uppington
D7ORAN-00172 Upstream of Keimos, downstream of Uppington
D7ORAN-00173 Upstream of Keimoas
D7ORAN-00174 At R27 road bridge
D8ORAN-00232 Below Augrabies Falls

I need to check these once Dimas has got back to me re data and sites

**Comment by helendallas** [comment]
Sites problematic and problem with water temp sites being different . @helendallas needs to check once Dimas has got back to her

**Comment by helendallas** [comment]
Checked all correct, closing ticket
