### ISSUE TITLE
Looking for PDFs 

### ISSUE THREAD

**Issue by toniolsen** [helendallas/FRC_FBIS#29]
Hi @Janette-Lumley and @Aneri16, 

I have started uploading PDFs and copying the link to all the invertebrate species data in the "Data to combine" folder on Dropbox.
I am just missing two PDFs that you may have.

1.) The published report : Snaddon, K., Ractcliffe, G., and Ewart-Smith, J., 2014. @Janette-Lumley, I think you captured this data?
2.) The thesis: Tharme, R., 2010. @Aneri16 you captured this data?

Could you please let me know if you have these PDFs and send them to me? You can email them through or post them here. 
Thanks!

**Comment by helendallas** [comment]
@toniolsen @Aneri16 @Janette-Lumley 
Please keep a note of what is done please, did you get these docs Toni?

Also please dont close any issues. Just move them do done.

**Comment by aneriswanepoel** [comment]
I emailed the Tharme paper to Toni

**Comment by toniolsen** [comment]
I received both documents. Thanks!
