### ISSUE TITLE
SASS data - De Moor et al Salt River April 2004 Survey 

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#292]
Please add SASS data to the relevant site once the invert data has been uploaded and the site has an FBIS Site Code. 

Use the data in the SASS sheets in the report.
Tables 3, 4 and 5.

[De Moor et al Salt River April 2004 Survey .pdf](https://github.com/helendallas/FRC_FBIS/files/11234006/De.Moor.et.al.Salt.River.April.2004.Survey.pdf)

**Comment by helendallas** [comment]
Thanks @Janette-Lumley I assume this is all the data for the sites?

**Comment by Janette-Lumley** [comment]
@helendallas in the pdf there were only 3 tables with SASS data, tables 3,4 and 5 (site 4,6 and 7) that were added to FBIS.
