### ISSUE TITLE
Wetland Plant data from SANBI

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#295]
The Plant data set is here.

[Wetland_Plant_data_2023_11_08_nj_Edited HD.xlsx](https://github.com/helendallas/FRC_FBIS/files/13459169/Wetland_Plant_data_2023_11_08_nj_Edited.HD.xlsx)

There a re still several issues that need fixing before it can be uploaded to FBIS.

Including 
 

- Most are Ecosystem type = Wetland, but 32 are blank -  please check
- Some Latitudes are not – (negative) – please check
- About 30 sites do not have latitude/longitudes – these cannot be uploaded and need to be deleted -  please check
- Sampling date can only be in this format: yyyy/mm/dd . If it is not it will not upload. Several need to be corrected. -  please check; many of these don’t want to change when I change the formatting so may need to be captured manually again.
- Taxon rank is missing for two thirds of the data – it will not upload if this is blank I have added these
- Present always needs to be “1” to reflect it was present. I have added this
- Author(s) -  needs to be blank as this is a Database. The collector is captured separately. I have deleted this
- There is a second Sampling date with just the year.  I assume this is meant to be Year as per the upload template. This is the year of the database………not the collection date. It can be blank I have deleted this
- About 20 records do not have source reference specified. This should be added as SANBI BRAHMS Database I have added this
- About 20 records do not have reference category specified. -This should be added as database I have added this

@NancyFreshwater Please can you fix and send back soonest

**Comment by NancyFreshwater** [comment]
Thanks! Will follow up this weekend

**Comment by helendallas** [comment]
Comments via email. Added here for the record.

NJ: Re loading the data on to fbis, starting with the 10 000 entries, do you have a sense of how long this will take? Hlengiwe can no longer do this task, so it either falls to me, or we can look to the two invoices to reallocate from last years one to your team if someone can do this.
 
HD: Can I suggest we get someone to help from FRC – and look at reallocated last years SANBI funds. Here are the issues again I identified that need to be resolved before we can upload the data.

@KSnaddon has agreed to take this on. The relevant file is attached above. As mentioned, Points 1 to 4 need attending to, I have done the remainder. @NancyFreshwater Please can you confirm that this is the most recent version of the dataset.

**Comment by KSnaddon** [comment]
@NancyFreshwater I have a few more queries please:
1. What does this sampling date mean - 0-0-0 
2. And these - 0-1-0, 0-10-0, 1830-10-0
3. Some rows are highlighted in orange - most seem to be sub-species, but not all - what does this mean?

**Comment by KSnaddon** [comment]
@helendallas Updated plant occurrence list has been sent to you by Nancy. Nancy is still adding common plants to ML Excel spreadsheet, using information solicited from plant community. 

@NancyFreshwater will speak to Helen / Kate about how / when to update ML on FBIS.

**Comment by helendallas** [comment]
@KSnaddon @NancyFreshwater 

I spent today working o this and am currently uploading to testing. Sampling dates were a problem and needed to be revised.

Please don't edit this dataset now. You can begin a new dataset with new data received.

Thanks

**Comment by helendallas** [comment]
@NancyFreshwater I have edited and uploaded the plant dataset - some issues below, which I have taken the liberty of fixing so that we can have the data in the FBIS. 269 records did not upload.

1. Two occurrence records had a date of  1982/02/31 -  this is incorrect since there are only 28 days in Feb. I have changed to 1982/02/28

3. Several taxa did not exist on the master list for various reason

Adenostemma caffrum - the GBIF link was for the Adenostemma caffrum subsp. caffrum DC. instead of the Adenostemma caffrum DC. I have updated GBIF link in master file and in taxon management - done

Aeschynomene uniflora - Updated occurrence data to to Aeschynomene uniflora uniflora - variety not species -  Aeschynomene uniflora uniflora is a synonym of Aeschynomene uniflora. Both included.

Amauropelta bergiana bergiana -  the GBIF link was for Amauropelta bergiana (Schltdl.) Holttum - updated GBIF link in master list and in taxon managemen to Amauropelta bergiana var. bergiana (Schltdl.) Holttum, 1974 - Done

Askidiosperma albo-aristatum corrected to Askidiosperma alboaristatum in occurrence data -  Done

Atriplex vestita appendiculata changed to variety in occurrence data - Done

Atriplex vestita inappendiculata changed to variety in occurrence data - Done

Blechnum capense. -unknown issue, I will try again - Done

Calamagrostis epigejos capensis changed to variety in occurrence data - Done, only in sites with no sampling dates

Didymochlaena truncatula. -unknown issue, I will try again - Done

Fimbristylis dichotoma dichotoma - was species in Taxon management, changed to subspecies -  Done

Ixianthes retzioides - incorrect GBIF link on master list - update -  Done

Kniphofia ichopensis ichopensis - changed to variety in occurrence data -  Done

Nymphaea nouchali caerulea- changed to variety in occurrence data - Done

Ophioglossum lancifolium. -missing from master list - added -  Done

Panicum coloratum coloratum - GBIF link was Panicum coloratum - updated GBIF link in master list and in taxon management. changed to variety in occurrence data -  Done

Pycreus polystachyos polystachyos - GBIF link was Pycreus polystachyos - updated GBIF link in master list and in taxon management. -Chnaged to Variety - Done

I have updated these on FBIS Production - and now I need production to sync to testing.
Then I will check on Monday if these uploaded correctly.


4. The occurrence records with 0/0/0 all not upload. I had to change them to 1900/00/00 but then graphically this looks strange and gives a false impression of substantial sampling in 1900, or whatever random here we allocate these data.
 New Comment: I have extracted these into a separate file. SANBI Brahms Database_No Sampling Dates



![Screenshot 2024-03-01 at 14 35 11](https://github.com/helendallas/FRC_FBIS/assets/45286876/b263ddb3-1eb7-4e76-bd94-21fb9cb78c1a)

I recommend that we delete these records for now. If you can find a date later then they can be added as a new dataset

[SANBI Brahms Database_No Sampling Dates.xlsx](https://github.com/helendallas/FRC_FBIS/files/14478767/SANBI.Brahms.Database_No.Sampling.Dates.xlsx)

**Comment by helendallas** [comment]
@NancyFreshwater @KSnaddon I have managed to upload the plant data onto FBIS production. 9339 occurrence records

Here is the link:

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=37&validated=&sourceCollection=[%22fbis%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified


The final corrected upload file is on dropbox in the wetlands folder - Module - Plants - Data Sets and here.

**Wetland_Plant_data_Uploaded_2024_03_04 Excluding No Dates.xslx**

The remaining records with no dates have been excluded.

**SANBI Brahms Database_No Sampling Dates.xlsx**

[Wetland_Plant_data_Uploaded_2024_03_04 Excluding No Dates.xlsx](https://github.com/helendallas/FRC_FBIS/files/14496161/Wetland_Plant_data_Uploaded_2024_03_04.Excluding.No.Dates.xlsx)

[SANBI Brahms Database_No Sampling Dates.xlsx](https://github.com/helendallas/FRC_FBIS/files/14496167/SANBI.Brahms.Database_No.Sampling.Dates.xlsx)

**Comment by helendallas** [comment]
Completed, so closing ticket
