### ISSUE TITLE
Holmes, M., & Taylor, J. C. (2015) Great Fish River, Eastern Cape, South Africa

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#296]
Please format the data for uploading

Details in excel file
[Holmes & Taylor 2015 Diatoms  Great Fish River.xlsx](https://github.com/helendallas/FRC_FBIS/files/14050723/Holmes.Taylor.2015.Diatoms.Great.Fish.River.xlsx)

File added to you dropbox Janette folder as well

**Comment by Janette-Lumley** [comment]
@helendallas this data has been entered, I just need to do the final checks and the document upload link

**Comment by Janette-Lumley** [comment]
@helendallas This data has been entered into the upload template. @KSnaddon is adding the taxa that wasn't on the algae master list and is also checking the data against the pdf.

**Comment by helendallas** [comment]
@Janette-Lumley Please add latest data file here

**Comment by KSnaddon** [comment]
@helendallas & @Janette-Lumley - just FYI - I tried to upload the data, but there is still a long list of taxa not on the Master List (in addition to the list that Janette shared), so I just need to add these too.

**Comment by KSnaddon** [comment]
Final successful upload csv:

[Holmes and Taylor 2015 FINAL.csv](https://github.com/user-attachments/files/16639021/Holmes.and.Taylor.2015.FINAL.csv)
