### ISSUE TITLE
Holmes, M., Campbell, E. E., de Wit, M., & Taylor, J. C. (2022) GFR

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#297]
[Holmes, M., Campbell, E. E., de Wit, M., & Taylor, J. C. (2022) GFR.xlsx](https://github.com/helendallas/FRC_FBIS/files/14050750/Holmes.M.Campbell.E.E.de.Wit.M.Taylor.J.C.2022.GFR.xlsx)

Please prepare data

File added to you dropbox Janette folder as well

**Comment by helendallas** [comment]
@Janette-Lumley Please always add a comment so that I know where the file is and that it is ready for me to look at . thanks

**Comment by Janette-Lumley** [comment]
@helendallas I have saved the file to "Janette only/Holmes Algae/Holmes and Taylor captured data" I just still need to do some final checks.

**Comment by Janette-Lumley** [comment]
@helendallas all the data has been entered I just need to add the document upload link

**Comment by Janette-Lumley** [comment]
@helendallas  This data has been entered into the upload template. @KSnaddon  is adding the taxa that wasn't on the algae master list and is also checking the data against the pdf.

**Comment by helendallas** [comment]
@Janette-Lumley Please add latest data file here

**Comment by KSnaddon** [comment]
Final successful upload csv:

[Holmes M et al 2022 FINAL_HD.csv](https://github.com/user-attachments/files/16639025/Holmes.M.et.al.2022.FINAL_HD.csv)
