### ISSUE TITLE
SASS Data - FCG

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#3]
Awaiting feedback from Justine Ewart-Smith re data

**Comment by helendallas** [comment]
@toniolsen 
Please move to **Done** column if this is completed

**Comment by helendallas** [comment]
@toniolsen 
Please confirm that all this data is captured into FBIS. With Justine Ewart-Smith the Data Owner

**Comment by toniolsen** [comment]
@helendallas, 
@Janette-Lumley definitely captured this data, but now it is not on the system? Justine has sites in FBIS, but it does not correspond to the data that we entered. 
@Janette-Lumley, can you please confirm that this data below was captured into FBIS:
[CFR Invertebrate SASS Data for FBIS_FCG.xlsx](https://github.com/helendallas/FRC_FBIS/files/3635619/CFR.Invertebrate.SASS.Data.for.FBIS_FCG.xlsx)
I think it was one of the first SASS datasheets that you entered.

**Comment by helendallas** [comment]
@toniolsen 
Please can you add this data onto FBIS, and check it is all there.

Also take the opportunity to add the correc Reference Source, it is not Rivers Database

**Comment by toniolsen** [comment]
@Janette-Lumley is capturing this data:
[CFR Invertebrate SASS Data Bulk Import Template.xlsx](https://github.com/helendallas/FRC_FBIS/files/3639695/CFR.Invertebrate.SASS.Data.Bulk.Import.Template.xlsx)

It includes Justine's data from a published report and Chantel Petersen's data from her thesis. Christa Thirion's data is also in this spreadsheet (highlighted in grey), but does not need to be captured as I already did this.
Thanks!

**Comment by helendallas** [comment]
@Janette-Lumley 
Please can we sit with this data and use the revised spreadsheet, which is easier. Shout when you are ready to enter it.

**Comment by Janette-Lumley** [comment]
@helendallas The FCG SASS data was entered in according to the green highlighted data: Dropbox: Data for consolidation > Invertebrate Data > CFR Invertebrate data SASS > Data > SASS Data FCG and C Petersen_transformed to enter

**Comment by Janette-Lumley** [comment]
@helendallas I just need to change the Reference source, it says Rivers Database. Could you please let me know what the correct Report is to upload and enter.

**Comment by Janette-Lumley** [comment]
@helendallas I found the report on the JRS external hard drive, so I have uploaded it and corrected the reference from Rivers database to the published report.

**Comment by helendallas** [comment]
Thanks @Janette-Lumley 
Please just confirm with Justine that she is happy for the report to be visible on FBIS. If not we can change to unpublished data

**Comment by helendallas** [comment]
@Janette-Lumley 

Have you checked with Justine about adding this report? Please follow up and revert

**Comment by Janette-Lumley** [comment]
@helendallas 
Yes I called Justine and she said it shouldn't be a problem.

**Comment by helendallas** [comment]
@Janette-Lumley 
Please check study reference for all sites and dates: This one is still wrong:

![Screenshot_2020-03-24 FBIS SASS(2)](https://user-images.githubusercontent.com/45286876/77426788-e24b3100-6ddd-11ea-86b2-aaeef7df2b87.png)

Also check which data are associated with which report...there are two. See below:
[Ewart-Smith, J. 2017. Assessment of the Groot River, Meiringspoort First report.pdf](https://github.com/helendallas/FRC_FBIS/files/4375306/Ewart-Smith.J.2017.Assessment.of.the.Groot.River.Meiringspoort.First.report.pdf)

[Ewart-Smith, J. 2018. Assessment of the Groot River, Meiringspoort Second Report.pdf](https://github.com/helendallas/FRC_FBIS/files/4375311/Ewart-Smith.J.2018.Assessment.of.the.Groot.River.Meiringspoort.Second.Report.pdf)

Also the other data: must be associated with a different report. Please can you follow up with Justine to see if there are reports associated with these data. 

2)      Huis rivier has sites upstream and downstream of a weir, the SASS and ASPT were similar
3)      Kars, Nuwejars, Lourens etc (impacts not known)
4)      Trout farms (SmalUp1 was upstream of a trout farm, with the rest of the sites below it) Smal – smalblaar river, duToit and bridge = molenaars,

First check data - if it is not obvious then lets forget about this data and once you ahve checked on above, we cna close the ticket.

**Comment by Janette-Lumley** [comment]
@helendallas I have checked and changed the study references. 
The spreadsheet that I received was for the 2017 report. Can I enter the 2018 report data?
I have also emailed Justine with regard to the other report and awaiting her reply.

**Comment by helendallas** [comment]
@Janette-Lumley If and when you get the extra data and report, then go ahead and add it. The important criterion is to ensure the correct Site Codes, Rivers and sampling dates , with associated SASS and wq data, are from the correct report, as reflected in the study reference.

**Comment by Janette-Lumley** [comment]
**Copy of emails:**

Hi Janette
Please check that all Justine’s Meiringspoort sites are linked to this document…I thought there were more than 2 - Helen

 
Hi Helen,
I went through this again this week, the original spreadsheet that Toni gave me had only that document name as per your email below, but there are actually 2 other reports. I have attached the spreadsheet that hopefully will make sense. I have added the correct report name at the top (highlighted in blue), the original name is highlighted in yellow. The FBIS site codes are in green. So I will need to add those two other reports to FBIS and then go into the SASS data and correct the study references accordingly.

But yes you are correct, there should be more than 2 sites linked to that study reference as it stands now, Each of the site codes on the spreadsheet should be linked to that document, not only the 2 as per the search result below.

I have also just added the two other reports to the dropbox folder: FRC_FBIS Data for 
Consolidation\Data for Consolidation\Invertebrate Data\CFR Invertebrate data SASS\Data\FCG

The 2018 report hasn’t been captured yet. - Janette

**Comment by Janette-Lumley** [comment]
@helendallas I have uploaded all the other reports and linked them to the correct SASS data. I also captured the SASS data from the 2018 report. There were a few errors in the excel spreadsheet that Toni sent me when I compared the data to the reports so I have made all the necessary corrections.

**Comment by helendallas** [comment]
@Janette-Lumley Thanks so much!
