### ISSUE TITLE
Uploading PDFs for theses and published reports

### ISSUE THREAD

**Issue by toniolsen** [helendallas/FRC_FBIS#30]
Hi @Janette-Lumley, @Aneri16 @philipfrenzel 

I just wanted to share the process of uploading PDFS to the document management page so if you extract data from a published report or thesis (only) you can upload the PDF and then copy the link into the "Document Upload Link" column. Obviously for all peer-reviewed papers we must try get the DOI.

First go to this address: http://freshwaterbiodiversity.org/documents
Then follow these steps:
![Screenshot 2019-09-25 at 11 52 44](https://user-images.githubusercontent.com/43198125/65595477-cd0b5c00-df8c-11e9-9d92-442c9fc87796.png)
![Screenshot 2019-09-25 at 11 52 57](https://user-images.githubusercontent.com/43198125/65595497-d7c5f100-df8c-11e9-949a-5a09927030a4.png)

When filling in the name of the document please look at the other document title formats already in the document management. E.g for theses: Name, year, title, degree, university.
For published reports: Name, year, title, report number.

![Screenshot 2019-09-25 at 11 55 49](https://user-images.githubusercontent.com/43198125/65595504-dbf20e80-df8c-11e9-8a07-d18b75f346ec.png)
![Screenshot 2019-09-25 at 11 56 02](https://user-images.githubusercontent.com/43198125/65595506-deecff00-df8c-11e9-9561-cc293d9b9bdb.png)
![Screenshot 2019-09-25 at 11 56 16](https://user-images.githubusercontent.com/43198125/65596397-ac440600-df8e-11e9-9145-50f13eed39c2.png)

Then copy the link in the address bar to the document upload link column (this link should end in a number) and drag down for all records that come from that specific document. Be sure to check that the numbers do not change when you drag down. 

Please note: I have added all the document links for all the invertebrate species data in the "data to combine" folder as well as for all the national fish data. (Besides the fish data that we are waiting on from Mo). These final files are on Dropbox, so just be careful not to overwrite these copies with the document links in them. Thanks! Let me know if anything is unclear.

**Comment by aneriswanepoel** [comment]
@philipfrenzel here you go! 
Just shout if anything is unclear. And remember the title of the report should be in the format shown in this example (the Snaddon et al report). 
The link at the end of the process that should be copied onto your spreadsheet in the Document Upload Link column will look something like this: 
https://freshwaterbiodiversity.org/documents/205 (you will have a different end number though)

**Comment by helendallas** [comment]
UPdate on documents unploading:
@Janette-Lumley @Aneri16 

The document authors, date, title etc need to be added to the **Edit BIMS Document**

BIMS
![image](https://user-images.githubusercontent.com/45286876/86903796-1db10780-c110-11ea-9cb2-c9b76f8e87ee.png)

![image](https://user-images.githubusercontent.com/45286876/86903831-27d30600-c110-11ea-94fd-64a1a69b8eae.png)

To have the document visible on the dropdown list for source reference, you need to add:

For current solution, you need to add `Bims source reference` in the free-text keywords field : 
 
![image](https://user-images.githubusercontent.com/45286876/86903724-08d47400-c110-11ea-92d1-9987c265dd6d.png)

This will be automated in the future, but for now please add.
