### ISSUE TITLE
Integrate Invasive plant species from Julie Coetzee?? Rhodes

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#301]
We need to integrate species on the invasive list with our Plant Master list, and format for FBIS.

@NancyFreshwater Please can you add the list here or share link with us on the GitHub ticket.

@KSnaddon Can you please check this and integrate as needed.

Further discussion is needed on the actual data. Should we be getting in touch with Julie again ? Nancy.

**Comment by KSnaddon** [comment]
@helendallas I have the list from Nancy and have started editing and re-arranging the data.  I will show it to you ASAP.

**Comment by KSnaddon** [comment]
@helendallas Just FYI - I am adding ecosystem type to the invasives data - half way through.  I have deleted all records that have either (1) no species (this is where they went to a site, and the species was no longer there, but still recorded as a line), or (2) no co-ordinates.

**Comment by KSnaddon** [comment]
@helendallas and @NancyFreshwater - I have completed checking and editing the Julie Coetzee database. 

[Occurrence_Upload_Coetzee_Data_9 April 2024.xlsx](https://github.com/helendallas/FRC_FBIS/files/14918874/Occurrence_Upload_Coetzee_Data_9.April.2024.xlsx)

I'm still just checking a few things, and still need to add the areal cover data.  @helendallas - would you like to check the file before I finalise?

@NancyFreshwater - do we have permission to upload the data, and is there a particular report to link it to?  At the moment, it is recorded as Julie Coetzee's database, with her Institution being Rhodes University.  Is there anything more to add / refine?

**Comment by helendallas** [comment]
Thanks @KSnaddon 

I would like to check through the file tomorrow, then first upload to testing to check all is uploading correctly.

**Comment by KSnaddon** [comment]
Perfect, thanks.

**Comment by NancyFreshwater** [comment]
Thanks so much Helen and Kate! Wonderful, please go ahead and lets let
Julie know. I can email and cc you both letting her know it was ypu that
did all the work

**Comment by helendallas** [comment]
@KSnaddon I uploaded to testing, some taxa not in master list (or haven't pulled from production)

![Screenshot 2024-04-10 at 13 36 39](https://github.com/helendallas/FRC_FBIS/assets/45286876/2996ce81-ff42-4f30-875c-f1386c8528ac)


Here is link to data that did upload





https://testing.healthyrivers.kartoza.com/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=%5B%221288%22%5D&endemic=&conservationStatus=%5B%5D&modules=37&validated=&sourceCollection=%5B%22fbis%22,%22gbif%22,%22virtual_museum%22%5D&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

**Comment by KSnaddon** [comment]
That's strange, as they appear if I search for them:
![image](https://github.com/helendallas/FRC_FBIS/assets/91128958/d7fd854c-84ba-46f6-8695-2f95f89bd051)

**Comment by KSnaddon** [comment]
@helendallas The data are ready for upload to Production, once you have the final word from Julie.

**Comment by KSnaddon** [comment]
@helendallas These data have now been successfully uploaded to the Production Site.  

[success_Occurrence_Upload_Coetzee_Data_8_May_2024.csv](https://github.com/helendallas/FRC_FBIS/files/15259922/success_Occurrence_Upload_Coetzee_Data_8_May_2024.csv)

**Comment by NancyFreshwater** [comment]
Thanks will pick up on this tomorrow

**Comment by helendallas** [comment]
Thanks @KSnaddon looks good.

@NancyFreshwater Here is the link to the data

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=[%22Julie%20Coetzee%22]&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=37&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=&ecosystemType=River,Wetland,Open%20waterbody,Unspecified

I will close this ticket now.
