### ISSUE TITLE
Variety vs Sub species

### ISSUE THREAD

**Issue by KSnaddon** [helendallas/FRC_FBIS#302]
@helendallas Some of the plant taxa have been entered onto the Master List as a "Variety", whereas this is not a drop-down option when  compiling a bulk occurrence records upload.  Variety is, however, an option if you "Add a taxon" manually from Taxon Management.  

Which should it be?  I feel like we've had this discussion before, but I can't recall the outcome!

**Comment by helendallas** [comment]
@KSnaddon Yes, we did discuss before. Since then I have requested that Dimas add variety and forma as options for uploading data. This came asa request from SANParks as well.
