### ISSUE TITLE
Invertebrate Taxon Data - Barbara Stewart PhD

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#31]
@philipfrenzel 
Extract data from PhD thesis and follow up with Iziko museum -  Albe Bosman for catalogued data - if required

**Comment by helendallas** [comment]
@philipfrenzel 

Template to use is on dropbox:
https://www.dropbox.com/s/szmdjeuj4lrpudo/Invertebrate%20Taxon%20Template%202019_10_03.xlsx?dl=0

[Invertebrate Taxon Template 2019_10_03.xlsx](https://github.com/helendallas/FRC_FBIS/files/3696189/Invertebrate.Taxon.Template.2019_10_03.xlsx)


Please discuss with Janette or Aneri if you are unclear.

**Comment by helendallas** [comment]
@Aneri16 I am reassigning this to you. Perhaps get hold of Philip to see where he got with this and what still needs to happen. 
It would also be worth checking on GBIF is these data are already there, as we don't want to duplicate.

**Comment by Aneri16** [comment]
@helendallas 
I am just finalizing this data now and just have a question re a river name. Most of the co-ordinates given are vague so I have been looking on the FBIS map to find the more accurate co-ordinates. One river is the Burgersbos River (crossing Rhodes Drive, Constantia, co-ords given are : -34,01667 S and 18,4167 E). Does this river maybe have a different name now?

**Comment by aneriswanepoel** [comment]
I have finished this data extraction, just need to add UUIDs. Folder is on Dropbox: 
C:\Users\User\Dropbox\FRC_FBIS Data for Consolidation\Data for Consolidation\Invertebrate Data\CFR Invertebrate data Species\Final for FBISv4 -> Stewart, B.A. 1991

**Comment by helendallas** [comment]
@Aneri16 Thanks. Th Burgerspos looks to be an unnamed tributary, so happy to leave as is. 
Please just make sure the sampling date is in the correct format: yyyy/mm/dd

Then you can combine with the consolidated file, and check the taxonomy

**Comment by aneriswanepoel** [comment]
@helendallas okay have combined it and checked taxonomy and all looks okay
