### ISSUE TITLE
SASS Data - Liz Day

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#32]
Check all SASS data owned by Liz Day and for those SASS assessments where there are no abundances, please make A. Include a note in the comments section as per previous edits.

![Screenshot_2019-09-30 FBIS Map](https://user-images.githubusercontent.com/45286876/65860352-66aa8300-e36a-11e9-9f3f-878223a69718.png)

**Comment by aneriswanepoel** [comment]
@helendallas what must I compare the SASS data against? Do you have the SASS sheets?

**Comment by aneriswanepoel** [comment]
Temporarily hit pause with this data capture while FBIS bugs are being sorted out

**Comment by aneriswanepoel** [comment]
@helendallas 
SASS data capture is complete but biotope ratings not filled in
