### ISSUE TITLE
SASS Data - Dallas Palmiet and Molenaars River

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#34]
Check SASS data for Dallas 1997 (Dallas 1995)
Four sites on the Palmiet River
Two sites on the Molenaars River

Correct sampling Dates
Add biotope ratings (see on datasheets) HD has added
Check taxa
Change Reference Source to:
Peer-reviewed Scientific Article
DOI: 10.1080/10183469.1997.9631389

Add in Notes;
Dallas, H.F. 1995. An evaluation of SASS (South African Scoring System) as a tool for the rapid bioassessment of water quality. Master of Science Thesis, Department of Zoology, University of Cape Town.

**Comment by aneriswanepoel** [comment]
@helendallas 
H1MOLE-DETOI not on FBIS - must be added

**Comment by helendallas** [comment]
@Aneri16 
I have added the site so now you cna add the SASS data

**Comment by aneriswanepoel** [comment]
@helendallas 
Thanks, I have just completed this SASS data capture now
