### ISSUE TITLE
SASS Data - Bonado & Dallas 2006

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#35]
Please add SASS data for these sites. Site information, SASS data and abiotic data given in excel sheet.  Some sites are new, so create Site first, other just need a new date added. (if data already exist then please just check for accuracy)

Make all abundance = A and make a note in the notes column.
All sites sampled in October 2001

[Bonada et al 2006_JNABS25(2).pdf](https://github.com/helendallas/FRC_FBIS/files/3676828/Bonada.et.al.2006_JNABS25.2.pdf)
[Bonada et al 2006 Sass and abiotic data.xlsx](https://github.com/helendallas/FRC_FBIS/files/3676829/Bonada.et.al.2006.Sass.and.abiotic.data.xlsx)

PDF of study attached.
DOI

**Comment by aneriswanepoel** [comment]
@helendallas 
FBIS is not recognizing the DOI when I try to add it on the Source Reference page so I am unable to proceed with uploading SASS data... For now I am going to make the reference Unpublished Data and will correct it once we have sorted out the DOI issue

**Comment by aneriswanepoel** [comment]
@helendallas 
SASS data has been captured so moving to "Done" column but need to remember to come back and correct the DOI/reference once Kartoza has fixed it

**Comment by helendallas** [comment]
@Aneri16 
Please check if this has been resolved or not. If not please alert me so I can escalate the ticket for Dimas to fix.

**Comment by aneriswanepoel** [comment]
@helendallas 
Busy checking this now

**Comment by aneriswanepoel** [comment]
@helendallas 
Okay all checked and updated. DOI now recognized correctly
