### ISSUE TITLE
Invertebrate Taxon Data - Bruce Eady Msc 2011

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#36]
Figure 3.1: Study area, showing the paired sample sites from each river system.

No Site descriptions, but please see if you can find some details in the thesis or papers. Or email Nick to ask (He was Bruce's supervisor).

[B Eady 2011 Study Site information.xlsx](https://github.com/helendallas/FRC_FBIS/files/3676931/B.Eady.2011.Study.Site.information.xlsx)

Data in thesis (and papers)
[Eady B.R. 2011.pdf](https://github.com/helendallas/FRC_FBIS/files/3676940/Eady.B.R.2011.pdf)
[Eady B.R., Hill T.R. & Rivers-Moore N.A. 2014.pdf](https://github.com/helendallas/FRC_FBIS/files/3676941/Eady.B.R.Hill.T.R.Rivers-Moore.N.A.2014.pdf)
[Uploading Eady B.R., Rivers-Moore N.A. & Hill T.R. 2013.pdf…]()

Macroinvertebrate data in 
APPENDIX D: Total macroinvertebrate taxa per season

abiotic data in 
APPENDIX C: Water quality variables for each site per season

**Comment by helendallas** [comment]
@Janette-Lumley  How is this going?

**Comment by Janette-Lumley** [comment]
@helendallas 

I emailed Nick for site descriptions, but there wasn't much I could find from what he sent me. I added what I could find. Let me know when you have some time to have a look. Thanks

**Comment by helendallas** [comment]
@Janette-Lumley 
Please fix the dates. They need to be yyyy/mm/dd
Add in Refined Geomorphological zone - same as Longitudinal zone in his table. 
Change collector/Owner format to : First name Surname, so Bruce Eady
Change Author(s) to correct format: Eady BR
Title -dont put fullstop at end.

This is now standard.

**Comment by Janette-Lumley** [comment]
@helendallas I have added the Refined Geomorphological zone, Aneri had already fixed the dates and name formats this morning.

**Comment by helendallas** [comment]
@Aneri16 @Janette-Lumley Thanks
