### ISSUE TITLE
SASS Data - Le Roux 2013 Holsloot River

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#38]
Extract SASS data from MSc thesis:

Site details on Page 39
Table 3: General information per sampling site

Sample dates: pg 42
see appendix

Appendix 3 SASS5-Data recorded in the 2011-2012 for all Sampling Sites - standard
data sheets (Dallas 2005).

Thesis is very large - please get from JRS hard drive.

**Comment by aneriswanepoel** [comment]
Temporarily hit pause with this data capture while FBIS bugs are being sorted out

**Comment by helendallas** [comment]
@Aneri16 
I have created usernames: 
Anso_LeRoux
Ntswaki_Ditlhale

Please see if this is now working.

**Comment by helendallas** [comment]
Checked. Somethings strange is happening with Site Ownership. But I will need to check further.
