### ISSUE TITLE
Invertebrate Taxon data - Vere Ross-Gillespie

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#40]
Please extract data for three species in six study rivers in PhD thesis and add to ad hoc sheet.

Lestagella penicillata (Ephemeroptera), Aphanicercella spp. (Plecoptera) and Chimarra ambulans
(Trichoptera),

Sites: pg 24

Tables 2.1, 2.2 and 2.3.Physical and geographical information (2.1), geomorphological characteristics (2.2) and channel morphology characteristics (2.3) pertaining to the six study rivers
selected for life-history analyses from the Western Cape, South Africa.

and Table 3.1. Site locality information for specimens of Lestagella penicillata, Aphanicercella spp. and Chimarra ambulans collected for genetic analysis.

Just record present, as abundances not relevant.

Field sampling page 86
4.2.2 Field sampling - kick net

Thesis too large to upload, please get from computer knowledge database

Abiotic

extract relevant data from:
Table 4.1. Summary of important environmental and physico-chemical variables associated with each of the study sites

Reference: 

Ross-Gillespie   V. | 2014 | Effects of   water temperature on life-history traits of selected South African aquatic   insects. | PhD thesis.   Zoology Department. University of Cape Town, South Africa

**Comment by Janette-Lumley** [comment]
@helendallas please email Vere for the water chemistry data, I only have the graphs. Thanks.

**Comment by helendallas** [comment]
@Janette-Lumley Email sent 202_01_21

**Comment by Janette-Lumley** [comment]
@helendallas I have added the data to the ad hoc spreadsheet without the water chemistry data, I also couldn't find any site descriptions.
