### ISSUE TITLE
Algal Data - Petersen thesis

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#42]
@philipfrenzel 
Please extract data from Chantel Petesens thesis - see 

Appendix 4.3 Algal taxa sampled March 204-March 2016.
K1 – K4 = Sites. The relative abundance of each algal taxa was grouped into: 1 = ≤ 50 (rare) 2 = 51- 250 (scarce), 3 = 251-1000 (common), 4 = 1001-5000 (abundant), 5 = 5001-25 000 (predominant) cells/ 5cm2. S = Summer, W = Winter, A = Autumn, Sp = Spring

Also Benthic
Chl-a in appendix 4.1

Janette has created sites already so make sure you use the same Site Codes
@Janette-Lumley 

Janette can give you the thesis for details.  Thesis is on the JRS hard drive.

**Comment by helendallas** [comment]
@philipfrenzel Please confirm this is done so I can close the ticket.

**Comment by philipfrenzel** [comment]
@helendallas  Yes, this is done. I'll close it with this reply.
