### ISSUE TITLE
Algal Data - Ractliffe Various studies

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#47]
@philipfrenzel 

Please scour the JRS hard drive and report of Geordie Ractliffe and extract periphyton data.

**Comment by aneriswanepoel** [comment]
@helendallas 
I have finished going through the files - only two studies extracted. The rest are wetland studies or have no co-ordinates..will add the file with new algal data to Dropbox

**Comment by helendallas** [comment]
@Aneri16 Thanks. Please add link to dropbox folder:
https://www.dropbox.com/sh/a25z08smji231b5/AACPs_isC1W8c9gjmddzuD-Za?dl=0

Any new algal data you track down can be added to this file. Please also make sure that all the columns match the last data file:
https://www.dropbox.com/s/44eema6w72tbzs7/SA%20Algal%20Data%20For%20FBISV3_13%20May%202020.xlsx?dl=0

And that all taxa match the master list.
[SA Algal Master list FBISv3_13 May 2020.xlsx](https://github.com/helendallas/FRC_FBIS/files/4715667/SA.Algal.Master.list.FBISv3_13.May.2020.xlsx)

Shout if you questions
