### ISSUE TITLE
Invertebrate Taxon Data - Snaddon 1998 MSc

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#50]
@Janette-Lumley 

Please check the Taxon column. Your have order and Family combined. It should be the highest taxonomic level.

e.g.
Plecoptera Notonemouridae
Should be **Notonemouridae**

**Comment by helendallas** [comment]
@Janette-Lumley 

I was checking the taxa on FBIS and was surprised that Kate had included Crustacea as a taxon, so I went to check the data in her thesis. Then I have found quite a few errors in this data set unfortunately.

![image](https://github.com/helendallas/FRC_FBIS/assets/45286876/d9feed68-d59d-46d9-ae33-5141302df206)


For example: These data are entered as Crustacea when they should be Cladocera. 133, 233 and 314400

Please can you go through all the data and check what else is incorrect. I may need to delete the whole study reference if there is a lot. If not you can manually update. I will have to show you how.

Thanks

files are here on you Janette dropbox folder called **For re checking**

https://www.dropbox.com/sh/j76v7gg110zn7gn/AAA672kMprPvFJITrvxX0qJxa?dl=0

**Comment by Janette-Lumley** [comment]
@helendallas I have fixed the data, the file is in the folder "For re checking"
There is one taxon that is not in the master list (Hymenoptera)

**Comment by helendallas** [comment]
To upload to production

**Comment by helendallas** [comment]
Uploaded, @Janette-Lumley Please double check all looks okay. I ended up combining larvae and adults as we havent included life stages. I know we had them separate for some other studies, but I think it is better to combine.

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%221262%22]&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=

**Comment by Janette-Lumley** [comment]
@helendallas the data seems to have doubled up for example:
BR2 Baetidae = 7 occurrences in the spreadsheet but there are 14 in FBIS. I have checked quite a lot and it is the same for all of them.

**Comment by helendallas** [comment]
Checked data again and all looks fine. closing ticket
