### ISSUE TITLE
Invertebrate Taxon Data - Snaddon BRBM 2009

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#51]
@Janette-Lumley @Aneri16 

I think you both had a hand in consolidating this data. 

I have found a few issues with the Number of replicates and biotopes. I have created a new file which I have allocated Broad, Specific and Substratum for each Site_Sampling Date.  Please check and overwrite existing data with this.

Also there should really be any replicates as far as I can tell.

Snaddon 2009 BRMP Revised Datasheet.xlsx
[Snaddon 2009 BRMP Revised Datasheet.xlsx](https://github.com/helendallas/FRC_FBIS/files/3690275/Snaddon.2009.BRMP.Revised.Datasheet.xlsx)

Please can you go through each Site_Sampling Date and check the Presence and Biotopes.

Here is the new Data To Combine file. Also in dropbox folder.
[Snaddon, K. 2009 New 2019_10_03.xlsx](https://github.com/helendallas/FRC_FBIS/files/3690278/Snaddon.K.2009.New.2019_10_03.xlsx)

**Comment by helendallas** [comment]
@Janette-Lumley 

Please can you indicate the status of this within this ticket, thanks

**Comment by Janette-Lumley** [comment]
@helendallas 
The broad, specific and substratum biotopes have been changed according to what you added in the datasheet. Please check the number of replicates with me to let me know if they are correct or not. Thanks.
