### ISSUE TITLE
SASS Data - TMGA

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#52]
@Janette-Lumley 

Please can you capture the SASS data in the spreadsheets:

SASS Data TMGA_EPM1.xlsx
SASS data TMGA_EPM2.xlsb

https://www.dropbox.com/sh/ye07anvookzp46p/AAAiwMyK3o4tiwyDssQiRpPba?dl=0

The Site Codes, Site descriptions and georeferences should be the same as for the TMGA Invertebrate Taxon Data.

I have emailed Kate re Biotope ratings and to find out who did each SASS assessment. As well as associated DO, EC, pH and temp data?

**Comment by helendallas** [comment]
@Janette-Lumley Please update me on this

**Comment by Janette-Lumley** [comment]
@helendallas I can start on this next week, it would also be a good way to test the system. I will keep you updated.

**Comment by helendallas** [comment]
@Janette-Lumley @Aneri16 
As per our chat today Janette, once Aneri is done consolidating invert data and you are done with Brown etc., can we have a google chat, with working through the data flow adding to FBIS. The TMGA sites should mostly exist, although there may be extras from EMP1.  Excel file here gives Original Site Code, FBIS Site Code and Sampling date - all needed to ensure the data are added to the correct site and date.

Janette will co-ordinate ho data are divided.

[TMGA Sites and dates.xlsx](https://github.com/helendallas/FRC_FBIS/files/4819411/TMGA.Sites.and.dates.xlsx)

**Comment by aneriswanepoel** [comment]
I will get started on this

**Comment by aneriswanepoel** [comment]
@helendallas I have reached the end of the first batch of SASS data (TMGA_EPM1). However stuck on the last bit of data - SASS data was collected for a site called K_4_Dwars channel but I cannot find the corresponding FBIS site code or any other details for that site

**Comment by Janette-Lumley** [comment]
Hi @Aneri16 I found a sheet with the FBIS site codes and for K4 it is G4LOUW-00014

**Comment by Janette-Lumley** [comment]
@helendallas  This is complete.  The data for EMP1 was entered by Aneri and I entered the data from EMP2.

**Comment by helendallas** [comment]
@Janette-Lumley @Aneri16 
Thanks that's awesome, I will close ticket.
