### ISSUE TITLE
Invertebrate Taxon Data - TMGA 

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#53]
@Janette-Lumley 

Please check what happened to the missing Taxon (Genus and Species) data for all data.

New file:
Snaddon, K., Ractliffe, G. & Ewart-Smith, J., 2014 New 2019_10_03.xlsx

**Comment by Janette-Lumley** [comment]
@helendallas I have sent Kate an email with regards to missing site description, I will fill it in as soon as I received it. All other data has been fixed.

**Comment by Janette-Lumley** [comment]
@helendallas I have added the Genus and species data and taken out the subfamily data. I have also added the site descriptions according to what Kate sent us.

There was some missing data (Specific Biotope and Substratum) so I have gone through the reports and filled in as much as I could find. 

The new spreadsheet is on dropbox data to combine folder: Snaddon, K., Ractliffe, G. & Ewart-Smith, J., 2014 New

**Comment by helendallas** [comment]
@Janette-Lumley 
thanks very much!

**Comment by helendallas** [comment]
@helendallas 
to check river names - -some are strange
