### ISSUE TITLE
Invertebrate Taxon Data - Tharme 2010

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#54]
@Aneri16 

Please can you put the electronic data in the FBIS data - Tharme 2010 folder on dropbox.

I need to go through and check spreadsheet with the original data thanks.

**Comment by helendallas** [comment]
This data also has crustacea. I cannot match with the original data. Need to do more detective work

**Comment by helendallas** [comment]
@Janette-Lumley Please can you see what has gone wrong here . You will need to extract a csv file of all the data, then find the correct datasheets in the folder I added to Janette (FBIS data - R. Tharme). **I extracted the csv data. Added to folder.**

Please read Rebecca's thesis to understand what she did. Hard copy on shelf.

The Stone samples family consolidated seems to be what Aneri generated and used but I cant match to data per sampling data.

Each site was sampled multiple times, each site had a control and Pre-Impact sample, for three biotopes (stones in current -  riffle and run, stones out of current -pool).  Then there were multiple stones sampled per biotope, which I asked Aneri to get an average from. 

Please have a look and see what you can pick up.

Thanks

https://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=[%22384%22]&endemic=&conservationStatus=[]&modules=21&validated=&sourceCollection=[%22fbis%22,%22gbif%22,%22virtual_museum%22]&module=occurrence&ecologicalCategory=&rank=&siteIdOpen=&orderBy=name&polygon=&dst=

**Comment by Janette-Lumley** [comment]
@helendallas I have gone through this data and the FBIS data matches the pilot study data as well as Stone samples family consolidated data. I have highlighted one site (Elands) for easy reference.

**Comment by helendallas** [comment]
Ok thanks, closing ticket
