### ISSUE TITLE
SASS Data - Ollis 2005 MSc

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#56]
@Aneri16 
Please extract SASS data from Dean Ollis's MSc.  Lourens, Palmiet and Hout Bay Rivers
Dean will be the SASS Data Owner

Most Sites should exist already in FBIS. See Chapter 2 tables and maps for study site details. 
Sampling dates on page 66.

SASS Data:
Page 134.
APPENDIX 2.6: MACROINVERTEBRATE TAXA COLLECTED. Use the biotope code to assign taxa per biotope. Use abundance = A, since no abundances are given, and make a note.

[Ollis DJ 2005. MSc SASS.pdf](https://github.com/helendallas/FRC_FBIS/files/3696361/Ollis.DJ.2005.MSc.SASS.pdf)

**Comment by aneriswanepoel** [comment]
Assigned to @Janette-Lumley

**Comment by Janette-Lumley** [comment]
@helendallas I have entered the data with abundances. Dean found the excel spreadsheet with all the data and sent it to me.

**Comment by helendallas** [comment]
@Janette-Lumley Thanks. So there are 13 sites. Just checking you added study reference as it doesnt come up in the search filter

**Comment by Janette-Lumley** [comment]
@helendallas yes the study reference is: Ollis, D.J., 2005, Rapid bioassessment of the ecological integrity of the Lourens, Palmiet and Hout Bay rivers (South Western Cape, South Africa) using aquatic macroinvertebrates

I also tried to search for it in the filter but it didn't come up, but if you go to the SASS dashboard for a site and then to a SASS data record you can see the reference there.
