### ISSUE TITLE
Invertebrate Taxon data - Mirimin et al 2015

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#57]
@Aneri16 
Please can you extract presence data for the shrimp and ad to the FBIS ad hoc file:

https://www.dropbox.com/s/heibw5d006uwbov/FBIS%20Adhoc%20Data%20New%202019_10_03.xlsx?dl=0

FBIS Adhoc Data New 2019_10_03.xlsx

Table1 gives sampling sites, you can include them all.

**Comment by helendallas** [comment]
[Mirimin L., Kitchin N., Impson D.N., Clark P.F., Richard J., Daniels S.R. & Roodt-Wilding R. 2015.pdf](https://github.com/helendallas/FRC_FBIS/files/3696815/Mirimin.L.Kitchin.N.Impson.D.N.Clark.P.F.Richard.J.Daniels.S.R.Roodt-Wilding.R.2015.pdf)

**Comment by helendallas** [comment]
@Aneri16 
Did you capture data from this? There is no record in the ad hoc sheet on dropbox

**Comment by aneriswanepoel** [comment]
@helendallas 
Yes data was captured - I have highlighted in yellow for you. At bottom of sheet.

**Comment by helendallas** [comment]
@Aneri16 
Okay it was definately not there earlier, maybe it had not sinced or the reference was not it.

Thanks
