### ISSUE TITLE
Invertebrate Taxon Data -  Scodanibbio 2002

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#60]
@Aneri16 
Please extract data from this thesis. Sites will already have codes in the FBIS, please check and make them the same in the spreadsheet.

Scodanibbio   L. | 2002 | Is aquatic   invertebrate endemism in the Western Cape region of South Africa related to   the fynbos blackwaters? | Honours theis.   Botany Department. University of Cape Town, South Africa.
[Scodanibbio L. 2002.pdf](https://github.com/helendallas/FRC_FBIS/files/3696996/Scodanibbio.L.2002.pdf)

Page 14; Table 1: Description of the ten sites on the Breede River and tributaries for which
fieldwork was undertaken.Rand I stand for Reference and Impacted sites respectively,
as classified by Dallas et al. (1998).

Sampling method is Kick Net. Broad biotope =  Mixed.

Abiotic data:
Table 13: Results obtained from fieldwork on the Breede River and its tributaries,
indicating the date and site at which the variables were recorded.

Presence data only - list of taxa in following tables

Invertebrate data from Tables 14 to 21 only. Not the Appendices as these are already in Biobase

**Comment by aneriswanepoel** [comment]
@helendallas 
Data extraction is complete but cannot find site codes on FBIS.

**Comment by helendallas** [comment]
@Aneri16 
Helen has provided Aneri with FBIS SIte codes for capturing into the ad hoc spreadshet. Please note some river names need to be changed.

**Comment by aneriswanepoel** [comment]
@helendallas 
FBIS site codes have been captured and river names edited
