### ISSUE TITLE
Invertebrate Taxon Data - Wishart 1998 MSc

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#62]
@Janette-Lumley 

Please extract data from thesis.
 Issue: Data in thesis is pooled for three sites and all months.

Jenny Day re data - she has hard copy data which she will bring at the AGM

**Comment by helendallas** [comment]
@Janette-Lumley Please update me on this

**Comment by Janette-Lumley** [comment]
@helendallas did Jenny give you the hard copy data at the AGM?

**Comment by helendallas** [comment]
@Janette-Lumley No sadly not. Can daat be extracted from the thesis. If not lets leave for now. et me know and I can close it and reassign it. Thanks

**Comment by Janette-Lumley** [comment]
@helendallas I remember it was that book on my desk and I was struggling to find a lot of data in there. I need to go and get a few things from the office computer tomorrow before lockdown, so let me bring the book back and have another look before you close this ticket. I will let you know.

**Comment by helendallas** [comment]
Data in thesis not compatible with FBIS, No co-ordinates, or details per site and date.
