### ISSUE TITLE
Algae data: adapting the algae template to match the new biotope classification

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#67]
@philipfrenzel please adapt the algae template to match the new biotope classification that Helen suggested. This will involve trawling through the raw data to retrieve the specific biotope data.

**Comment by helendallas** [comment]
@phi Please confirm this is done so I can close the ticket

**Comment by philipfrenzel** [comment]
@helendallas Yes, completed. I'll close this comment with this reply. Thanks.
