### ISSUE TITLE
CFR Fish Data: Sampling methods dropdown needs ‘multiple’ to be added 

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#69]
@Aneri16 
Sampling method column in CFE Fish Data (CFR Fish Data_excl_SAIAB.xlsx): ‘multiple’ needs to be added to sampling methods dropdown, and we need to go back to papers with ‘unspecified’ and see if any should in fact be ‘multiple’. This is a 'Toni-linked issue'.

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
I have added the "multiple" option and have gone through the relevant papers to edit accordingly. There are 2 papers that I still need to look at but am waiting for Bruce to get back to me with the names of these papers so that I can finish up.

**Comment by jeremyshelton** [comment]
@Aneri16 thanks. Is this all sorted now or are you still looking through those papers of Bruce's?

**Comment by aneriswanepoel** [comment]
@jeremyshelton no everything is now done
