### ISSUE TITLE
CFR Fish Data: Substratum column needs 'mixed' category added

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#70]
@Aneri16 
Substratum column in CFE Fish Data (CFR Fish Data_excl_SAIAB.xlsx): ‘mixed’ needs to be added to Substratum dropdown, and we need to go back and check for papers with ‘mixed’ and see if any adjustments are needed. This is a 'Toni-linked issue'.

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
I am in the process of checking the relevant papers. Will let you know when it is done.

**Comment by jeremyshelton** [comment]
@Aneri16 are you still working on this, or is it now done?

**Comment by aneriswanepoel** [comment]
@jeremyshelton I am done with this.
