### ISSUE TITLE
CFR Fish Data: Hydraulic biotope column needs 'mixed' and 'unspecified' added

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#71]
@Aneri16 Hydraulic biotope column in CFR Fish Data (CFR Fish Data_excl_SAIAB.xlsx): ‘mixed’ and 'unspecified' need to be added to the dropdown, and we need to go back to check for papers  with ‘mixed’ or 'unspecified' and see if any adjustments to the dataset are needed. This is a 'Toni-linked issue'.

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
Same as for #70 - will let you know once complete (both can be addressed at the same time so easy to do and won't take long)

**Comment by jeremyshelton** [comment]
@Aneri16 just following up to check on the status of this task?

**Comment by aneriswanepoel** [comment]
@jeremyshelton this is also complete.
