### ISSUE TITLE
SA Fish data: date format consistency

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#76]
@Aneri16 @mokajee on second thought lets convert all date formats in the SA fish data to the same as that used in the CFR Fish data 👍

**Comment by Aneri16** [comment]
@jeremyshelton @mokajee 
I can do this today. Correct format then being YEAR-MONTH-DAY

**Comment by aneriswanepoel** [comment]
@jeremyshelton @mokajee 
OK, I can correct the SA fish data that Toni and I worked on and then Mo can just correct the data he is currently working on

**Comment by jeremyshelton** [comment]
@Aneri16 sounds good 👍
@mokajee
