### ISSUE TITLE
SA Fish Data: Tracking down the experts (aim for end Jan 2020)

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#77]
@mokajee lets see how much expert data we can track down by end Jan 2020. Olaf was happy with our expert list, so I reckon we can start firing off those emails 👍

**Comment by mokajee** [comment]
Awesome. I will start sending out emails from tomorrow.

**Comment by jeremyshelton** [comment]
@mokajee Great!
