### ISSUE TITLE
PDF Upload issues?

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#78]
@helendallas we need to make sure that we only upload PDFs not accessible online. This has not been the case thus far, as some of the these we have uploaded are available online! We also need to watch out for copyright infringements. We also need to revisit linking data to thees and the papers that stem from them....let's chat when you're back 👍

**Comment by jeremyshelton** [comment]
@Aneri16 please feed back on thesis copyrite protocols once you have contacted universities?

**Comment by aneriswanepoel** [comment]
@jeremyshelton @helendallas 
I phoned the Stellenbosch University Copyright Administrator re serving up theses on FBIS. We must submit a request to gain permission to serve these papers, and she said this is quite unlikely to happen. I can imagine this is the case for all universities and the papers for which they own the copyright.

**Comment by helendallas** [comment]
@jeremyshelton @Aneri16 
Okay, we need to systematically work through:
1 - all documents on the live site
2 - all invertebrate data spreadsheets. I have already started consolidating, so wait on this for now. To discuss today.

**Comment by helendallas** [comment]
@Aneri16 Please confirm this has been done. I think you went through everything in FBIS live

**Comment by aneriswanepoel** [comment]
Yes all thesis PDFs have been removed from FBIS and URLs added to spreadsheets
