### ISSUE TITLE
Toni still owner of fish records

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#79]
I see that Toni is still listed as the owner of the fish data…..this is incorrect. Not sure why it is still like this as I had assumed it was corrected ages ago.

@Aneri16 lets double-check that the record owner-column is correct in our new spreadsheet. The owner is always the person who collected the data....

<img width="826" alt="Screenshot 2019-11-04 at 12 07 02" src="https://user-images.githubusercontent.com/44292029/68113101-a16c8180-fefb-11e9-8e65-f73d560febe1.png">

@helendallas

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
There is no "owner" column in the spreadsheet, only "collector/assessor" so my guess is that the person who adds the data to FBIS might be assigned the "owner"?

**Comment by helendallas** [comment]
@jeremyshelton @Aneri16 
The collector/assessor probably needs to be renamed collector/owner, and it needs to be imported with the author details as per the spreadsheet. Jeremy, please make a note to check with Dimas why the collector/owner is Toni when the data are exported into csv.

**Comment by aneriswanepoel** [comment]
@helendallas @jeremyshelton 
Okay will change the column name in national and CFE fish spreadsheets, as well as the adhoc spreadsheet

**Comment by jeremyshelton** [comment]
@Aneri16 has this column now been updated?
@helendallas I have made a note to raise this with Dimas at our next catchup on Tuesday.

**Comment by aneriswanepoel** [comment]
@jeremyshelton yes I've renamed the column to "collector/owner"

**Comment by jeremyshelton** [comment]
@Aneri16 👍
