### ISSUE TITLE
Biobase - correcting georeferences

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#80]
Once Biobase Data is on the live site, the georeferences need to be corrected based on work already done by @Janette-Lumley 

@helendallas  needs to check how best to do this with Kartoza team

**Comment by helendallas** [comment]
@Janette-Lumley 
Please can you direct me to the spreadsheet of corrected georeferences for the Biobase sites. The Kartoza team are going to correct them from the backend before migration into the live site. This will save us a lot of editing :)

**Comment by Janette-Lumley** [comment]
@helendallas the spreadsheet is on dropbox under : FRC_FBIS Folder for FRC \Data for Consolidation \Invertebrate Data \ Biobase

**Comment by helendallas** [comment]
Ticket created for Dimas to correct georeference in the backend of the FBIS Live site. Ticket closed
