### ISSUE TITLE
Land cover

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#83]
@jeremyshelton 

I recommend we include a land use layer in FIS V3. Can you please discuss with admire as to the most appropriate one to serve up.

**Comment by jeremyshelton** [comment]
@helendallas ticket #1788 assigned to Admire

**Comment by jeremyshelton** [comment]
@helendallas before closing this ticket lets make sure we are 100% happy with the land use layer: 
<img width="1440" alt="Screenshot 2020-03-23 at 09 48 25" src="https://user-images.githubusercontent.com/44292029/77293721-8dc78900-6ceb-11ea-93d3-78f5fe115abe.png">
Admire said the LADA land use classes are the one we should go with. Does that look right to you?

**Comment by helendallas** [comment]
@jeremyshelton yes, but we have a ticket on the Epic V4, dont also need it here. this is FRCinternal

**Comment by jeremyshelton** [comment]
@helendallas Kept it here because I think it's an issue for FRC internal discussion.
