### ISSUE TITLE
Invertebrate Taxon Data - Consolidate into Master File

### ISSUE THREAD

**Issue by helendallas** [helendallas/FRC_FBIS#85]
Consolidate all invertebrate taxon data into Master File, then check for consistency, errors and missing fields.

**Comment by helendallas** [comment]
@Janette-Lumley 
How is the checking on GBIF going for this master list?

**Comment by Janette-Lumley** [comment]
@helendallas I am on just over 1000 entries.

**Comment by helendallas** [comment]
Final step to check master list ingested to FBIS with GBIF records

**Comment by helendallas** [comment]
Completed
