### ISSUE TITLE
CPUE in data upload forms?

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#87]
@helendallas I have lost track with what we decided in terms of entering (or background calculating) CPUE in the fish and invert upload forms. 

Here is Toni's mock-up on which the forms were built:
[Form_All.modules.pdf](https://github.com/helendallas/FRC_FBIS/files/3850962/Form_All.modules.pdf)

@Aneri16 please add Toni's input?

**Comment by aneriswanepoel** [comment]
@helendallas @jeremyshelton 
From Toni:
The idea with the CPUE is that it should be auto calculated (catch/effort). There should be a function in the background developed to draw CPUE graphs by doing that calculation.

**Comment by helendallas** [comment]
See ticket #91
