### ISSUE TITLE
Do taxa in our fish master list match those in GBIF?

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#89]
@mokajee 

Following our zoom with Kartoza today, I just wanted to touch base on the SA taxon master list and make sure that the taxa we list for SA correspond to those listed in GBIF (and that the actual taxon names correspond)? Or is this something we need to interrogate?

@Aneri16

**Comment by jeremyshelton** [comment]
@mokajee 
Please add the 'recipe' and 'ingredients' we used to generate our SA fish taxon master list to this ticket as discussed, and once you hear back from @toniolsen

**Comment by mokajee** [comment]
Having checked with @toniolsen, this is what I know about the **development of the master list**: 

- We are unsure where the original Excel spreadsheet (see attached) came from. I have a distant memory of being told that the list was given to us by SAIAB. [SA fish list_Master.xlsx](https://github.com/helendallas/FRC_FBIS/files/3882415/SA.fish.list_Master.xlsx)

- From the above spreadsheet, I then took Skelton's fish book and his two name-changes papers (2012; 2016) and updated the species list. 

- As far as i can tell, our list now contains all fish species known to occur in freshwater in southern Africa as a whole. @toniolsen says that this list was also checked by Neels Kleynhans, but I was not part of this communications. 

- I did send the list to both Paul Skelton and Roger Bills, but didn't receive any feedback from them. 

- I would say that I am 99.9% certain that our list contains all the fish species that occur in the country (and a few that don't). Unfortunately, there isn't an accepted list available for us to cross reference with. Hence, I think publishing our list early next year, could be a much needed start, in terms of coming to a consensus on this.

**Comment by mokajee** [comment]
> @mokajee
> 
> Following our zoom with Kartoza today, I just wanted to touch base on the SA taxon master list and make sure that the taxa we list for SA correspond to those listed in GBIF (and that the actual taxon names correspond)? Or is this something we need to interrogate?
> 
> @Aneri16

@toniolsen Says that Kartoza pulled all South African fish data from GBIF (minus the marine species). But that this is worth double checking with Dimas. 

- My suggestion is to first check with Dimas to see if they used our list for the species search, or pulled the fish species independently (I highly doubt this). 

- If they used our list to determine what species they pulled onto FBIS, then we do need to double check to ensure that there aren't any 'new' species on GBIF that aren't on our list. If possible, I suggest that we search for and download all data for Actinopterygii, Chondrichthyes and Sacropterygii. We would then need to exclude results in the ocean and estuaries. The output of this search should give us all the species on GBIF that occur in inland ecosystems in SA. 
--

**Comment by jeremyshelton** [comment]
@mokajee 
Ok thanks for this. I will double check with Dimas. Probably best to just call up (from GBIF) all the taxa from our master list, but let me give this some thought. 
Will chat to Dimas about this this week...

**Comment by helendallas** [comment]
@jeremyshelton I assume this has been resolved. Closing ticket
