### ISSUE TITLE
Check PDF uploads in live site

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#90]
@Aneri16 could you or @melandrirafferty please check all documents in FBIS live site to make sure they fit our new criteria for PDF uploads: documents that do not exist online, for example consulting reports, some other unpublished reports that never made it online (and are often very old). @helendallas anything to add here?

**Comment by aneriswanepoel** [comment]
@jeremyshelton yes can do today

**Comment by jeremyshelton** [comment]
Great, thanks 👍

**Comment by aneriswanepoel** [comment]
@jeremyshelton I have just finished going through the FBIS live site and I have deleted all the documents that should not be there. So only reports are on the site

**Comment by jeremyshelton** [comment]
@Aneri16 that's fantastic. Good work. Will check through this asap 👍
