### ISSUE TITLE
Should CPUE feature in the upload forms for fish and invert data?

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#91]
@Aneri16 @toniolsen @helendallas 
I am a little unclear on what we decided with CPUE in the forms for fish and invert data? At present it does not feature, but I seem to recall this was something that Kartoza would calculate in background (e.g. abundance divided by effort) and then this would be displayed somewhere? (not sure where?)

Or maybe I have this wrong and we chose to not report on CPUE?

**Comment by helendallas** [comment]
See ticket #87 

@jeremyshelton We decided it should be auto-calculated where data were available. I recommend we park this for FBIS V5.

I am closing #87

**Comment by jeremyshelton** [comment]
@helendallas I think the idea was that it would be useful for the FBIS form to auto-calculate CPUE, and for this to be included in the downloaded csv.....but this might not be that straightforward because effort can be time or area etc. But maybe something with trying?

**Comment by helendallas** [comment]
@jeremyshelton I suggest we park this for now and see if it is something we have budget etc to do in the next phase.
