### ISSUE TITLE
Recipe for PDF uploads

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#92]
@Aneri16 could you please make a ticket explaining the recipe for what we do and what we don't upload via the FBIS PDF uploader. Then for those that we do upload, a brief indication of where url, doi, database description etc are appropriate. thanks

**Comment by Aneri16** [comment]
@jeremyshelton 
Will do so today

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
I have created the ticket (#94) and it is in the "information" column. Have a look and let me know if I need to add anything?
