### ISSUE TITLE
National fish data ready for Kartoza?

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#93]
@Aneri16 
How is the progress coming along in terms of adjusting the National Fish spreadsheet as per Kartoza's requests? Let me know when ready & I will check and replace the one currently shared in dropbox 👍 Thanks

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
Mel and I have both finished our sections and I am now just going through the sheet to make sure everything is correct etc

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
Okay I have finished going through the data and I think it is ready for Kartoza. It is in the "Shared with Kartoza" folder: National fish data _ 22 Nov

**Comment by jeremyshelton** [comment]
@Aneri16 great. Have just checked through it. All looks good 👍 Will share with Dimas now...
