### ISSUE TITLE
Protocol for uploading PDFs and other information sources to FBIS

### ISSUE THREAD

**Issue by aneriswanepoel** [helendallas/FRC_FBIS#94]
**The following PDFs can be uploaded to FBIS:** 
- Reports
- Those documents which cannot be found online anymore

**The following PDFs cannot be uploaded to FBIS:**
- Theses
- Journal articles

For the excel spreadsheets for bulk ingestion:
**In terms of uploading thesis documents to FBIS:**
- Provide only a link (URL) to the university website where the PDF can be accessed
- Provide author(s), year, title

**In terms of uploading journal articles to FBIS:**
- Provide only the DOI number
- Provide author(s), year, title

**In terms of referencing databases:**
- Provide full description (eg. Cape Nature State of Biodiversity Database 2015)
- No website links 

**In terms of uploading reports:**
- Provide author(s), full name of report, organization for which report was compiled and report 
  number

**Comment by jeremyshelton** [comment]
@Aneri16 
Thank you very much. That's spot on. So glad we resolved this 👍

**Comment by helendallas** [comment]
**Clarification in terms of Citation Manager and Document Manager:**

When data is ingested into FBIS from an excel file with the information above, it is added to the CITATIONS Manager (**Administration/Citations**)

Citations include all study references in the FBIS – the URL or DOI is for theses and peer-reviewed papers are added here.

All Published Reports (and some papers/theses that are not available online at all) are added via DOCUMENTS Manager (**Administration/Documents**)
The title should be the full study reference: Author(s), Date, Title, Source.

If the PDF is not available then use the "Document Not Available" pdf below:
[Document Not available.pdf](https://github.com/helendallas/FRC_FBIS/files/4455647/Document.Not.available.pdf)
