### ISSUE TITLE
FRC big picture ticket: Fish data for FBIS v3 (Feb 2020)

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#95]
@Aneri16 @mokajee 
Hi guys, 
Well done to us on reaching our November fish data milestone. Looking forward, there are four main tasks to be completed during the next phase before FBISv3 is released in Feb next year:

**1. SA non-native fish data** 
Systematically search google for data on Non-native fish data in SA
**2. SA expert data**
Work through our list (https://www.dropbox.com/sh/o0ktzp3op25bzhc/AACqH-wqNT3amtuZqEzoCh3ca?dl=0) of experts sending out email data requests. Do we need to think about data sharing agreements?
**3. SA organisation data**
Just like we have done for CapeNature in the WC, we need to make sure we contact all major organisations that might be sitting on freshwater fish data. These include regional conservation organisations (e.g. DENC, KZN Wildlife...etc), Universities (E.G. North West Universities' Water research Group), as will as SANParks, CSIR, Anchor Environmental, Groundtruth, 
**4. Continue refining SA taxon list and GBIF interoperability**
We need to make sure we have the right 'recipe' behind our taxon master list, AND that this is the list that Dimas is using to pull from GBIF
**5. Make sure out fish dataset tracker is up to date and useful**
I reckon we are going to need to combine our lists of experts and low-hanging data fruit into an updated version of the dataset tracker: that way we can keep track of what we already have, and what we still need to tick off. (The existing data set tracker is here: https://www.dropbox.com/sh/jjdjzvfc9fg5mom/AABC2lgjh-vQst7BCIfM8EN5a?dl=0)

@helendallas

**Comment by jeremyshelton** [comment]
Lets have a fish team meeting before the year end to work through these & plan the next pew months. @mokajee I know you are busy with your chapter and proposal. Perhaps the week of 9-13 December?

**Comment by aneriswanepoel** [comment]
@jeremyshelton @mokajee 
Meeting sounds good - I just won't be able to do the 13th. Any other day is fine though

**Comment by mokajee** [comment]
Hi Both, 

Yes, I agree a meeting is much needed. I've picked up several things that need to be discussed and dealt with. I should be done with the proposal this week (Thursday, I hope), so could potentially meet next week, if that works for you both. I can't commit to a specific day between the the 9-13th as I will be presenting my upgrade to the Department on one of those days. 

If next  week does not work, then I will confirm later this week which  days I will be available between the 9-13. 

Sorry for the complications.

**Comment by mokajee** [comment]
I've also been receiving feedback from the experts I have contacted thus far. Many have committed to getting us the data in the coming months, with some data already being sent to me.

**Comment by jeremyshelton** [comment]
OK good. Thanks Mo. I am away next week, so lets aim for 9-13th. I can do any day except Frida, so lets set a date once you know when your proposal is going to be...

**Comment by mokajee** [comment]
Just got feedback that my seminar wont be happening in December. So I am available on any day between 9-13 December.

**Comment by jeremyshelton** [comment]
Cool. Sent out invite for 10 Dec @10h00


www.frcsa.org.za
