### ISSUE TITLE
FBIS search glitches

### ISSUE THREAD

**Issue by mokajee** [helendallas/FRC_FBIS#96]
The map on the website does not remove invert records when I try to search for all fish in the country.

**Comment by mokajee** [comment]
@jeremyshelton is it possible to batch download all the FBIS data at once? Or does this have to go through Kartoza?

It might be useful to have this as an option for the public?

**Comment by jeremyshelton** [comment]
@mokajee in relation to 'The map on the website does not remove invert records when I try to search for all fish in the country' please provide a url for this query on FBIS, and/or a screenshot so ai can check it out 👍

**Comment by jeremyshelton** [comment]
@mokajee 'is it possible to batch download all the FBIS data at once' yes it is: Simply make sure FBIS is selected in 'data sources'. Then hit search > all sites > detailed dashboard > download .csv

Have a go and I'll walk you through any stumbling blocks 👍

<img width="577" alt="Screenshot 2019-11-28 at 06 11 53" src="https://user-images.githubusercontent.com/44292029/69776758-274fb580-11a6-11ea-8b51-efeafd1077d6.png">

**Comment by mokajee** [comment]
> @mokajee in relation to 'The map on the website does not remove invert records when I try to search for all fish in the country' please provide a url for this query on FBIS, and/or a screenshot so ai can check it out 👍

When I select the fish module, invert taxa still come up in the results: 
![image](https://user-images.githubusercontent.com/55532969/69793911-fdac8380-11d1-11ea-907f-de8885ddbc0b.png)

**Comment by mokajee** [comment]
http://freshwaterbiodiversity.org/map/#site-detail/taxon=&search=&siteId=&collector=&category=&yearFrom=&yearTo=&months=&boundary=&userBoundary=&referenceCategory=&spatialFilter=&reference=&endemic=&conservationStatus=[]&modules=1&validated=[%22validated%22,%22non%20validated%22,%22sass%20accredited%22,%22non%20sass%20accredited%22]&sourceCollection=[%22fbis%22,%22gbif%22]&ecologicalCategory=

**Comment by jeremyshelton** [comment]
@mokajee this should be rectified once v2.6 is deployed. Please make a note to test this again once v2.6 is live...

**Comment by helendallas** [comment]
@mokajee I am closing this ticket
