### ISSUE TITLE
Rivers Database fish data

### ISSUE THREAD

**Issue by jeremyshelton** [helendallas/FRC_FBIS#98]
@Aneri16 we need to add the RD fish data from dropbox to our fish spreadsheet for Kartoza to upload for FBIS v3

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
I'm only seeing this ticket now... I don't think this data was added then.

**Comment by jeremyshelton** [comment]
OK, please have a look, confirm that we didn't include it, and let me know what you think it would require (time-wise) to add this to our [spreadsheet](https://www.dropbox.com/sh/ilfrbn6klyesv3k/AAA520tmniByikaY-Of2CCr9a?dl=0)?

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
I've just had a look on FBIS and it seems the data has been uploaded already. Not sure by whom or when but it is there.

**Comment by jeremyshelton** [comment]
Ok cool, well it it’s in, its in 👍 please try do a few extra cross checks to make sure it’s all in there. Thanks

**Comment by aneriswanepoel** [comment]
@jeremyshelton 
I've checked a few sites and the data seems to be there, but just doesn't include the abundances that are in the spreadsheet. Everything else seems to be included though

**Comment by jeremyshelton** [comment]
Hmm OK thanks. Are there a lot of abundance data? Do you think we should try add that this week?

**Comment by aneriswanepoel** [comment]
There are 3267 records with abundances. Perhaps it was a case of the abundance column not being read correctly? I noticed that the column is called "Catch/number" but I'm not sure if that is the issue? Spreadsheet is here:
C:\Users\User\Dropbox\FRC_FBIS Data for Consolidation\Data for Consolidation\Fish data\Rivers Database Fish Data

Unless I have got it wrong and abundances are indeed on FBIS but I'm just being blind/stupid. Could you check one or two sites and confirm? For example: 

A2ELAN-BESTE
A3GMAR-LOTTE
X3SAND-THULA
 
Thanks!

**Comment by aneriswanepoel** [comment]
When I download the CSV for the sites, abundance is not included

**Comment by jeremyshelton** [comment]
Is there sampling effort associated with those abundance data?

**Comment by aneriswanepoel** [comment]
Yes

**Comment by jeremyshelton** [comment]
OK, lets  address in FBISv5.

**Comment by helendallas** [comment]
@Aneri16 Has this been resolved yet? Note to address in FBIS V5.

**Comment by jeremyshelton** [comment]
@helendallas looks like this is all sorted.
Closing ticket.
